# Environment
## Ayuntamiento de Barcelona

In [16]:
import plotly.express as px
import geopandas as gpd
import shapely.geometry
import numpy as np
import wget
import fiona
import folium

In [2]:
import pandas as pd
import plotly.graph_objects as go

In [151]:
x = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\\2022_qualitat_aire_estacions.csv")

In [168]:
x

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,8,Barcelona,19,Barcelona,43,999,2023,3,6,31.10,...,20.40,V,22.30,V,23.30,V,23.10,V,22.70,V
1,8,Barcelona,19,Barcelona,43,999,2023,3,7,18.50,...,19.70,V,21.90,V,23.00,V,23.60,V,22.70,V
2,8,Barcelona,19,Barcelona,43,999,2023,3,8,21.40,...,20.00,V,21.20,V,18.20,V,20.20,V,20.20,V
3,8,Barcelona,19,Barcelona,43,999,2023,3,9,20.70,...,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N
4,8,Barcelona,19,Barcelona,54,999,2023,3,6,22.70,...,14.90,V,18.70,V,19.70,V,24.20,V,25.10,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,8,Barcelona,19,Barcelona,57,109,2023,3,9,3.80,...,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N
256,8,Barcelona,19,Barcelona,57,101,2023,3,6,2.63,...,2.65,V,2.54,V,2.51,V,2.73,V,2.62,V
257,8,Barcelona,19,Barcelona,57,101,2023,3,7,2.61,...,2.79,V,2.78,V,2.39,V,2.63,V,2.53,V
258,8,Barcelona,19,Barcelona,57,101,2023,3,8,2.60,...,2.95,V,3.18,V,2.93,V,3.00,V,3.86,V
259,8,Barcelona,19,Barcelona,57,101,2023,3,9,4.34,...,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N

In [161]:
# para sacar el contaminante en la tabla de arriba la general por barrio.
x = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\contaminants.csv")
x

    Codi_Contaminant                Desc_Contaminant Unitats
0                  1                             SO2   µg/m³
1                  7                              NO   µg/m³
2                  8                             NO2   µg/m³
3                  9                           PM2.5   µg/m³
4                 12                             NOx   µg/m³
5                 14                              O3   µg/m³
6                  6                              CO   mg/m³
7                 10                            PM10   µg/m³
8                 22                    Black Carbon   µg/m³
9                999           Biomassa Black Carbon       %
10               998  Flow C (Mesura interna equip)
11               997   Flow 1 (Mesura interna equip)     NaN
12               996   Flow 2 (Mesura interna equip)     NaN

In [167]:
x.MES.value_counts()

3    260
Name: MES, dtype: int64

sacar el mean por dia, evaluar el tipo de contaminante por el codigo= buscarlo en el el df de los contaminantes
conectar el data frame con el de arriba el completo para aberiguar la calidad por barrio con el codigo de la estacio. 
if estacio = entonces...

In [174]:
x = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\Qualitat_Aire_Detall.csv")
x.sample(5)

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
163,8,Barcelona,19,Barcelona,44,14,2023,3,9,51.0,...,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N
36,8,Barcelona,19,Barcelona,54,997,2023,3,6,3822.2,...,3855.0,V,3855.0,V,3855.0,V,3854.6,V,3845.6,V
205,8,Barcelona,19,Barcelona,43,901,2023,3,7,0.0,...,0.0,V,0.0,V,0.0,V,0.0,V,0.0,V
32,8,Barcelona,19,Barcelona,43,997,2023,3,6,3824.0,...,3849.0,V,3849.0,V,3848.3,V,3840.2,V,3865.2,V
13,8,Barcelona,19,Barcelona,54,22,2023,3,7,1086.0,...,558.0,V,476.0,V,580.0,V,1561.0,V,1384.0,V

In [175]:
x.ESTACIO.value_counts()

57    64
43    52
54    52
44    28
58    20
50    16
4     16
42    12
Name: ESTACIO, dtype: int64

In [233]:
x = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\\2022_qualitat_aire_estacions.csv")

In [234]:
x

,Estacio,nom_cabina,codi_dtes,zqa,codi_eoi,Longitud,Latitud,ubicacio,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Clas_1,Clas_2,Codi_Contaminant
0,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.38640,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,8
1,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.38640,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,14
2,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.38640,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,7
3,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.38640,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,12
4,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,8
5,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,14
6,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,10
7,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,1
8,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,6
9,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,7
10,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,12
11,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,8
12,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,14
13,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,10
14,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,1
15,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,6
16,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,7
17,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,12
18,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,8
19,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,14
20,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,10
21,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,1
22,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,6
23,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,7
24,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,12
25,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.40390,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,8
26,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.40390,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,10
27,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.40390,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,7
28,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.40390,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,12
29,42,Barcelona - Sants,ID,1,8019042,2.1331,41.37880,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,8
30,42,Barcelona - Sants,ID,1,8019042,2.1331,41.37880,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,7
31,42,Barcelona - Sants,ID,1,8019042,2.1331,41.37880,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,12
32,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,8
33,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,14
34,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,10
35,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,1
36,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,6
37,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,12
38,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,7
39,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,8
40,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,14
41,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,10
42,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,7
43,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,12

In [171]:
x.Estacio.value_counts()

43    7
44    7
57    7
54    7
58    5
50    4
4     4
42    3
Name: Estacio, dtype: int64

### capacidad acustica

###### De 55 a 75 dB

###### Es un nivel de ruido considerable. Por ejemplo, un aspirador genera 65 dB. Una calle con mucho tráfico alcanza los 75 dB. El despertador o la televisión a un volumen elevado, pueden llegar a los 75 dB, igual que una lavadora, el teléfono móvil o una batidora.

###### De 75 dB a 100 dB

###### Es un nivel alto de ruido, la sensación es molesta. Por ejemplo, en un atasco hay 90 dB de ruido. También el que suele emitir una sirena de policía.

TOTAL_D        Ruido total en periodo dia
FFCC_E         Ruido de ejes ferroviarios y tranvía en período tarde
PATIS_D        Ruido en patios interiores en período día
OCI_N          Ruido de ocio y aglomeración de personas en período noche
VIANANTS_E     Ruido en calles peatonales en período tarde
VIANANTS_D     Ruido en calles peatonales en período día
INDUST_DEN     Ruido de industria en período Lden
INDUST_N       Ruido de industria en período noche
INDUST_E       Ruido de industria en período tarde
INDUST_D       Ruido de industria en período día
FFCC_DEN       Ruido de ejes ferroviarios y tranvía en período Lden
FFCC_N         Ruido de ejes ferroviarios y tranvía en período noche 
FFCC_D         Ruido de ejes ferroviarios y tranvía en período día
TOTAL_E        Ruido total en periodo tarde
GI_TR_DEN      Ruido de grandes infraestructuras viarias en período Lden 
GI_TR_N        Ruido de grandes infraestructuras viarias en período noche
GI_TR_E        Ruido de grandes infraestructuras viarias en período tarde
GI_TR_D        Ruido de grandes infraestructuras viarias en período día
TRANSIT_DEN    Ruido de tráfico viario en período Lden
TRANSIT_N      Ruido de tráfico viario en período noche
TRANSIT_E      Ruido de tráfico viario en período tarde
TRANSIT_D      Ruido de trafico viario en periodo dia
TOTAL_DEN      Ruido total en período Lden
TOTAL_N        ruido total en periodo noche
PATIS_E        Ruido en patios interiores en período tarde

In [190]:
y = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\capacidad acustica\\2017_barris_soroll_bcn_long.csv")

In [191]:
y

,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Concepte,Rang_soroll,Valor
0,1,Ciutat Vella,1,el Raval,TOTAL_D,<40 dB,7.73%
1,1,Ciutat Vella,1,el Raval,TOTAL_D,40-45 dB,26.98%
2,1,Ciutat Vella,1,el Raval,TOTAL_D,45-50 dB,7.38%
3,1,Ciutat Vella,1,el Raval,TOTAL_D,50-55 dB,11.97%
4,1,Ciutat Vella,1,el Raval,TOTAL_D,55-60 dB,19.85%
...,...,...,...,...,...,...,...
18975,10,Sant Martí,73,la Verneda i la Pau,PARCS_D,60-65 dB,0.00%
18976,10,Sant Martí,73,la Verneda i la Pau,PARCS_D,65-70 dB,0.00%
18977,10,Sant Martí,73,la Verneda i la Pau,PARCS_D,70-75 dB,0.00%
18978,10,Sant Martí,73,la Verneda i la Pau,PARCS_D,75-80 dB,0.00%
18979,10,Sant Martí,73,la Verneda i la Pau,PARCS_D,>=80 dB,0.00%

In [192]:
y.Codi_Barri.value_counts()

1     260
38    260
54    260
53    260
52    260
     ...
25    260
24    260
23    260
22    260
73    260
Name: Codi_Barri, Length: 73, dtype: int64

In [142]:
y = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\capacidad acustica\\2017_ciutat_mapa_estrategic_soroll_bcn_long.csv")

In [143]:
y

    Rang_soroll Concepte   Valor
0        <40 dB  TOTAL_D   2.60%
1      40-45 dB  TOTAL_D  14.49%
2      45-50 dB  TOTAL_D  16.38%
3      50-55 dB  TOTAL_D  10.53%
4      55-60 dB  TOTAL_D  17.06%
..          ...      ...     ...
255    60-65 dB  PARCS_D   0.00%
256    65-70 dB  PARCS_D   0.00%
257    70-75 dB  PARCS_D   0.00%
258    75-80 dB  PARCS_D   0.00%
259     >=80 dB  PARCS_D   0.00%

[260 rows x 3 columns]

In [193]:
y = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\capacidad acustica\\2017_tramer_mapa_estrategic_soroll_bcn_long.csv")

In [197]:
y.TR

,TRAM,GEOM_WKT,Concepte,Valor
0,T04719W,MULTILINESTRING ((430229.788593716 4586585.199...,TOTAL_D,70 - 75 dB(A)
1,T19941Z,MULTILINESTRING ((432928.898296899 4584019.987...,TOTAL_D,45 - 50 dB(A)
2,T18111R,MULTILINESTRING ((429953.263102905 4588161.440...,TOTAL_D,55 - 60 dB(A)
3,T03222Y,MULTILINESTRING ((427949.038250661 4580946.042...,TOTAL_D,60 - 65 dB(A)
4,T17625I,MULTILINESTRING ((433950.188943519 4585741.213...,TOTAL_D,55 - 60 dB(A)
...,...,...,...,...
448945,T08868Y,MULTILINESTRING ((431756.999149255 4585026.456...,PATIS_E,< 40 dB(A)
448946,P98700,"MULTILINESTRING ((433540.3279 4587660.4522,433...",PATIS_E,< 40 dB(A)
448947,P98690,"MULTILINESTRING ((433545.366 4587658.255,43354...",PATIS_E,< 40 dB(A)
448948,P27312,"MULTILINESTRING ((430555.994 4585460.656,43055...",PATIS_E,< 40 dB(A)
448949,P28659,"MULTILINESTRING ((428842.519 4587255.013,42883...",PATIS_E,< 40 dB(A)

In [202]:
print(set(y.TRAM))

{'T18492R', 'P82041', 'T06060K', 'T21586Z', 'P25590', 'T07088A', 'T16570G', 'T17321V', 'T04380P', 'T02165C', 'P70560', 'T03292M', 'P90571', 'P82610', 'T02628M', 'T03646S', 'T00570D', 'T00526Z', 'P05050', 'T03279P', 'T02457L', 'P95912', 'T10275E', 'T05932D', 'T20978H', 'T00879V', 'T07905I', 'T17396O', 'T01162V', 'T00382B', 'T07562F', 'T12080D', 'T03197O', 'T21201V', 'T08012K', 'T01775S', 'T18944Y', 'T17661M', 'T15529B', 'T21170F', 'T00853L', 'T15178Y', 'T17246B', 'P28661', 'T10145V', 'T02047X', 'T17624H', 'P33790', 'T02418E', 'T04025Z', 'T00823F', 'T16467I', 'T04991K', 'P95980', 'T21370L', 'T01897B', 'T07272Y', 'T04596D', 'T10638L', 'T20677X', 'P29544', 'T13773D', 'P70070', 'P12860', 'P82030', 'T17868Z', 'T20750P', 'T17584Q', 'T16731F', 'T08274E', 'T21452M', 'T03362J', 'P11980', 'T02021N', 'T00496K', 'RD0127W', 'T01080U', 'T21349O', 'T12353J', 'T02392L', 'T05057L', 'T02378N', 'T08665P', 'T08690Q', 'T20323A', 'T09152Z', 'T17751N', 'T20121S', 'T06978V', 'T16373D', 'T02513C', 'T18963B', 'T09059D', 'T07964T', 'T07908L', 'T04930X', 'T10789Z', 'T13054F', 'T20416E', 'T00506V', 'T07543C', 'T01502V', 'T14335P', 'T02525G', 'T14657E', 'P25920', 'P06200', 'T04917A', 'T01501U', 'T14733Z', 'P25060', 'T10471G', 'P71440', 'P81020', 'T02397Q', 'T03296Q', 'T15943L', 'T13511J', 'T08717K', 'T04301A', 'T05841B', 'T05410I', 'T12879I', 'T00942L', 'RD0093O', 'T21007V', 'T16422V', 'P94891', 'T00677N', 'T15829K', 'T13912W', 'T17546K', 'T18337H', 'T09559S', 'T03164F', 'T08702D', 'T10510W', 'P80580', 'T17361D', 'T16334W', 'T03218C', 'T21512H', 'P60080', 'P90720', 'T18657U', 'T09366L', 'T21474S', 'RL0010J', 'T04717U', 'T21244G', 'T10606D', 'P26360', 'T12691Y', 'LRD0008', 'P27642', 'T10860P', 'T03186L', 'T09689B', 'T13854D', 'P70050', 'T01734J', 'T19456R', 'P84100', 'T17364G', 'T20888G', 'P71002', 'T09675V', 'T07975W', 'T07711A', 'T11125V', 'T12939D', 'P06423', 'T08130P', 'T04868I', 'T19335J', 'T09571O', 'T05930B', 'RD0033G', 'T02835R', 'T08921M', 'T20613H', 'T02983C', 'T20681T', 'T08594R', 'RD0027A', 'T19327J', 'T14450R', 'T10482J', 'T00141M', 'T17874X', 'T07952P', 'T13098R', 'T02388P', 'T17308Y', 'T09586V', 'T18220V', 'T03361I', 'T00247V', 'T16503V', 'T05224I', 'T06743E', 'T14839I', 'T08632G', 'LRD0020', 'T04904V', 'T00337W', 'T03312Z', 'T15951L', 'T04978N', 'T12613K', 'T03734R', 'P41200', 'T21173I', 'T07696S', 'T05289Z', 'T08096E', 'T08952T', 'T08453F', 'P80730', 'T03455N', 'T10832L', 'T05473X', 'T09938Z', 'T13526Q', 'T06090Q', 'T18733P', 'T14396C', 'T10114O', 'T12693A', 'P92010', 'T11265G', 'T07769S', 'T06251P', 'T19257M', 'P70300', 'T04956H', 'T03554P', 'P20550', 'T09441F', 'T13276R', 'T15725D', 'T18222X', 'T07026M', 'T08847T', 'P12501', 'T18251C', 'T03477T', 'T01889B', 'T07746L', 'T19666Z', 'T06572D', 'T17917R', 'T20574R', 'T02206U', 'T04181K', 'P91665', 'T10888B', 'T08476M', 'T08940P', 'T14352Q', 'P97602', 'T09329G', 'T05446U', 'T06754H', 'T11954Y', 'P60930', 'T16330S', 'T18265I', 'T20265H', 'T03926X', 'T12789H', 'P60460', 'T13701N', 'T18372K', 'P07933', 'P96380', 'T15286B', 'T07301M', 'T05182P', 'T01555I', 'T02166D', 'T04251H', 'P80880', 'LRD0017', 'T00539E', 'T15297E', 'T02119W', 'T01833L', 'P60950', 'T00019L', 'T05540R', 'P15391', 'T13978O', 'T18851U', 'T02601B', 'T00596N', 'P29410', 'T07432W', 'T08609H', 'T18776A', 'P25710', 'T21353K', 'P99381', 'P33300', 'P91043', 'P06601', 'T18235C', 'T09628O', 'T01202M', 'T09596X', 'T12141Z', 'T20060W', 'T04424K', 'T21509M', 'P21312', 'P41340', 'P08450', 'T18249I', 'T08284G', 'T04100T', 'T18494T', 'T05984P', 'T14773H', 'T02770R', 'T09855X', 'T13228J', 'T08957Y', 'T17142U', 'T12099O', 'T19466T', 'P91420', 'T20503C', 'T10779X', 'T09516H', 'T17338E', 'T10412V', 'T11359L', 'T18117X', 'T20671R', 'T02499V', 'T00364Z', 'T00818I', 'P31361', 'T18544M', 'T03112T', 'T02931Q', 'T16689U', 'P34471', 'T06157S', 'P08610', 'T07403R', 'T16926O', 'P21090', 'T01737M', 'P60430', 'P33614', 'T00149U', 'T09903O', 'T10462F', 'P82690', 'T06324P', 'T16326W', 'T02556N', 'T16964U', 'T03242C', 'T17025Q', 'P31300', 'T10094B', 'T09051V', 'T01034O', 'T02784X', 'T14102A', 'T07612Y', 'P06591', 'T00977W', 'T10605C', 'T03723O', 'T21143C', 'T08734L', 'T17993D', 'T12354K', 'T06343S', 'T07841J', 'T00776P', 'RL0055C', 'T00566H', 'T16129T', 'T01351Y', 'T12542M', 'T02354F', 'T04792F', 'P97930', 'P93680', 'T02100L', 'T03246G', 'T02790V', 'T01716H', 'T04896M', 'T08036S', 'T21239J', 'T09813N', 'T18983F', 'T05968P', 'T07884U', 'T16000D', 'T09217Z', 'P82760', 'P25690', 'P72131', 'T03117Y', 'T00471B', 'T05568D', 'T02321W', 'T03116X', 'T19962E', 'P15120', 'T08404W', 'P50531', 'P12420', 'P41230', 'P95040', 'T19963F', 'T07941M', 'T08497R', 'T00598P', 'T09500Z', 'T17354E', 'T02566P', 'T19188Q', 'T04960D', 'P81040', 'T04501G', 'T02000I', 'T04903U', 'T09569U', 'T08571K', 'T20821N', 'T07147U', 'T05156N', 'T10762O', 'T00024I', 'P27110', 'T04748B', 'T10097E', 'T02865X', 'T17871U', 'P70600', 'T08718L', 'T16354A', 'P80430', 'P96570', 'T12580S', 'T17648P', 'T21472Q', 'P21480', 'P15840', 'T05997U', 'T09266I', 'T09923S', 'T05354R', 'T11471K', 'T08932P', 'T17287K', 'T00066S', 'T08145W', 'T14638B', 'T19648X', 'T04363O', 'T11101N', 'T10774S', 'RD0012L', 'T20658U', 'T06131I', 'P94170', 'T15596M', 'T20695Z', 'T19553R', 'T13187R', 'T10926Q', 'T17160W', 'T09673T', 'P83350', 'T01346B', 'T15748K', 'T16791R', 'T07262W', 'P25700', 'T19132A', 'T11157D', 'T05868M', 'T00798V', 'T04472S', 'T13412H', 'P71693', 'T18451I', 'T09765W', 'T03273J', 'T07254W', 'T11115T', 'T11446J', 'T07161S', 'T08028S', 'T12586Y', 'T11026T', 'T20814O', 'T19159L', 'P16090', 'T16730E', 'T19353L', 'T17531D', 'P31410', 'P21370', 'T11321X', 'T21456Q', 'T04226G', 'T10640F', 'T01243V', 'T18047A', 'T09944X', 'T07977Y', 'T00712Z', 'T00893T', 'T04849F', 'T07219T', 'T18038Z', 'T21072E', 'T21258M', 'T19848D', 'T04185O', 'T21360J', 'T11062X', 'T05213F', 'P12850', 'P81490', 'T04656Y', 'P25441', 'P16511', 'T02439J', 'P98450', 'T10544G', 'P50460', 'P93410', 'T20593U', 'T17454H', 'T03597A', 'T08184D', 'T20876C', 'T03064C', 'T11055Y', 'P12691', 'T01885X', 'T20703I', 'T17238B', 'T15922G', 'P92050', 'P34101', 'T20894E', 'T12462N', 'P35490', 'P72200', 'T13733V', 'T07149W', 'P25560', 'T19250F', 'T06002A', 'T06107I', 'T04607P', 'T12362K', 'T04117C', 'T03293N', 'T21280K', 'P92860', 'T00544B', 'T03286O', 'T18689C', 'T20740N', 'T12265K', 'T15209O', 'T21487X', 'T08102L', 'T09210S', 'T19077K', 'T18443I', 'T18998M', 'T19587B', 'T01038S', 'T18335F', 'P92630', 'T17716K', 'T00528B', 'T12531J', 'T16794U', 'T10991Z', 'T04853B', 'P93860', 'T02001J', 'T21018Y', 'T19572U', 'T11986G', 'T06726D', 'T13350K', 'T02900J', 'T16019O', 'P95150', 'T15675K', 'T02251Z', 'T01803F', 'P20750', 'P71563', 'T19628T', 'T11288N', 'T03469T', 'T12398W', 'T06504R', 'T19565V', 'T11567R', 'T17455I', 'T16605A', 'T09749W', 'T02793Y', 'T16408X', 'T13683C', 'T08218W', 'T02428G', 'T11012N', 'P60620', 'T18281I', 'P27840', 'T08158B', 'T20735Q', 'T21492U', 'P30381', 'T08141S', 'T07762L', 'T18064B', 'T07013H', 'T10741J', 'T00119O', 'T10817M', 'P40560', 'T12147F', 'LRD0044', 'T05660Y', 'T07651F', 'T19228H', 'T11528K', 'T07851L', 'P71680', 'T20152Z', 'T10579R', 'T09071Z', 'T04435N', 'NS0007G', 'T01830I', 'T11775X', 'T05865J', 'T01500T', 'T02198L', 'T00088Y', 'T17680P', 'T17681Q', 'T03621J', 'T05309M', 'T20549Q', 'T16904I', 'T19040X', 'T15413Q', 'P92090', 'T07917M', 'T21381O', 'T12108Y', 'T02193G', 'T08043R', 'T05911Y', 'P12570', 'T00262U', 'T21506J', 'T18802L', 'P95952', 'P40240', 'T20479T', 'T05138L', 'T10331V', 'T18685Y', 'T14920A', 'T11393N', 'T06742D', 'T17183D', 'T10496P', 'T10285G', 'T19407I', 'T08191C', 'P50690', 'T12670T', 'P98390', 'T06271T', 'T16151R', 'T17559P', 'NS0013M', 'T11039Y', 'T19503H', 'T07642E', 'T11950U', 'T19900Q', 'T10423Y', 'T15696P', 'T05036G', 'T12997N', 'T10246Z', 'T11247E', 'T13778I', 'P06702', 'T20674U', 'T17410V', 'T06058Q', 'T09111Q', 'P92042', 'T08760N', 'T06249V', 'T04875H', 'T09170B', 'T00232O', 'T16712C', 'T08005L', 'P11850', 'T12422F', 'P96040', 'P93810', 'T11822N', 'T19035A', 'P30370', 'T05360P', 'T18522G', 'T04636U', 'T21414G', 'T14744C', 'T12699G', 'T06899X', 'T20641L', 'T16691O', 'T16979B', 'T18516I', 'T01119S', 'T12881C', 'T09690U', 'T15744G', 'T07953Q', 'T07976X', 'T00143O', 'P34050', 'T17509F', 'T11875A', 'T12547R', 'T12289S', 'T12251E', 'T11958C', 'T12397V', 'T21068I', 'T20699D', 'T00444Y', 'T18841S', 'T03471N', 'T09567S', 'P97470', 'T11993F', 'T11870V', 'T12140Y', 'P72080', 'T06401L', 'T09681T', 'T03609N', 'T20088I', 'P07991', 'T16905J', 'T05370R', 'T09081B', 'T01760L', 'T01200K', 'T18269M', 'T05242K', 'T18729T', 'T12984I', 'T03035X', 'T00209P', 'T13315H', 'T15398I', 'T11368M', 'T16420T', 'T16621A', 'T15379F', 'T18025U', 'T05703S', 'T14606T', 'T01747O', 'T20765W', 'T08163Y', 'T10654L', 'T13628V', 'RL0012L', 'T07658M', 'T00018K', 'P33160', 'T01708H', 'P93400', 'T19859G', 'T01983Y', 'T08527G', 'T10635I', 'T00867R', 'P16020', 'T11742O', 'T16701Z', 'T13810R', 'P21420', 'T04478Y', 'T15659K', 'T02270C', 'T07553E', 'T02593S', 'T19744W', 'T12262H', 'P81110', 'T11385N', 'T18460J', 'T15928M', 'T08459L', 'T11981B', 'P32430', 'T02212S', 'T00111G', 'T21500D', 'P26681', 'T18817S', 'T08738P', 'T11570M', 'P15631', 'P70270', 'T03383O', 'T17799D', 'T09601D', 'T07273Z', 'P30180', 'P80980', 'T09608K', 'T04506L', 'T14465Y', 'T16049U', 'T09988J', 'T08803H', 'P05241', 'T06662E', 'T04998R', 'T11093E', 'T17956Y', 'P07703', 'T15841G', 'T04593A', 'T12630L', 'T17409C', 'T03348L', 'T13393V', 'T00376D', 'T12429M', 'T03079J', 'T16749P', 'T10631E', 'T03387S', 'T18948C', 'P40250', 'P71250', 'T03748X', 'T02989I', 'T19142C', 'T09740N', 'T13291Q', 'T08620C', 'T06047N', 'T17873W', 'T20344F', 'T18790Y', 'T16047S', 'T11761R', 'T09050U', 'T07477J', 'T08537I', 'T00389I', 'P60770', 'T02839V', 'T14653A', 'T00049R', 'T12427K', 'T02067B', 'T03718R', 'T09788D', 'T12070B', 'T20001L', 'P91100', 'T17766U', 'T09541I', 'T18619O', 'T12036Z', 'T21495X', 'T01546H', 'T20901M', 'T19264L', 'T01872S', 'T09504D', 'P31000', 'T12808T', 'T09692W', 'T16036P', 'T21136D', 'T11641K', 'T20603F', 'P50960', 'P91590', 'P82915', 'T02121Q', 'P34220', 'T05557A', 'P30611', 'T21003R', 'P92170', 'T07340T', 'T08753O', 'T04241F', 'T00123K', 'P91310', 'T01025N', 'T15506U', 'P82780', 'T16401Q', 'T12864B', 'T11326C', 'T10844P', 'T12612J', 'T07849R', 'T04340H', 'T18374M', 'T02992D', 'T03602G', 'P30220', 'T12041W', 'T06097X', 'P25850', 'T10564K', 'T10154W', 'T15989Z', 'T01850M', 'P50860', 'NS0015O', 'P06370', 'T02978F', 'T03905S', 'T11905P', 'T11693W', 'T11512C', 'T09853V', 'T06264U', 'T14230H', 'T00090S', 'T17069C', 'T12769D', 'T09288O', 'T18259K', 'T08778X', 'T16226T', 'T05148N', 'T04496A', 'P34330', 'P25502', 'T19825W', 'T10840L', 'VA0017Q', 'T16958W', 'T21415H', 'T04915Y', 'T09756V', 'T03157G', 'T12626P', 'T09993G', 'T17867Y', 'T03686A', 'RD0003C', 'T10833M', 'T19169N', 'T13841Y', 'T16197F', 'T12133Z', 'P91370', 'T12681W', 'T21544P', 'T04851Z', 'P98060', 'T03868E', 'T08926R', 'RD0026Z', 'T05971K', 'T09243B', 'T20807P', 'T09610E', 'T12716Q', 'T15056P', 'T10128U', 'T15806D', 'T02771S', 'T10864T', 'T01194D', 'T00187A', 'T19881E', 'T02085D', 'T00161Q', 'T17187H', 'P40220', 'T09094G', 'T18106U', 'T07285D', 'T20197M', 'T10448H', 'T16493K', 'T09426G', 'T10121N', 'T16966W', 'T05175Q', 'T11477Q', 'T11482N', 'T11349J', 'T14504O', 'T14846H', 'T13976M', 'T11488T', 'T19970E', 'T08008O', 'T20508H', 'T09249H', 'T06863L', 'T08502X', 'T09963A', 'T10513Z', 'T06216M', 'T07981U', 'T15576I', 'T09818S', 'T05284U', 'T16882T', 'T19405G', 'T20271F', 'T15697Q', 'T10124Q', 'T10646L', 'T10845Q', 'T08409B', 'P08220', 'T16603Y', 'P82420', 'T19546S', 'T04843Z', 'T07049T', 'T03059F', 'P11270', 'T08841N', 'T17901J', 'T17645M', 'T04507M', 'P70200', 'T18484R', 'T05413L', 'T11644N', 'T00142N', 'T06926J', 'T12015U', 'T08530B', 'T18637Q', 'T15387F', 'T02637N', 'T06302J', 'T08194F', 'T02763S', 'T01495N', 'T19055E', 'RD0029C', 'T12520G', 'T08480I', 'T07717G', 'T09031R', 'T17491M', 'T17105P', 'T12723P', 'T00223N', 'P81350', 'T16159Z', 'T08865V', 'T04652U', 'T06187Y', 'T07359E', 'P94240', 'T08888C', 'P90631', 'T13984M', 'T04597E', 'T00569K', 'T19785F', 'T20758X', 'T08458K', 'T06406Q', 'T01209T', 'T06660C', 'T03631L', 'P21200', 'P13020', 'T04304D', 'P80860', 'T11710G', 'T07680K', 'T05147M', 'T20906R', 'P50350', 'T06281V', 'T16325V', 'T10916O', 'T16434Z', 'T09433F', 'T10617G', 'T02625J', 'T16977Z', 'P08382', 'T05113C', 'T09517I', 'T01932N', 'T17732K', 'T10179F', 'T02537K', 'T11473M', 'T19233E', 'T02538L', 'P50940', 'T17281E', 'P83610', 'T21287R', 'T07827L', 'T17358I', 'P95720', 'T14790I', 'T19406H', 'T13850Z', 'T01663L', 'T20696A', 'T02429H', 'T19113X', 'T00316R', 'T15255U', 'T00275Z', 'P82842', 'T20915S', 'T12363L', 'T09735Q', 'T02569S', 'T08344B', 'T05198X', 'T12583V', 'T15824F', 'T09138B', 'T06676K', 'T12144C', 'T00172T', 'T11995H', 'T01538H', 'T10508C', 'T02582P', 'T04614O', 'T05792J', 'T04484W', 'T01987C', 'T06923G', 'T18254F', 'P40140', 'T07136R', 'T10957X', 'RL0044R', 'P71480', 'T17017Q', 'P60160', 'T10182A', 'T09895F', 'T18894F', 'T16661I', 'T11519J', 'T13468X', 'T07225R', 'P26860', 'T17190C', 'T17600Z', 'T08964X', 'P07911', 'T21491T', 'P07303', 'T20936X', 'T02045V', 'T15416T', 'T14522Q', 'T02014O', 'T08316X', 'T07257Z', 'T09103Q', 'T13072H', 'T03513G', 'T12834V', 'T06366Z', 'T00378F', 'P15690', 'T11327D', 'P81440', 'T02106R', 'T02472K', 'T00641B', 'T01190Z', 'T04933A', 'T18186K', 'T02342B', 'T21383Q', 'P26920', 'T16064T', 'T21294Q', 'T17163Z', 'T20911O', 'T12758A', 'P15660', 'T21014U', 'P41310', 'T19123Z', 'T05367W', 'T19562S', 'T08563K', 'T03494U', 'T11749V', 'T06575G', 'T10527F', 'T00229T', 'P95780', 'T10418B', 'T10205Q', 'T02664Q', 'T00876S', 'T07557I', 'T15435W', 'P15680', 'T07987A', 'T16646J', 'T21323E', 'T18750Q', 'T06680G', 'P72480', 'T20804M', 'T05107E', 'T10273C', 'T19071E', 'T02786Z', 'T10847S', 'T02274G', 'T07631B', 'T01045R', 'T04536R', 'T03703K', 'P27750', 'T01210M', 'T08451D', 'P90342', 'T02676U', 'T00446A', 'P05340', 'T07700X', 'RD0102X', 'T13859I', 'T10921L', 'T02714J', 'P16762', 'T08267F', 'T02997I', 'T21384R', 'T15859Q', 'T05956L', 'RD0099U', 'T16537F', 'T09691V', 'T05068O', 'T19849E', 'T18510C', 'P93922', 'T05251L', 'T10354C', 'T19839C', 'T21471P', 'P20740', 'T20473N', 'T20600C', 'T20109W', 'T09821N', 'P26700', 'P60170', 'P06090', 'T02609J', 'T05109G', 'T20015R', 'P96701', 'T02164B', 'T18715N', 'T16102I', 'T19120W', 'T19594A', 'T14426R', 'T06668K', 'P30150', 'T08009P', 'T16531Z', 'T08042Q', 'T17697Y', 'P25320', 'T13307H', 'T19961D', 'T09158F', 'T01382F', 'T01636I', 'T10572K', 'T20854W', 'T01824K', 'P93780', 'T07308T', 'T12596A', 'T08526F', 'T01171W', 'T09164D', 'T04727W', 'P31660', 'T08305U', 'P40880', 'T06313M', 'T13831W', 'T05075N', 'T17375J', 'T16786U', 'NS0001A', 'T09001L', 'T06137O', 'T11687Y', 'T16716G', 'T10382G', 'P27312', 'T20707M', 'P81690', 'T01873T', 'T02446I', 'T20528L', 'T11587V', 'T09986H', 'T13137H', 'P60602', 'T17415A', 'T05346R', 'T05869N', 'T07264Y', 'T03375O', 'T04212A', 'T13879M', 'T01519E', 'T13954G', 'T16266B', 'LRD0026', 'P81161', 'T15825G', 'T15386E', 'T08747Q', 'T18831Q', 'T00582H', 'T21093J', 'T12256J', 'P30890', 'T11992E', 'T08114P', 'T18268L', 'T10194E', 'P50770', 'T04071F', 'T18868D', 'T21447P', 'T05545W', 'P27920', 'T14851E', 'T20799G', 'T16010F', 'T01690O', 'T12817U', 'T10658P', 'T14457Y', 'T01731G', 'T18751R', 'T10091Y', 'T07332T', 'T12327H', 'P34010', 'T19960C', 'T02031P', 'T10110K', 'T20748V', 'T14359X', 'T04335K', 'T12218D', 'T18812N', 'T08988F', 'P12650', 'T16136S', 'T19347N', 'T05270O', 'T12816T', 'P95383', 'RD0017Q', 'T08153W', 'T01974X', 'T21081F', 'T15531V', 'T02323Y', 'T21316F', 'T11961X', 'T09736R', 'T19286R', 'P20700', 'P51180', 'T09962Z', 'P34280', 'P71450', 'T03700H', 'T01255Z', 'P91300', 'P27670', 'T14249S', 'T20491P', 'P97991', 'T00668M', 'P28553', 'T10659Q', 'T01992Z', 'T01157Y', 'T10166A', 'P30630', 'T07459H', 'T07707E', 'T14469C', 'P05010', 'T04352L', 'T00562D', 'T04736X', 'T20784Z', 'T00915I', 'T11156C', 'T08591O', 'T20822O', 'T09576T', 'T17473K', 'T05814Y', 'T11165D', 'T02438I', 'T07748N', 'P94090', 'T16364C', 'T00131K', 'T10392I', 'T20684W', 'T16167Z', 'T04285R', 'T08939W', 'T09554N', 'T16590K', 'RL0004D', 'T08395M', 'T04189S', 'T01709I', 'T19339N', 'P80500', 'T19798K', 'T06765K', 'T04190L', 'T09760R', 'T11140U', 'T20126X', 'P80910', 'T07703A', 'T05154L', 'LRD0011', 'T00250Q', 'T14882L', 'T19578A', 'T00975U', 'T10419C', 'P35044', 'P81500', 'P92663', 'T21528P', 'T08685T', 'T11171B', 'T06649H', 'T05030A', 'T09477R', 'P80110', 'T05467Z', 'T00157U', 'T17261A', 'T07986Z', 'P81391', 'T07904H', 'P71541', 'T15679O', 'T20553M', 'T16630B', 'T03429L', 'T20313Y', 'T17767V', 'T01217T', 'P97491', 'T03661R', 'T02016Q', 'P25012', 'T01776T', 'T18828V', 'T08640G', 'T11083C', 'T09035V', 'T00789U', 'T07590J', 'T16187D', 'T02238C', 'T06330N', 'P28050', 'T11859A', 'T04719W', 'P25350', 'T01942P', 'T20368N', 'T02906P', 'T14879Q', 'T12576W', 'T05168R', 'T20130T', 'P80330', 'T06087V', 'T17850P', 'T04660U', 'P31470', 'T01790R', 'P16280', 'T19303B', 'T06046M', 'T01397M', 'T15190U', 'P15320', 'T08677T', 'T10612B', 'T10004J', 'P13150', 'T07843L', 'T10992A', 'T10171X', 'T09374L', 'P12790', 'T09084E', 'T09991E', 'T08311S', 'T19474T', 'T19107Z', 'T11081A', 'T19451M', 'T07970R', 'T09482O', 'T18799H', 'T01022K', 'T17602B', 'T19400B', 'T07725G', 'T02159E', 'T09024S', 'T03275L', 'T21185M', 'T10269G', 'P40420', 'T15715B', 'T06919K', 'P92271', 'T09268K', 'T03441H', 'T01801D', 'T14884N', 'T05205F', 'P81830', 'T05963K', 'T12132Y', 'T18985H', 'T08211P', 'T10005K', 'T04405H', 'T08168D', 'T20034U', 'T00678O', 'T15711X', 'T17929V', 'T04932Z', 'T03937A', 'T03319G', 'T16462D', 'T19205A', 'P30260', 'T01703C', 'T02331Y', 'T09732N', 'P30050', 'T08658Q', 'T03504F', 'P95161', 'T02112P', 'T21392R', 'T19181J', 'T19812R', 'T02187I', 'T13285S', 'T03188N', 'T19895K', 'P41730', 'T11835S', 'T20527K', 'T01053R', 'T13903V', 'T00486I', 'T15048P', 'T15290X', 'T01712D', 'T15879U', 'P72661', 'T18697C', 'P11870', 'T20455L', 'P71960', 'T09328F', 'P92380', 'P41110', 'T02511A', 'T06447Z', 'T17107R', 'T19690Z', 'T01509C', 'T11142W', 'T07495L', 'P98020', 'T07914J', 'P50540', 'T04474U', 'T07131M', 'T21075H', 'T16067W', 'T07008K', 'T16338A', 'T03755W', 'T01432Y', 'T19689G', 'T11645O', 'T06053L', 'T14682F', 'T00210I', 'T04552R', 'T10672N', 'P32950', 'T17350A', 'T17384K', 'T10414X', 'T08533E', 'T02551I', 'T19427M', 'T06336T', 'T02110N', 'T01305S', 'T12594Y', 'T08696W', 'P21450', 'T07995A', 'T19489A', 'T07475H', 'T10656N', 'T14181P', 'T00760H', 'T12224B', 'T09781W', 'T01740H', 'T12706O', 'T02477P', 'T20959E', 'T00993W', 'T18760S', 'T06111E', 'T17702E', 'T07793S', 'T08873V', 'T09339I', 'T12851W', 'T04524N', 'T04231D', 'P32020', 'T10203O', 'T12068H', 'T04224E', 'P28520', 'T15536A', 'P12191', 'T08308X', 'T17472J', 'T04143E', 'P06610', 'T20501A', 'T20290I', 'T12534M', 'P31140', 'T03019X', 'T02344D', 'T13399B', 'T12926Y', 'T07670I', 'T18044X', 'P92422', 'T21285P', 'T20342D', 'RD0124T', 'P90501', 'T09239F', 'T16619G', 'T02256E', 'T17830L', 'T20353G', 'T12878H', 'P60230', 'T00774N', 'RL0015O', 'T16098D', 'T15000Z', 'T02956Z', 'T20299R', 'T04644U', 'P12520', 'T11887E', 'T21061B', 'P05030', 'RL0041O', 'P07891', 'P15510', 'T02020M', 'P83270', 'P83790', 'T20773W', 'P90090', 'P40500', 'T16024L', 'P93200', 'T04570T', 'T04345M', 'T02150V', 'T00490E', 'P81740', 'P70760', 'T19878J', 'T17962W', 'T07568L', 'T06283X', 'T00108L', 'T07736J', 'P30240', 'T03928Z', 'P41020', 'T06942J', 'T08379M', 'T10993B', 'T13818Z', 'T21120V', 'T16784S', 'T07035N', 'T04835Z', 'T13776G', 'P41240', 'T06128N', 'T13287U', 'T10288J', 'T02197K', 'T08662M', 'T17314W', 'T05023B', 'T12764Y', 'T15567H', 'T20251B', 'T11586U', 'T03643P', 'T21053B', 'P60390', 'T05225J', 'T16134Q', 'T21560P', 'T12461M', 'T12316E', 'T00175W', 'T11934U', 'T04902T', 'T04678E', 'T05553W', 'T21231B', 'T02258G', 'T04017Z', 'T11677W', 'T04966J', 'T03316D', 'T10618H', 'T02620E', 'T00236S', 'P91670', 'T17622F', 'T17787Z', 'P33602', 'P33910', 'P28500', 'T14863I', 'T09655R', 'T18901N', 'T20848Y', 'T00107K', 'T06134L', 'T21355M', 'T02914P', 'T19080F', 'T21077J', 'T18973D', 'T04316H', 'T19543P', 'P40540', 'T07246W', 'T05295X', 'T10181Z', 'T03784B', 'P15050', 'T03238G', 'T08806K', 'T05853F', 'T18727R', 'T06161O', 'T00952

In [186]:
y.GEOM_WKT.value_counts()

MULTILINESTRING ((430229.788593716 4586585.19905775,430181.876584091 4586593.70443592))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  25
MULTILINESTRING ((428478.106811811 4585915.25031926,428490.060594814 4585884.1301785))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   25

In [187]:
y = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\capacidad acustica\ATMOSFERA_MES_SUPRAMUN_2018.csv")

In [188]:
y.SHAPE.value_counts().sum()

45853

In [189]:
y

,FID,SHAPE,IDTRAM_AGL,IDTRAM,IDAGLO,CODI_INE,TVLDIA,TVLVES,TVLNIT,TVLDEN,...,TOTVES,TOTNIT,TOTDEN,VLDIA,VLVES,VLNIT,SVLDIA,SVLVES,SVLNIT,OBJECTID
0,ATMOSFERA_MES_SUPRAMUN_2018.134902,"MULTILINESTRING ((418934.6899 4602170.0496, 41...",1717,27124,VOC2,08279,58,58,49,59,...,58,49,59,65,65,55,0,0,0,134902
1,ATMOSFERA_MES_SUPRAMUN_2018.109272,"MULTILINESTRING ((428084.3613 4582246.8167, 42...",17112,T18520E,BCN1,08019,62,59,54,63,...,59,54,63,0,0,0,0,0,0,109272
2,ATMOSFERA_MES_SUPRAMUN_2018.102492,"MULTILINESTRING ((432690.9162 4586956.886, 432...",10332,T06162P,BCN1,08019,68,66,61,70,...,66,61,70,0,0,0,0,0,0,102492
3,ATMOSFERA_MES_SUPRAMUN_2018.137490,"MULTILINESTRING ((417967.7731 4603161.4321, 41...",4305,29712,VOC2,08279,59,59,50,60,...,59,50,60,65,65,55,0,0,0,137490
4,ATMOSFERA_MES_SUPRAMUN_2018.95114,"MULTILINESTRING ((430415.0153 4581110.6482, 43...",2954,T01133Q,BCN1,08019,56,54,49,58,...,54,49,58,0,0,0,0,0,0,95114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45848,ATMOSFERA_MES_SUPRAMUN_2018.124248,"MULTILINESTRING ((354437.3837 4553283.6379, 35...",1086,1182,TAR,43148,58,58,55,62,...,58,55,62,65,65,55,0,0,0,124248
45849,ATMOSFERA_MES_SUPRAMUN_2018.99475,"MULTILINESTRING ((427626.996 4583797.712, 4276...",7315,P33000,BCN1,08019,42,40,35,44,...,40,35,44,0,0,0,0,0,0,99475
45850,ATMOSFERA_MES_SUPRAMUN_2018.109617,"MULTILINESTRING ((432364.9082 4582679.8029, 43...",17457,T10145V,BCN1,08019,67,65,60,68,...,65,60,68,0,0,0,0,0,0,109617
45851,ATMOSFERA_MES_SUPRAMUN_2018.117236,"MULTILINESTRING ((422556.9647 4579922.0494, 42...",2858,3905,BLLI,08217,57,57,51,59,...,57,51,59,65,65,55,0,0,0,117236
45852,ATMOSFERA_MES_SUPRAMUN_2018.129286,"MULTILINESTRING ((423739.0246 4602251.3792, 42...",1915,1918,VOCI,08187,59,59,50,60,...,59,50,60,65,65,55,0,0,0,129286

### Green points

delete non necesary.

In [110]:
y = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\puntos_ecologicos.csv")

In [111]:
y = y.drop(columns=["register_id", "institution_id", "institution_name", "addresses_roadtype_id", "addresses_roadtype_name", "values_description", "secondary_filters_fullpath", "secondary_filters_tree", 
                "secondary_filters_asia_id", "geo_epgs_25831_x", "geo_epgs_25831_y", "addresses_road_id", "addresses_end_street_number", "addresses_neighborhood_id", "addresses_neighborhood_id",
                "values_id", "values_attribute_id", "values_category", "values_attribute_name", "values_value", "values_outstanding", "secondary_filters_id", 
                "addresses_town", "addresses_main_address", "addresses_type"])

In [117]:
y["secondary_filters_name"].value_counts()

Punts verds mòbils            97
Punts verds de barri          27
Horts urbans                  15
Punts verds de zona            7
Punts verds col·laboradors     1
Name: secondary_filters_name, dtype: int64

In [113]:
y = y.drop(y[y["secondary_filters_name"] == "Punts de recollida d'arbres de Nadal"].index)

In [114]:
y = y.drop(y[y["secondary_filters_name"] == "Contenidors de sal"].index)

In [115]:
y = y.drop(y[y["secondary_filters_name"] == "Punts de roba amiga"].index)

In [116]:
y = y.drop(y[y["secondary_filters_name"] == "Punts de recollida d'arbres de Nadal"].index)

In [88]:
n = y["secondary_filters_name"] == "Punts verds col·laboradors"
y[n]

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
437,﻿75990029216,Punt Verd de Barri Col·laborador - Recuperació...,NaN,NaN,1996-09-17T00:00:00+02:00,2023-02-28T13:41:18.437140+01:00,NaN,NaN,152202,Carrer de les Guilleries,...,NaN,65731068,Punts verds col·laboradors,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000000,429487.034971,4.583912e+06,41.40366,2.15641

### Huertos urbanos

In [119]:
huerto = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\huertos.csv")
huerto

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿99400400469,Hort Urbà de Can Peguera,NaN,NaN,2015-11-04T12:11:42+01:00,2022-09-23T12:49:54.202656+02:00,NaN,NaN,57100,C Camós,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,430170.170636,4.587276e+06,41.434021,2.164193
1,﻿98180122541,Hort Urbà Masia Can Mestres,NaN,NaN,1998-06-29T00:00:00+02:00,2022-09-23T12:41:11.292400+02:00,NaN,NaN,58634,Camí Can Clos,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,428498.372611,4.579043e+06,41.359715,2.145157
2,﻿1156115521,Hort Urbà Masia Can Soler,NaN,NaN,2001-06-05T00:00:00+02:00,2022-09-23T12:49:01.767216+02:00,NaN,NaN,148409,Ctra Sant Cugat,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,427362.046099,4.586306e+06,41.425029,2.130702
3,﻿99400186934,Hort Urbà,9.940041e+10,La Casa de l'Aigua,2007-07-06T08:51:21+02:00,2022-09-23T12:51:00.902439+02:00,NaN,NaN,139907,C Garbí,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,432182.013692,4.589361e+06,41.452965,2.188037
4,﻿99400100015,Hort Urbà Parc de la Trinitat,NaN,NaN,2004-11-23T14:00:35+01:00,2022-09-23T12:52:43.616445+02:00,NaN,NaN,314100,Pg Santa Coloma,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,432814.485640,4.588944e+06,41.449269,2.195655
5,﻿99400183714,Hort Urbà de Sant Pau del Camp,NaN,NaN,2007-05-21T13:46:45+02:00,2022-09-23T12:27:35.260523+02:00,NaN,NaN,500,C Abat Safont,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,430530.332476,4.580808e+06,41.375794,2.169246
6,﻿99400400467,Hort Urbà Baró de Viver,NaN,NaN,2015-11-04T11:24:12+01:00,2022-09-23T12:51:57.064996+02:00,NaN,NaN,314100,Pg Santa Coloma,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,433080.424051,4.588992e+06,41.449723,2.198833
7,﻿99400100007,Hort Urbà de l'Avi,NaN,NaN,2004-11-23T12:43:51+01:00,2022-09-23T12:47:45.631318+02:00,NaN,NaN,340905,C Torrent del Remei,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,428816.369204,4.585246e+06,41.415613,2.148230
8,﻿99400100012,Hort Urbà de Turull,NaN,NaN,2004-11-23T13:25:29+01:00,2022-09-23T12:46:40.315876+02:00,NaN,NaN,348350,Ptge Turull,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,428777.193634,4.585011e+06,41.413495,2.147789
9,﻿99400100016,Hort Urbà Masia Can Cadena,NaN,NaN,2004-11-23T14:24:00+01:00,2022-09-23T12:53:39.525173+02:00,NaN,NaN,208205,C Menorca,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,432996.621503,4.585782e+06,41.420806,2.198186
10,﻿99400170336,Hort Urbà Torre Melina,NaN,NaN,2006-10-20T14:18:50+02:00,2022-09-23T12:43:04.088082+02:00,NaN,NaN,339815,Camí Torre Melina,...,Informació,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,425696.028441,4.581010e+06,41.377183,2.111416
11,﻿99400200051,Hort Urbà de Pedralbes,NaN,NaN,2008-02-12T09:44:25+01:00,2022-09-23T12:42:00.469725+02:00,NaN,NaN,72704,C Castellet,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,425728.947701,4.582914e+06,41.394332,2.111577
12,﻿99400363859,Hort Urbà Can Pujades,NaN,NaN,2014-11-20T12:01:02+01:00,2022-09-23T12:44:02.506871+02:00,NaN,NaN,700168,Camí Múrgola,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,424660.180575,4.585200e+06,41.414821,2.098509
13,﻿99400180128,Hort Urbà Sagrada Família,NaN,NaN,2007-03-30T08:54:17+02:00,2022-09-23T12:29:23.036079+02:00,NaN,NaN,238400,C Padilla,...,NaN,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,431511.282331,4.583783e+06,41.402677,2.180639
14,﻿99400186258,Hort Urbà Collserola,NaN,NaN,2007-06-26T08:38:52+02:00,2022-09-23T12:45:40.467359+02:00,NaN,NaN,66803,C Carles Pirozzini,...,Informació,65731076,Horts urbans,Planol BCN >> Medi ambient >> Medi ambient >> ...,651,65103012000008,427665.696358,4.585340e+06,41.416357,2.134451

In [120]:
huerto = huerto.drop(columns=["register_id", "institution_id", "institution_name", "addresses_roadtype_id", "addresses_roadtype_name", "values_description", "secondary_filters_fullpath", "secondary_filters_tree", 
                "secondary_filters_asia_id", "geo_epgs_25831_x", "geo_epgs_25831_y", "addresses_road_id", "addresses_end_street_number", "addresses_neighborhood_id", "addresses_neighborhood_id",
                "values_id", "values_attribute_id", "values_category", "values_attribute_name", "values_value", "values_outstanding", "secondary_filters_id", 
                "addresses_town", "addresses_main_address", "addresses_type"])

### Jardin interiors.

In [122]:
interior = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\jardin_interiors.csv")

In [125]:
interior = interior.drop(columns=["register_id", "institution_id", "institution_name", "addresses_roadtype_id", "addresses_roadtype_name", "values_description", 
                "geo_epgs_25831_x", "geo_epgs_25831_y", "addresses_road_id", "addresses_end_street_number", "addresses_neighborhood_id", "addresses_neighborhood_id",
                "values_id", "values_attribute_id", "values_category", "values_attribute_name", "values_value", "values_outstanding", 
                "addresses_town", "addresses_main_address", "addresses_type"])

Change names of columns

In [127]:
interior.shape

(49, 11)

### puntos ecologicos.

mateix del aoltra data frame

In [130]:
punts = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\puntos_ecologicos.csv")

### refugis.

In [132]:
refugi = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\refugi.csv")

refiguios tipo escuelas, parques, lugares tipo asilos bibliotecas, de espacios publicos.

In [235]:
refugi

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_attribute_id,values_category,values_attribute_name,values_value,values_outstanding,values_description,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿92086005760,Biblioteca Canyelles,NaN,NaN,1986-05-21T00:00:00+02:00,2023-02-16T09:52:36.412303+01:00,NaN,NaN,153158,Ronda de la Guineueta Vella,...,100002.0,Informació d'interès,E-mail,b.barcelona.c@diba.cat,True,NaN,430192.917191,4.588362e+06,41.443804,2.164340
1,﻿92168165957,Escola Ramon Casas,NaN,NaN,1989-12-04T00:00:00+01:00,2023-02-16T09:52:27.242319+01:00,NaN,NaN,700714,Carrer del Platí,...,100002.0,Informació d'interès,E-mail,a8002976@xtec.cat,True,NaN,427595.967414,4.578935e+06,41.358670,2.134383
2,﻿92086011165,Casal de Gent Gran Parc Sandaru,NaN,NaN,1985-05-21T00:00:00+02:00,2023-02-16T09:52:33.285232+01:00,NaN,NaN,50803,C Buenaventura Muñoz,...,100002.0,Informació d'interès,E-mail,casalgg.parcsandaru@bcn.cat,True,NaN,431844.899337,4.582567e+06,41.391746,2.184767
3,﻿99085102712,Parc de Diagonal Mar,NaN,NaN,1999-03-26T00:00:00+01:00,2023-02-16T09:52:23.104422+01:00,NaN,NaN,186703,Carrer de Llull,...,100003.0,Informació d'interès,Web,https://link.bcn.cat/cPdDM,True,NaN,434157.960807,4.584404e+06,41.408490,2.212232
4,﻿92168175469,Centre Esportiu Municipal Perill,NaN,NaN,1989-10-26T00:00:00+01:00,2023-02-16T09:52:26.550092+01:00,NaN,NaN,251102,C Perill,...,100002.0,Informació d'interès,E-mail,perill@eurofitness.com,True,NaN,429909.760963,4.583438e+06,41.399432,2.161521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,﻿92171135342,Centre Esportiu Municipal Nova Icària,NaN,NaN,1992-06-19T00:00:00+02:00,2023-02-16T09:52:26.299338+01:00,NaN,NaN,62609,Av Icària,...,100002.0,Informació d'interès,E-mail,recepcio@novaicaria.com,True,NaN,432953.634548,4.582628e+06,41.392394,2.198021
197,﻿99400342694,Biblioteca Sant Gervasi - Joan Maragall,NaN,NaN,2014-05-15T15:03:15+02:00,2023-02-16T09:52:18.358981+01:00,NaN,NaN,302203,Carrer de Sant Gervasi de Cassoles,...,100002.0,Informació d'interès,E-mail,b.barcelona.jmg@diba.cat,True,NaN,427783.024467,4.584184e+06,41.405955,2.135993
198,﻿99400694393,Casal de Gent Gran Can Novell,NaN,NaN,2022-06-28T12:08:56.451907+02:00,2023-02-16T09:52:33.671067+01:00,NaN,NaN,52605,Carrer de Caballero,...,100002.0,Informació d'interès,E-mail,gentgranlescorts@bcn.cat,True,NaN,427582.425000,4.581553e+06,41.382243,2.133908
199,﻿95025093613,Casal de Gent Gran La Capa,NaN,NaN,1995-01-25T00:00:00+01:00,2023-02-16T09:52:25.111934+01:00,NaN,NaN,12600,Carrer dels Alts Forns,...,100002.0,Informació d'interès,E-mail,lamarina@esport3.org,True,NaN,428295.253581,4.579072e+06,41.359964,2.142726
200,﻿99400637478,Casal de Barri Transformadors,NaN,NaN,2019-09-23T14:07:17+02:00,2023-02-16T09:52:34.014638+01:00,NaN,NaN,28305,C Ausiàs Marc,...,100002.0,Informació d'interès,E-mail,casaltransformadors@gmail.com,True,NaN,431331.536286,4.582762e+06,41.393462,2.178605

In [136]:
# eliminar variables y telefons
refugi["values_category"].value_counts()

Informació d'interès    193
Variables                 2
Telèfons                  2
Name: values_category, dtype: int64

In [135]:
refugi.columns

Index(['register_id', 'name', 'institution_id', 'institution_name', 'created',
       'modified', 'addresses_roadtype_id', 'addresses_roadtype_name',
       'addresses_road_id', 'addresses_road_name',
       'addresses_start_street_number', 'addresses_end_street_number',
       'addresses_neighborhood_id', 'addresses_neighborhood_name',
       'addresses_district_id', 'addresses_district_name',
       'addresses_zip_code', 'addresses_town', 'addresses_main_address',
       'addresses_type', 'values_id', 'values_attribute_id', 'values_category',
       'values_attribute_name', 'values_value', 'values_outstanding',
       'values_description', 'geo_epgs_25831_x', 'geo_epgs_25831_y',
       'geo_epgs_4326_x', 'geo_epgs_4326_y'],
      dtype='object')

### Arbolado.

In [216]:
viari = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\arbrat\OD_Arbrat_Viari_BCN.csv")

In [217]:
viari.columns

Index(['codi', 'x_etrs89', 'y_etrs89', 'latitud', 'longitud', 'tipus_element',
       'espai_verd', 'adreca', 'cat_especie_id', 'nom_cientific',
       'nom_castella', 'nom_catala', 'categoria_arbrat', 'data_plantacio',
       'tipus_aigua', 'tipus_reg', 'geom', 'catalogacio', 'codi_barri',
       'nom_barri', 'codi_districte', 'nom_districte'],
      dtype='object')

In [218]:
viari = viari.drop(columns=["codi", "x_etrs89", "y_etrs89", "tipus_element", "cat_especie_id", "tipus_aigua", "tipus_reg", "nom_catala", "geom", "catalogacio"])

In [219]:
viari

,latitud,longitud,espai_verd,adreca,nom_cientific,nom_castella,categoria_arbrat,data_plantacio,codi_barri,nom_barri,codi_districte,nom_districte
0,41.437287,2.165353,"Central de Nou Barris, Parc","Pg Fabra i Puig, 450",Fraxinus angustifolia 'Raywood',-,PRIMERA,2022-02-15,48.0,LA GUINEUETA,8,NOU BARRIS
1,41.437335,2.165436,"Central de Nou Barris, Parc","Pg Fabra i Puig, 450",Fraxinus angustifolia 'Raywood',-,PRIMERA,2022-02-15,48.0,LA GUINEUETA,8,NOU BARRIS
2,41.437769,2.162530,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",Platanus x hispanica,Plátano,SEGONA,NaN,43.0,HORTA,7,HORTA - GUINARDÓ
3,41.437788,2.162501,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",Platanus x hispanica,Plátano,SEGONA,NaN,43.0,HORTA,7,HORTA - GUINARDÓ
4,41.437810,2.162471,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",Platanus x hispanica,Plátano,SEGONA,NaN,43.0,HORTA,7,HORTA - GUINARDÓ
...,...,...,...,...,...,...,...,...,...,...,...,...
153827,41.419993,2.190518,NaN,"C\ Josep Estivill, 65",Melia azedarach,Melia; cinamomo,PRIMERA,2023-02-04,61.0,LA SAGRERA,9,SANT ANDREU
153828,41.420038,2.190579,NaN,"Ptge Bofarull, 2",Melia azedarach,Melia; cinamomo,PRIMERA,2023-02-04,61.0,LA SAGRERA,9,SANT ANDREU
153829,41.419800,2.191147,NaN,"C\ Gran de la Sagrera, 12",Melia azedarach,Melia; cinamomo,PRIMERA,2023-02-04,61.0,LA SAGRERA,9,SANT ANDREU
153830,41.419979,2.191137,NaN,"C\ Gran de la Sagrera, 12",Melia azedarach,Melia; cinamomo,PRIMERA,2023-02-04,61.0,LA SAGRERA,9,SANT ANDREU
153831,41.419716,2.191138,"Hondures, c. - Sagrera, c. - Josep Estivill, c.","C\ Gran de la Sagrera, 49",Celtis australis,Almez,SEGONA,NaN,61.0,LA SAGRERA,9,SANT ANDREU

In [225]:
viari.shape

(153832, 12)

### arbrat parcs

located in the squares, flower beds, gazebos or small garden spaces

In [220]:
parcs = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\arbrat\OD_Arbrat_Parcs_BCN.csv")

In [222]:
parcs = parcs.drop(columns=["codi", "x_etrs89", "y_etrs89", "tipus_element", "cat_especie_id", "tipus_aigua", "tipus_reg", "nom_catala", "geom", "catalogacio"])

KeyError: "['codi', 'x_etrs89', 'y_etrs89', 'tipus_element', 'cat_especie_id', 'tipus_aigua', 'tipus_reg', 'nom_catala', 'geom', 'catalogacio'] not found in axis"

In [224]:
parcs.shape

(35922, 12)

### Arbrat Zona

In [227]:
zona = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\arbrat\OD_Arbrat_Zona_BCN.csv")

In [231]:
zona = zona.drop(columns=["codi", "x_etrs89", "y_etrs89", "tipus_element", "cat_especie_id", "tipus_aigua", "tipus_reg", "nom_catala", "geom", "catalogacio"])

In [239]:
zona.data_plantacio.isna().sum()

40345

In [229]:
zona.shape

(43392, 22)