# Environment
## Ayuntamiento de Barcelona

In [212]:
import plotly.express as px
import geopandas as gpd
import shapely.geometry
import numpy as np
import wget
import fiona
import folium

In [218]:
import pandas as pd
import plotly.graph_objects as go

In [330]:
import src.ecology as eco
import src.equipamiento as eq
import importlib
importlib.reload(eco)

### Calidad de aire.

In [172]:
# df de estaciones.
aire = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\\2022_qualitat_aire_estacions.csv")

In [173]:
distr = eco.limpia_estacions_aire(aire)

In [174]:
# df de los contaminantes y su id.
contami = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\contaminants.csv")

In [175]:
contami = eco.limpia_contaminants (contami)

sacar el mean por dia, evaluar el tipo de contaminante por el codigo= buscarlo en el el df de los contaminantes
conectar el data frame con el de arriba el completo para aberiguar la calidad por barrio con el codigo de la estacio. 
if estacio = entonces...

In [176]:
marzo_2023 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\Qualitat_Aire_Detall.csv")

In [177]:
marzo_2023 = eco.aire_monthly (marzo_2023, contami, distr)

In [178]:
# Febrero 2023
feb_2023 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2023_02_Febrer_qualitat_aire_BCN.csv")

In [179]:
feb_2023 = eco.aire_monthly (feb_2023, contami, distr)

In [180]:
# Enero 2023
ene_2023 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2023_01_Gener_qualitat_aire_BCN.csv")

In [181]:
ene_2023 = eco.aire_monthly (ene_2023, contami, distr)

In [182]:
# Dic 2022
dic_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_12_Desembre_qualitat_aire_BCN.csv")

In [183]:
dic_2022 = eco.aire_monthly (dic_2022, contami, distr)

In [185]:
# Nov 2022
nov_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_11_Novembre_qualitat_aire_BCN.csv")

In [186]:
nov_2022 = eco.aire_monthly (nov_2022, contami, distr)

In [187]:
# Octubre 2023
oct_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_10_Octubre_qualitat_aire_BCN.csv")

In [188]:
oct_2022 = eco.aire_monthly (oct_2022, contami, distr)

In [189]:
# septiembre 2022
sep_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_09_Setembre_qualitat_aire_BCN.csv")

In [190]:
sep_2022 = eco.aire_monthly (sep_2022, contami, distr)

In [191]:
# Agosto 2022
ago_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_08_Agost_qualitat_aire_BCN.csv")

In [192]:
ago_2022 = eco.aire_monthly (ago_2022, contami, distr)

In [193]:
# Jul 2022
jul_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_07_Juliol_qualitat_aire_BCN.csv")

In [194]:
jul_2022 = eco.aire_monthly (jul_2022, contami, distr)

In [195]:
# Junio 2022
jun_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_06_Juny_qualitat_aire_BCN.csv")

In [196]:
jun_2022 = eco.aire_monthly (jun_2022, contami, distr)

In [197]:
# Mayo 2022
may_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_05_Maig_qualitat_aire_BCN.csv")

In [198]:
may_2022 = eco.aire_monthly (may_2022, contami, distr)

In [199]:
# Abril 2022
abr_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_04_Abril_qualitat_aire_BCN.csv")

In [200]:
abr_2022 = eco.aire_monthly (abr_2022, contami, distr)

In [220]:
# Marzo 2022
mar_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_03_Marc_qualitat_aire_BCN.csv")

In [222]:
mar_2022 = eco.aire_monthly (mar_2022, contami, distr)

KeyError: "['PROVINCIA', 'CODI_PROVINCIA', 'CODI_MUNICIPI', 'MUNICIPI'] not found in axis"

### capacidad acustica

###### De 55 a 75 dB

###### Es un nivel de ruido considerable. Por ejemplo, un aspirador genera 65 dB. Una calle con mucho tráfico alcanza los 75 dB. El despertador o la televisión a un volumen elevado, pueden llegar a los 75 dB, igual que una lavadora, el teléfono móvil o una batidora.

###### De 75 dB a 100 dB

###### Es un nivel alto de ruido, la sensación es molesta. Por ejemplo, en un atasco hay 90 dB de ruido. También el que suele emitir una sirena de policía.

TOTAL_D        Ruido total en periodo dia
FFCC_E         Ruido de ejes ferroviarios y tranvía en período tarde
PATIS_D        Ruido en patios interiores en período día
OCI_N          Ruido de ocio y aglomeración de personas en período noche
VIANANTS_E     Ruido en calles peatonales en período tarde
VIANANTS_D     Ruido en calles peatonales en período día
INDUST_DEN     Ruido de industria en período Lden
INDUST_N       Ruido de industria en período noche
INDUST_E       Ruido de industria en período tarde
INDUST_D       Ruido de industria en período día
FFCC_DEN       Ruido de ejes ferroviarios y tranvía en período Lden
FFCC_N         Ruido de ejes ferroviarios y tranvía en período noche 
FFCC_D         Ruido de ejes ferroviarios y tranvía en período día
TOTAL_E        Ruido total en periodo tarde
GI_TR_DEN      Ruido de grandes infraestructuras viarias en período Lden 
GI_TR_N        Ruido de grandes infraestructuras viarias en período noche
GI_TR_E        Ruido de grandes infraestructuras viarias en período tarde
GI_TR_D        Ruido de grandes infraestructuras viarias en período día
TRANSIT_DEN    Ruido de tráfico viario en período Lden
TRANSIT_N      Ruido de tráfico viario en período noche
TRANSIT_E      Ruido de tráfico viario en período tarde
TRANSIT_D      Ruido de trafico viario en periodo dia
TOTAL_DEN      Ruido total en período Lden
TOTAL_N        ruido total en periodo noche
PATIS_E        Ruido en patios interiores en período tarde

In [323]:
soroll = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\capacidad acustica\\2017_barris_soroll_bcn_long.csv")

In [326]:
x = eco.soroll_barris(soroll)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["codi_districte", "codi_barri", "time"], inplace=True)

In [327]:
x

     nom_districte                barri     sound  valor
2190  Ciutat Vella             el Raval    <40 dB   0.27
2191  Ciutat Vella             el Raval  40-45 dB  28.36
2192  Ciutat Vella             el Raval  45-50 dB  11.97
2193  Ciutat Vella             el Raval  50-55 dB   7.95
2194  Ciutat Vella             el Raval  55-60 dB  15.40
...            ...                  ...       ...    ...
2915    Sant Martí  la Verneda i la Pau  60-65 dB  21.59
2916    Sant Martí  la Verneda i la Pau  65-70 dB  13.08
2917    Sant Martí  la Verneda i la Pau  70-75 dB   4.05
2918    Sant Martí  la Verneda i la Pau  75-80 dB   0.00
2919    Sant Martí  la Verneda i la Pau   >=80 dB   0.00

[730 rows x 4 columns]

### Green points

delete non necesary.

In [328]:
y = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\puntos_ecologicos.csv")

In [331]:
green = eq.clean_equipamientos (y)

In [334]:
green

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Punt Verd Mòbil *Mercat Bon Pastor,59,el Bon Pastor,9,Sant Andreu,Punts verds mòbils,41.436470,2.206245,C Sant Adrià 137
1,Punt Verd de Barri - Mercat de Sant Antoni,10,Sant Antoni,2,Eixample,Punts verds de barri,41.379065,2.161312,C Tamarit 169
2,Punt Verd Mòbil *Diagonal Mar,70,el Besòs i el Maresme,10,Sant Martí,Punts verds mòbils,41.410748,2.215235,C Llull 379
3,Punt Verd Mòbil *Passeig Sant Joan-Indústria,32,el Camp d'en Grassot i Gràcia Nova,6,Gràcia,Punts verds mòbils,41.402804,2.164687,Pg Sant Joan 169
4,Punt Verd Mòbil *Numància-Nau Santa Maria,19,les Corts,4,Les Corts,Punts verds mòbils,41.390934,2.131934,C Numància 180
...,...,...,...,...,...,...,...,...,...
606,Contenidor Roba Amiga * Via Júlia,51,Verdun,8,Nou Barris,Punts de roba amiga,41.441832,2.177335,Via Júlia 95
607,Contenidor Roba Amiga * Mercat de La Marina,13,la Marina de Port,3,Sants-Montjuïc,Punts de roba amiga,41.360349,2.139175,Passeig de la Zona Franca 178
608,Contenidor Roba Amiga * Punt Verd de Barri Sarrià,23,Sarrià,5,Sarrià-Sant Gervasi,Punts de roba amiga,41.397280,2.126532,Carrer del Cardenal Sentmenat 6
609,Contenidor de Sal *Torrent Font Mont - C. Font...,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,Contenidors de sal,41.413893,2.111225,Carrer de la Font del Mont 1
610,Contenidor de Sal * Escola Bressol La Puput,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,Contenidors de sal,41.415350,2.102357,Carrer d'Elisa Moragas i Badia 29

do sub queries to select just the necesary.

In [335]:
green["category"].value_counts()

Punts de recollida d'arbres de Nadal    226
Punts de roba amiga                     123
Contenidors de sal                      113
Punts verds mòbils                       97
Punts verds de barri                     27
Horts urbans                             15
Punts verds de zona                       7
Punts verds col·laboradors                1
Name: category, dtype: int64

### Jardin interiors.

In [337]:
interior = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\jardin_interiors.csv")

In [339]:
interior = eq.clean_pool (interior)

In [341]:
interior.sample()

,name,barri_id,barri,district_id,district,latitude,longitude,address
26,Jardins Interior d'Illa de Maria-Mercè Marçal,9,la Nova Esquerra de l'Eixample,2,Eixample,41.386378,2.149593,Carrer de Provença 97

### refugis.

In [344]:
refugi = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\refugi.csv")

refiguios tipo escuelas, parques, lugares tipo asilos bibliotecas, de espacios publicos.

In [345]:
refugi = eq.clean_pool (refugi)

In [348]:
refugi.sample()

,name,barri_id,barri,district_id,district,latitude,longitude,address
177,El Centre de la Platja,3,la Barceloneta,1,Ciutat Vella,41.383219,2.195019,Pg Marítim Barceloneta 25

### Arbolado.

In [350]:
viari = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\arbrat\OD_Arbrat_Viari_BCN.csv")

In [351]:
viari

,codi,x_etrs89,y_etrs89,latitud,longitud,tipus_element,espai_verd,adreca,cat_especie_id,nom_cientific,...,categoria_arbrat,data_plantacio,tipus_aigua,tipus_reg,geom,catalogacio,codi_barri,nom_barri,codi_districte,nom_districte
0,0000025AR,430270.562,4587637.998,41.437287,2.165353,ARBRE VIARI,"Central de Nou Barris, Parc","Pg Fabra i Puig, 450",2336,Fraxinus angustifolia 'Raywood',...,PRIMERA,2022-02-15,NaN,GOTEIG AVARIAT,POINT (430270.561661092 4587637.99844993),NaN,48.0,LA GUINEUETA,8,NOU BARRIS
1,0000028AR,430277.559,4587643.344,41.437335,2.165436,ARBRE VIARI,"Central de Nou Barris, Parc","Pg Fabra i Puig, 450",2336,Fraxinus angustifolia 'Raywood',...,PRIMERA,2022-02-15,NaN,GOTEIG AVARIAT,POINT (430277.558712503 4587643.34440513),NaN,48.0,LA GUINEUETA,8,NOU BARRIS
2,0000386AR,430035.239,4587693.836,41.437769,2.162530,ARBRE VIARI,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",126,Platanus x hispanica,...,SEGONA,NaN,NaN,SENSE INFORMAR,POINT (430035.238676006 4587693.83631125),NaN,43.0,HORTA,7,HORTA - GUINARDÓ
3,0000387AR,430032.831,4587696.005,41.437788,2.162501,ARBRE VIARI,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",126,Platanus x hispanica,...,SEGONA,NaN,NaN,SENSE INFORMAR,POINT (430032.831137134 4587696.00500337),NaN,43.0,HORTA,7,HORTA - GUINARDÓ
4,0000388AR,430030.367,4587698.393,41.437810,2.162471,ARBRE VIARI,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",126,Platanus x hispanica,...,SEGONA,NaN,NaN,SENSE INFORMAR,POINT (430030.366746935 4587698.39336605),NaN,43.0,HORTA,7,HORTA - GUINARDÓ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153827,0332602AR,432355.014,4585698.082,41.419993,2.190518,ARBRE VIARI,NaN,"C\ Josep Estivill, 65",739,Melia azedarach,...,PRIMERA,2023-02-04,POTABLE,GOTEIG,POINT (432355.014 4585698.082),NaN,61.0,LA SAGRERA,9,SANT ANDREU
153828,0332603AR,432360.160,4585703.060,41.420038,2.190579,ARBRE VIARI,NaN,"Ptge Bofarull, 2",739,Melia azedarach,...,PRIMERA,2023-02-04,POTABLE,GOTEIG,POINT (432360.16 4585703.06),NaN,61.0,LA SAGRERA,9,SANT ANDREU
153829,0332604AR,432407.414,4585676.221,41.419800,2.191147,ARBRE VIARI,NaN,"C\ Gran de la Sagrera, 12",739,Melia azedarach,...,PRIMERA,2023-02-04,POTABLE,GOTEIG,POINT (432407.414 4585676.221),NaN,61.0,LA SAGRERA,9,SANT ANDREU
153830,0332605AR,432406.765,4585696.095,41.419979,2.191137,ARBRE VIARI,NaN,"C\ Gran de la Sagrera, 12",739,Melia azedarach,...,PRIMERA,2023-02-04,POTABLE,GOTEIG,POINT (432406.765 4585696.095),NaN,61.0,LA SAGRERA,9,SANT ANDREU
153831,0332606AR,432406.526,4585666.893,41.419716,2.191138,ARBRE VIARI,"Hondures, c. - Sagrera, c. - Josep Estivill, c.","C\ Gran de la Sagrera, 49",1104,Celtis australis,...,SEGONA,NaN,POTABLE,GOTEIG,POINT (432406.526 4585666.893),NaN,61.0,LA SAGRERA,9,SANT ANDREU

In [217]:
viari.columns

Index(['codi', 'x_etrs89', 'y_etrs89', 'latitud', 'longitud', 'tipus_element',
       'espai_verd', 'adreca', 'cat_especie_id', 'nom_cientific',
       'nom_castella', 'nom_catala', 'categoria_arbrat', 'data_plantacio',
       'tipus_aigua', 'tipus_reg', 'geom', 'catalogacio', 'codi_barri',
       'nom_barri', 'codi_districte', 'nom_districte'],
      dtype='object')

In [218]:
viari = viari.drop(columns=["codi", "x_etrs89", "y_etrs89", "tipus_element", "cat_especie_id", "tipus_aigua", "tipus_reg", "nom_catala", "geom", "catalogacio"])

In [219]:
viari

,latitud,longitud,espai_verd,adreca,nom_cientific,nom_castella,categoria_arbrat,data_plantacio,codi_barri,nom_barri,codi_districte,nom_districte
0,41.437287,2.165353,"Central de Nou Barris, Parc","Pg Fabra i Puig, 450",Fraxinus angustifolia 'Raywood',-,PRIMERA,2022-02-15,48.0,LA GUINEUETA,8,NOU BARRIS
1,41.437335,2.165436,"Central de Nou Barris, Parc","Pg Fabra i Puig, 450",Fraxinus angustifolia 'Raywood',-,PRIMERA,2022-02-15,48.0,LA GUINEUETA,8,NOU BARRIS
2,41.437769,2.162530,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",Platanus x hispanica,Plátano,SEGONA,NaN,43.0,HORTA,7,HORTA - GUINARDÓ
3,41.437788,2.162501,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",Platanus x hispanica,Plátano,SEGONA,NaN,43.0,HORTA,7,HORTA - GUINARDÓ
4,41.437810,2.162471,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",Platanus x hispanica,Plátano,SEGONA,NaN,43.0,HORTA,7,HORTA - GUINARDÓ
...,...,...,...,...,...,...,...,...,...,...,...,...
153827,41.419993,2.190518,NaN,"C\ Josep Estivill, 65",Melia azedarach,Melia; cinamomo,PRIMERA,2023-02-04,61.0,LA SAGRERA,9,SANT ANDREU
153828,41.420038,2.190579,NaN,"Ptge Bofarull, 2",Melia azedarach,Melia; cinamomo,PRIMERA,2023-02-04,61.0,LA SAGRERA,9,SANT ANDREU
153829,41.419800,2.191147,NaN,"C\ Gran de la Sagrera, 12",Melia azedarach,Melia; cinamomo,PRIMERA,2023-02-04,61.0,LA SAGRERA,9,SANT ANDREU
153830,41.419979,2.191137,NaN,"C\ Gran de la Sagrera, 12",Melia azedarach,Melia; cinamomo,PRIMERA,2023-02-04,61.0,LA SAGRERA,9,SANT ANDREU
153831,41.419716,2.191138,"Hondures, c. - Sagrera, c. - Josep Estivill, c.","C\ Gran de la Sagrera, 49",Celtis australis,Almez,SEGONA,NaN,61.0,LA SAGRERA,9,SANT ANDREU

In [225]:
viari.shape

(153832, 12)

### arbrat parcs

located in the squares, flower beds, gazebos or small garden spaces

In [220]:
parcs = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\arbrat\OD_Arbrat_Parcs_BCN.csv")

In [222]:
parcs = parcs.drop(columns=["codi", "x_etrs89", "y_etrs89", "tipus_element", "cat_especie_id", "tipus_aigua", "tipus_reg", "nom_catala", "geom", "catalogacio"])

KeyError: "['codi', 'x_etrs89', 'y_etrs89', 'tipus_element', 'cat_especie_id', 'tipus_aigua', 'tipus_reg', 'nom_catala', 'geom', 'catalogacio'] not found in axis"

In [224]:
parcs.shape

(35922, 12)

### Arbrat Zona

In [227]:
zona = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\arbrat\OD_Arbrat_Zona_BCN.csv")

In [231]:
zona = zona.drop(columns=["codi", "x_etrs89", "y_etrs89", "tipus_element", "cat_especie_id", "tipus_aigua", "tipus_reg", "nom_catala", "geom", "catalogacio"])

In [239]:
zona.data_plantacio.isna().sum()

40345

In [229]:
zona.shape

(43392, 22)