# Equipamiento Urbano
## Ayuntamiento de Barcelona

In [231]:
import pandas as pd
import src.equipamiento as eq
import importlib
importlib.reload(eq)

## Cultura.
### centros civicos

In [232]:
civic = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\\2021_centres_civics_entitats.csv")

In [233]:
civic = eq.civic_ (civic)

In [235]:
civic

,name,district_id,district,barri_id,barri,latitud,longitud,total_usos_entitats,metres_quadrats
0,Centre Cívic Barceloneta,1,Ciutat Vella,3,la Barceloneta,41.380269,2.192301,130,1431
1,Centre Cívic Baró de Viver,9,Sant Andreu,58,Baró de Viver,41.448392,2.199921,39,1535
2,Centre Cívic Besòs,10,Sant Martí,70,el Besòs i el Maresme,41.416306,2.211479,0,3858
3,Centre Cívic Bon Pastor,9,Sant Andreu,59,el Bon Pastor,41.434780,2.204912,29,1370
4,Centre Cívic Can Basté,8,Nou Barris,46,el Turó de la Peira,41.430459,2.173212,54,1060
5,Centre Cívic Can Castelló,5,Sarrià-Sant Gervasi,26,Sant Gervasi - Galvany,41.399006,2.140163,17,1200
6,Centre Cívic Can Clariana Cultural,9,Sant Andreu,62,el Congrés i els Indians,41.427518,2.178412,72,842
7,Centre Cívic Can Deu,4,Les Corts,19,les Corts,41.386761,2.132502,0,803
8,Centre Cívic Can Felipa,10,Sant Martí,68,el Poblenou,41.404013,2.201387,72,3125
9,Centre Cívic Can Verdaguer,8,Nou Barris,45,Porta,41.433977,2.179080,52,990
10,Centre Cívic Casa del Rellotge,3,Sants-Montjuïc,13,la Marina de Port,41.357544,2.141390,32,880
11,Centre Cívic Casa Groga,7,Horta-Guinardó,39,Sant Genís dels Agudells,41.426863,2.137450,20,1152
12,Centre Cívic Casa Orlandai,5,Sarrià-Sant Gervasi,23,Sarrià,41.398330,2.124656,96,1066
13,Centre Cívic Convent de Sant Agustí,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",41.387391,2.181711,104,1655
14,Centre Cívic Cotxeres Borrell,2,Eixample,10,Sant Antoni,41.375909,2.163176,98,1775
15,Centre Cívic Cotxeres de Sants,3,Sants-Montjuïc,18,Sants,41.375264,2.136876,180,3167
16,Centre Cívic del Parc - Sandaru,10,Sant Martí,66,el Parc i la Llacuna del Poblenou,41.391719,2.184755,64,2000
17,Centre Cívic Drassanes,1,Ciutat Vella,1,el Raval,41.377645,2.172852,6,1074
18,Centre Cívic El Carmel,7,Horta-Guinardó,37,el Carmel,41.420264,2.151191,42,1054
19,Centre Cívic El Coll - La Bruguera,6,Gràcia,29,el Coll,41.418579,2.149897,0,1300
20,Centre Cívic El Sortidor,3,Sants-Montjuïc,11,el Poble Sec,41.372067,2.162532,119,905
21,Centre Cívic Font de la Guatlla,3,Sants-Montjuïc,14,la Font de la Guatlla,41.370560,2.147509,12,635
22,Centre Cívic Fort Pienc,2,Eixample,5,el Fort Pienc,41.395557,2.182446,114,1306
23,Centre Cívic Golferichs,2,Eixample,9,la Nova Esquerra de l'Eixample,41.380813,2.156392,46,1025
24,Centre Cívic Guinardó,7,Horta-Guinardó,35,el Guinardó,41.416056,2.173323,52,600
25,Centre Cívic Joan Oliver - Pere Quart,4,Les Corts,20,la Maternitat i Sant Ramon,41.379303,2.127758,45,2433
26,Centre Cívic Josep M. Trias i Peitx - Riera Bl...,4,Les Corts,20,la Maternitat i Sant Ramon,41.377780,2.121763,0,800
27,Centre Cívic l'Elèctric,5,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",41.419138,2.097872,17,566
28,Centre Cívic La Cadena,3,Sants-Montjuïc,13,la Marina de Port,41.364156,2.139067,6,333
29,Centre Cívic La Casa Elizalde,2,Eixample,7,la Dreta de l'Eixample,41.394484,2.165881,52,1800
30,Centre Cívic La Sagrera,9,Sant Andreu,61,la Sagrera,41.423942,2.189139,12,903
31,Centre Cívic La Sedeta,6,Gràcia,32,el Camp d'en Grassot i Gràcia Nova,41.405549,2.167665,36,1287
32,Centre Cívic Matas i Ramis,7,Horta-Guinardó,43,Horta,41.432755,2.160711,17,637
33,Centre Cívic Navas,9,Sant Andreu,63,Navas,41.416905,2.184919,54,1200
34,Centre Cívic Pati Llimona,1,Ciutat Vella,2,el Barri Gòtic,41.381636,2.179176,30,1900
35,Centre Cívic Pere Pruna,5,Sarrià-Sant Gervasi,25,Sant Gervasi - la Bonanova,41.403182,2.131303,4,287
36,Centre Cívic Sagrada Família,2,Eixample,6,la Sagrada Família,41.405380,2.176760,33,1900
37,Centre Cívic Sant Andreu,9,Sant Andreu,60,Sant Andreu,41.430853,2.189401,15,900
38,Centre Cívic Sant Martí,10,Sant Martí,72,Sant Martí de Provençals,41.416622,2.198564,130,5470
39,Centre Cívic Sarrià,5,Sarrià-Sant Gervasi,23,Sarrià,41.393872,2.121164,0,1011
40,Centre Cívic Teixonera,7,Horta-Guinardó,38,la Teixonera,41.422638,2.144555,43,841
41,Centre Cívic Tomasa Cuevas - Les Corts,4,Les Corts,19,les Corts,41.384784,2.128318,47,1603
42,Centre Cívic Torre Llobeta,8,Nou Barris,44,Vilapicina i la Torre Llobeta,41.426897,2.173951,63,738
43,Centre Cívic Trinitat Vella,9,Sant Andreu,57,la Trinitat Vella,41.451619,2.191190,53,750
44,Centre Cívic Urgell,2,Eixample,9,la Nova Esquerra de l'Eixample,41.386861,2.152032,100,953
45,Centre Cívic Vallvidrera Vázquez Montalbán,5,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",41.415364,2.102531,5,618
46,Centre Cívic Vil·la Florida,5,Sarrià-Sant Gervasi,25,Sant Gervasi - la Bonanova,41.405337,2.135294,22,1574
47,Centre Cívic Vil·la Urània,5,Sarrià-Sant Gervasi,27,el Putxet i el Farró,41.398643,2.142760,88,3415
48,Centre Cívic Zona Nord,8,Nou Barris,55,Ciutat Meridiana,41.461114,2.177397,47,2418
49,Centre Cultural Albareda,3,Sants-Montjuïc,11,el Poble Sec,41.374000,2.173269,203,1473
50,Centre Cultural la Farinera del Clot,10,Sant Martí,65,el Clot,41.404914,2.188443,84,2634

### restaurants

In [236]:
rest = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\\restaurants.csv")

In [237]:
rest = eq.clean_equipamientos (rest)

In [239]:
rest

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Restaurant Els Pollos de Llull *Ramon Turró,67,la Vila Olímpica del Poblenou,10,Sant Martí,Restaurants,41.391080,2.190942,C Ramon Turró 13
1,Restaurant La Royale,25,Sant Gervasi - la Bonanova,5,Sarrià-Sant Gervasi,Restaurants,41.403463,2.136026,Pl Camp 5
2,Restaurant Ca l'Isidre,1,el Raval,1,Ciutat Vella,Restaurants,41.375971,2.167983,C Flors 12
3,Bar Restaurant Baztan,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Restaurants,41.393962,2.156358,C Balmes 147
4,Restaurant Maccabi,1,el Raval,1,Ciutat Vella,Restaurants,41.381461,2.172793,C Rambla 79
...,...,...,...,...,...,...,...,...,...
2586,Bar Neutral,26,Sant Gervasi - Galvany,5,Sarrià-Sant Gervasi,Restaurants,41.393553,2.138566,C Ganduxer 26
2587,Restaurant Khalijia Shisha,7,la Dreta de l'Eixample,2,Eixample,Restaurants,41.390253,2.170580,Carrer de Pau Claris 92
2588,Hamburgueseria Rock & Boom,31,la Vila de Gràcia,6,Gràcia,Restaurants,41.398400,2.159791,Carrer de Bonavista 21
2589,Restaurant Bo de Bernat,10,Sant Antoni,2,Eixample,Restaurants,41.380510,2.160515,C Comte d'Urgell 27
2590,Bar Restaurant Chamako,11,el Poble-sec,3,Sants-Montjuïc,Restaurants,41.373813,2.163556,Carrer de Margarit 18

### Museum libraries.

In [240]:
mus = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\museum_libraries.csv")

In [241]:
mus = eq.clean_equipamientos (mus)

In [243]:
mus = clean_ids (mus)

In [245]:
mus

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Biblioteca Joan Miró,9,la Nova Esquerra de l'Eixample,2,Eixample,Biblioteques,41.378848,2.149248,Carrer de Vilamarí 61
1,Biblioteca Joan Miró,9,la Nova Esquerra de l'Eixample,2,Eixample,Biblioteques municipals,41.378848,2.149248,Carrer de Vilamarí 61
2,Biblioteca Joan Miró,9,la Nova Esquerra de l'Eixample,2,Eixample,Sales d'estudi,41.378848,2.149248,Carrer de Vilamarí 61
3,Museu Futbol Club Barcelona President Núñez,20,la Maternitat i Sant Ramon,4,Les Corts,Museus,41.379091,2.120286,Carrer d'Arístides Maillol 12
4,Museu del Disseny de Barcelona,66,el Parc i la Llacuna del Poblenou,10,Sant Martí,Museus,41.402601,2.188050,Plaça de les Glòries Catalanes 37
...,...,...,...,...,...,...,...,...,...
456,Biblioteca Camp de l'Arpa - Caterina Albert,64,el Camp de l'Arpa del Clot,10,Sant Martí,Sales d'estudi,41.415797,2.182298,Carrer de la Indústria 295
457,CRAI - Biblioteca de Fons Antic,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Sales d'estudi,41.386577,2.164030,G
458,Sala d'Estudi Montserrat Abelló - Les Corts,19,les Corts,4,Les Corts,Sales d'estudi,41.383731,2.135306,C Comtes de Bell-lloc 192
459,Biblioteca Marta Mata,23,Sarrià,5,Sarrià-Sant Gervasi,Biblioteques,41.397392,2.119283,C Domínguez i Miralles 1
460,EcoMuseu Urbà Gitano de Barcelona,1,el Raval,1,Ciutat Vella,Museus,41.379232,2.166539,Carrer de la Cera 10

### music and drinks. NOT

In [246]:
drinks = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\music_drinks.csv")

In [247]:
drinks = eq.clean_equipamientos (drinks)

In [249]:
drinks

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Karaoke Touch Music,67,la Vila Olímpica del Poblenou,10,Sant Martí,Karaokes,41.389967,2.196581,C Joan Miró 8
1,Cocteleria P41 Bar & Coctelarium,3,la Barceloneta,1,Ciutat Vella,Cocteleries,41.387113,2.196574,C Marina 19
2,Cocteleria P41 Bar & Coctelarium,3,la Barceloneta,1,Ciutat Vella,Xampanyeries,41.387113,2.196574,C Marina 19
3,Golden Shisha Lounge,26,Sant Gervasi - Galvany,5,Sarrià-Sant Gervasi,Discoteques,41.400357,2.141796,C Plató 13
4,Bar Marsella,1,el Raval,1,Ciutat Vella,Bars i pubs musicals,41.378278,2.171224,C Sant Pau 65
...,...,...,...,...,...,...,...,...,...
614,Cocteleria Nola,31,la Vila de Gràcia,6,Gràcia,Cocteleries,41.398079,2.159655,Carrer de Santa Teresa 1
615,Cocteleria Nola,31,la Vila de Gràcia,6,Gràcia,Xampanyeries,41.398079,2.159655,Carrer de Santa Teresa 1
616,Bar Soda bus & Verne,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Cocteleries,41.392070,2.154656,Carrer d'Aribau 150
617,Bar Soda bus & Verne,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Xampanyeries,41.392070,2.154656,Carrer d'Aribau 150
618,Bar Soda bus & Verne,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Restaurants,41.392070,2.154656,Carrer d'Aribau 150

### cines

In [250]:
cine = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\cinema.csv")

In [251]:
cine = eq.clean_equipamientos (cine)

In [253]:
cine

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Auditòrium,2,el Barri Gòtic,1,Ciutat Vella,Auditoris,41.382838,2.176818,Pl Sant Jaume 4
1,Teatre,60,Sant Andreu,9,Sant Andreu,Teatres,41.435729,2.186494,C Pons i Gallarza 58
2,Sala de Cinema,1,el Raval,1,Ciutat Vella,Cinemes,41.376851,2.173408,Av Drassanes 14
3,Teatre,64,el Camp de l'Arpa del Clot,10,Sant Martí,Teatres,41.410450,2.182461,C Provença 591
4,Teatre Romea,1,el Raval,1,Ciutat Vella,Teatres,41.380585,2.171083,C Hospital 51
...,...,...,...,...,...,...,...,...,...
190,Auditòrium,4,"Sant Pere, Santa Caterina i la Ribera",1,Ciutat Vella,Auditoris,41.391283,2.181347,Pg Lluís Companys 18
191,Centre de les Arts Lliures,4,"Sant Pere, Santa Caterina i la Ribera",1,Ciutat Vella,Teatres,41.384998,2.182022,Carrer de la Seca 2
192,Teatre,10,Sant Antoni,2,Eixample,Teatres,41.377441,2.155998,C Rocafort 42
193,Teatre,16,la Bordeta,3,Sants-Montjuïc,Teatres,41.371054,2.131946,Rbla Badal 113
194,Club Onyric,11,el Poble-sec,3,Sants-Montjuïc,Teatres,41.374807,2.164728,Av Paral

## educacion.
### escuelas

In [254]:
schools = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\equipamiento\education.csv")

In [255]:
schools = eq.clean_equipamientos (schools)

In [256]:
schools = eq.clean_ids (schools)

In [257]:
schools

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
1,Centre Educatiu Valldaura,52,la Prosperitat,8,Nou Barris,Ensenyament infantil (3-6 anys),41.442245,2.180029,C Santa Engràcia 110
2,Centre Educatiu Valldaura,52,la Prosperitat,8,Nou Barris,Educació primària,41.442245,2.180029,C Santa Engràcia 110
3,Centre Educatiu Valldaura,52,la Prosperitat,8,Nou Barris,Educació secundària,41.442245,2.180029,C Santa Engràcia 110
5,Centre Educatiu Vedruna Gràcia Barcelona,31,la Vila de Gràcia,6,Gràcia,Ensenyament infantil (3-6 anys),41.404718,2.151416,C Gran de Gràcia 234
6,Centre Educatiu Vedruna Gràcia Barcelona,31,la Vila de Gràcia,6,Gràcia,Educació primària,41.404718,2.151416,C Gran de Gràcia 234
...,...,...,...,...,...,...,...,...,...
2664,Escola de Doctorat - UB,10,Sant Antoni,2,Eixample,Universitats,41.384856,2.162637,Gran Via de les Corts Catalanes 582
2665,Institut de Biologia Evolutiva,3,la Barceloneta,1,Ciutat Vella,Universitats,41.385565,2.193994,Carrer del Doctor Aiguader 88
2669,Nuclio Digital School,6,la Sagrada Família,2,Eixample,Informàtica,41.407147,2.175102,Carrer de Padilla 285
2672,Llar d'Infants El Camí Feliç ZAL Port,12,la Marina del Prat Vermell,3,Sants-Montjuïc,Ensenyament infantil (0-3 anys),41.322168,2.134977,Avinguda dels Ports d'Europa 90
2678,Llar d'Infants Kasperle,31,la Vila de Gràcia,6,Gràcia,Ensenyament infantil (0-3 anys),41.400944,2.154074,C Gran de Gràcia 97

### hospitals

In [258]:
hospitals = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\equipamiento\hospitals.csv")

In [259]:
hospitals = eq.clean_equipamientos (hospitals)

In [261]:
hospitals

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Hospital El Pilar - Institut Cardiovascular Sa...,26,Sant Gervasi - Galvany,5,Sarrià-Sant Gervasi,Hospitals i clíniques,41.400457,2.148500,C Balmes 271
1,Centre d'Atenció Primària Vallvidrera,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,CAPs,41.413818,2.104164,Carrer d'Elisa Moragas i Badia 2
2,Centre d'Atenció Primària Turó,46,el Turó de la Peira,8,Nou Barris,CAPs,41.433082,2.170579,C Cadí 58
3,Centre d'Atenció Primària El Clot,65,el Clot,10,Sant Martí,CAPs,41.411767,2.193049,C Concili de Trento 25
4,Clínica Sant Antoni,13,la Marina de Port,3,Sants-Montjuïc,Hospitals i clíniques,41.356077,2.143294,C Sant Eloi 6
...,...,...,...,...,...,...,...,...,...
137,Centre d'Urgències d'Atenció Primària Horta,43,Horta,7,Horta-Guinardó,Centres urgències (CUAPs),41.434841,2.157430,C Sant Gaudenci 21
138,Centre d'Atenció Primària Casernes,60,Sant Andreu,9,Sant Andreu,CAPs,41.443165,2.192838,C Fernando Pessoa 51
139,Clínica Oftalvist,24,les Tres Torres,5,Sarrià-Sant Gervasi,Hospitals i clíniques,41.401070,2.125112,Carrer d'Anglí 38
140,Centre Mèdic Vilasalut *Barcelona,23,Sarrià,5,Sarrià-Sant Gervasi,Hospitals i clíniques,41.400146,2.119736,Sagrat Cor 7
141,Clínica Cipsalut,9,la Nova Esquerra de l'Eixample,2,Eixample,Hospitals i clíniques,41.381837,2.155480,Carrer de la Diputació 95

## SPORT
### excersice

In [54]:
exc = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\excersice.csv")

In [55]:
exc

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿99400297249,Àrea Esportiva,9.208603e+10,Parc de la Unitat,2012-07-12T00:00:00+02:00,2022-04-29T05:17:01.869892+02:00,NaN,NaN,186204,C Lloret de Mar,...,NaN,NaN,NaN,NaN,NaN,NaN,429640.510723,4.587535e+06,41.436303,2.157824
1,﻿99400297250,Àrea Esportiva *Pardo - Can Ros - Concepció Ar...,NaN,NaN,2012-07-12T10:07:27+02:00,2022-04-29T05:17:02.261529+02:00,NaN,NaN,160608,C Can Ros,...,NaN,NaN,NaN,NaN,NaN,NaN,431757.033399,4.586473e+06,41.426917,2.183275
2,﻿99400297205,Àrea Esportiva,9.216814e+10,Platja del Bogatell,2012-07-11T00:00:00+02:00,2022-04-29T05:16:58.852421+02:00,NaN,NaN,700756,Pg Marítim del Bogatell,...,NaN,NaN,NaN,NaN,NaN,NaN,433686.031383,4.582867e+06,41.394603,2.206754
3,﻿99400575466,Espai Gimnàstic per a Gent Gran *Pujalt,NaN,NaN,2018-01-25T09:35:53+01:00,2021-03-29T16:44:30.185453+02:00,NaN,NaN,271201,C Pujalt,...,NaN,NaN,NaN,NaN,NaN,NaN,431742.476730,4.590471e+06,41.462926,2.182649
4,﻿99400575501,Espai Gimnàstic per a Gent Gran *Jocs Esportiu...,NaN,NaN,2018-01-25T11:36:04+01:00,2021-03-29T16:44:20.955412+02:00,NaN,NaN,270901,C Pujades,...,NaN,NaN,NaN,NaN,NaN,NaN,434180.367237,4.584614e+06,41.410381,2.212477
5,﻿99400575506,Espai Gimnàstic per a Gent Gran,9.511411e+10,Jardins Ca l'Alena,2018-01-25T11:54:09+01:00,2021-03-29T16:44:20.371997+02:00,NaN,NaN,230601,C Mare de Déu de Port,...,NaN,NaN,NaN,NaN,NaN,NaN,428302.699521,4.579010e+06,41.359406,2.142822
6,﻿99400575508,Espai Gimnàstic per a Gent Gran *Plaça Navas,NaN,NaN,2018-01-25T11:59:51+01:00,2021-03-29T16:44:18.773153+02:00,NaN,NaN,226309,Pl Las Navas,...,NaN,NaN,NaN,NaN,NaN,NaN,429710.700485,4.580624e+06,41.374069,2.159467
7,﻿99400575430,Espai Gimnàstic per a Gent Gran,9.626914e+10,Parc de la Barceloneta,2018-01-24T16:08:15+01:00,2021-03-29T16:44:37.543462+02:00,NaN,NaN,197903,Pg Marítim de la Barceloneta,...,NaN,NaN,NaN,NaN,NaN,NaN,432593.428278,4.581484e+06,41.382060,2.193840
8,﻿99400575450,Espai Gimnàstic per a Gent Gran,9.911213e+10,Jardins d'Antoni Puigvert,2018-01-24T00:00:00+01:00,2023-01-31T14:46:26.758045+01:00,NaN,NaN,325005,Carrer de Sicília,...,NaN,NaN,NaN,NaN,NaN,NaN,430564.884000,4.584006e+06,41.404604,2.169292
9,﻿99400575454,Espai Gimnàstic per a Gent Gran *Parc Sanitar...,NaN,NaN,2018-01-24T17:28:07+01:00,2021-03-29T16:44:35.641213+02:00,NaN,NaN,116901,C Esteve Terradas,...,NaN,NaN,NaN,NaN,NaN,NaN,428150.072689,4.585179e+06,41.414955,2.140266
10,﻿99400575456,Espai Gimnàstic per a Gent Gran,9.510913e+10,Jardins del Baix Guinardó,2018-01-24T17:36:00+01:00,2021-03-29T16:44:34.768564+02:00,NaN,NaN,197302,C Marina,...,NaN,NaN,NaN,NaN,NaN,NaN,430441.603559,4.584582e+06,41.409781,2.167751
11,﻿99400575462,Espai Gimnàstic per a Gent Gran,9.940007e+10,Jardins de Josep Munté,2018-01-25T09:20:26+01:00,2021-03-29T16:44:30.951676+02:00,NaN,NaN,65200,C Cardenal Reig,...,NaN,NaN,NaN,NaN,NaN,NaN,426160.278885,4.581203e+06,41.378964,2.116944
12,﻿99400575421,Espai Gimnàstic per a Gent Gran *Arc de Teatre,NaN,NaN,2018-01-24T15:50:29+01:00,2021-03-29T16:44:38.161012+02:00,NaN,NaN,21306,C Arc del Teatre,...,NaN,NaN,NaN,NaN,NaN,NaN,430939.380467,4.580962e+06,41.377218,2.174119
13,﻿99400575457,Espai Gimnàstic per a Gent Gran,9.940032e+10,Parc de les Rieres d'Horta,2018-01-24T17:39:48+01:00,2021-03-29T16:44:34.137146+02:00,NaN,NaN,700651,Av Estatut de Catalunya,...,NaN,NaN,NaN,NaN,NaN,NaN,429259.595481,4.587240e+06,41.433612,2.153300
14,﻿99400575465,Espai Gimnàstic per a Gent Gran *Zona Esporti...,NaN,NaN,2018-01-25T09:32:53+01:00,2021-03-29T16:44:30.852890+02:00,NaN,NaN,275600,Av Rasos de Peguera,...,NaN,NaN,NaN,NaN,NaN,NaN,431105.634980,4.590101e+06,41.459543,2.175067
15,﻿99400575474,Espai Gimnàstic per a Gent Gran,9.940058e+10,Jardins Can Xiringoi,2018-01-25T00:00:00+01:00,2021-03-29T16:44:32.568929+02:00,NaN,NaN,8603,C Costa i Cuxart,...,NaN,NaN,NaN,NaN,NaN,NaN,431126.427501,4.586567e+06,41.427716,2.175718
16,﻿99400297246,Espai Gimnàstic per a Gent Gran,9.940023e+10,Jardins Interior d'Illa Càndida Pérez,2012-07-12T00:00:00+02:00,2022-04-29T05:16:59.863216+02:00,NaN,NaN,87009,C Comte Borrell,...,NaN,NaN,NaN,NaN,NaN,NaN,430025.474340,4.581026e+06,41.377713,2.163184
17,﻿99400297199,Espai Gimnàstic per a Gent Gran * Conca de Tre...,NaN,NaN,2012-07-11T10:07:40+02:00,2022-04-29T05:16:59.420679+02:00,NaN,NaN,85900,C Conca de Tremp,...,NaN,NaN,NaN,NaN,NaN,NaN,429366.462663,4.586196e+06,41.424218,2.154701
18,﻿99400172076,Espai Gimnàstic per a Gent Gran,9.822518e+10,Jardins de Vil·la Cecília,2006-11-17T13:49:40+01:00,2021-03-29T17:00:29.070262+02:00,NaN,NaN,107300,C Eduardo Conde,...,NaN,NaN,NaN,NaN,NaN,NaN,426531.902910,4.582858e+06,41.393906,2.121187
19,﻿99400575437,Espai Gimnàstic per a Gent Gran *Pl del Mar,NaN,NaN,2018-01-24T16:18:45+01:00,2021-03-29T16:44:36.153999+02:00,NaN,NaN,700911,Pl Mar,...,NaN,NaN,NaN,NaN,NaN,NaN,432130.607914,4.580516e+06,41.373300,2.188414
20,﻿99400575478,Espai Gimnàstic per a Gent Gran,9.208601e+10,Parc del Turó de la Peira,2018-01-25T09:58:23+01:00,2021-03-29T16:44:26.323576+02:00,NaN,NaN,119003,Pg Fabra i Puig,...,NaN,NaN,NaN,NaN,NaN,NaN,430108.064252,4.587215e+06,41.433467,2.163457
21,﻿99400575480,Espai Gimnàstic per a Gent Gran *Via Favència ...,NaN,NaN,2018-01-25T10:05:14+01:00,2021-03-29T16:44:24.967110+02:00,NaN,NaN,34400,Via Bàrcino,...,NaN,NaN,NaN,NaN,NaN,NaN,432505.582664,4.588809e+06,41.448025,2.191972
22,﻿99400575491,Espai Gimnàstic per a Gent Gran *Pl Assemblea...,NaN,NaN,2018-01-25T11:09:37+01:00,2021-03-29T16:44:23.085239+02:00,NaN,NaN,17604,C Antilles,...,NaN,NaN,NaN,NaN,NaN,NaN,432161.043674,4.586248e+06,41.424931,2.188135
23,﻿99400575510,Espai Gimnàstic per a Gent Gran *Plaça Alta d...,NaN,NaN,2018-01-25T12:03:45+01:00,2021-03-29T16:44:18.954979+02:00,NaN,NaN,11801,Pl Alta de Can Clos,...,NaN,NaN,NaN,NaN,NaN,NaN,428620.041380,4.579266e+06,41.361736,2.146586
24,﻿99400297206,Àrea Esportiva,9.208603e+10,Platja de la Nova Icària,2012-07-11T00:00:00+02:00,2022-04-29T05:16:58.853299+02:00,NaN,NaN,700757,Pg Marítim de Nova Icària,...,NaN,NaN,NaN,NaN,NaN,NaN,433469.394558,4.582515e+06,41.391413,2.204202
25,﻿99400297248,Àrea Esportiva,9.940025e+10,Jardins d'Enriqueta Sèculi,2012-07-12T00:00:00+02:00,2022-04-29T05:17:01.912996+02:00,NaN,NaN,325800,Ptge Simó,...,NaN,NaN,NaN,NaN,NaN,NaN,430886.896357,4.583983e+06,41.404418,2.173147
26,﻿99400297202,Espai Gimnàstic per a Gent Gran *Perea - Vall ...,NaN,NaN,2012-07-11T10:34:44+02:00,2022-04-29T05:16:59.412688+02:00,NaN,NaN,252455,C Perea,...,NaN,NaN,NaN,NaN,NaN,NaN,428240.588590,4.586212e+06,41.424263,2.141226
27,﻿99400575481,Espai Gimnàstic per a Gent Gran *Plaça Mainada,NaN,NaN,2018-01-25T10:12:38+01:00,2021-03-29T16:44:24.744774+02:00,NaN,NaN,187659,Pl Mainada,...,NaN,NaN,NaN,NaN,NaN,NaN,431787.104272,4.585656e+06,41.419566,2.183727
28,﻿99400575494,Espai Gimnàstic per a Gent Gran,9.933510e+10,Jardins Casa Bloc,2018-01-25T11:13:01+01:00,2021-03-29T16:44:22.748786+02:00,NaN,NaN,350705,C Valentí Iglésias,...,NaN,NaN,NaN,NaN,NaN,NaN,432312.551696,4.588017e+06,41.440870,2.189750
29,﻿99400575512,Espai Gimnàstic per a Gent Gran,9.534511e+10,Jardins Maluquer,2018-01-25T12:12:01+01:00,2021-03-29T16:44:17.858919+02:00,NaN,NaN,190904,Ptge Maluquer,...,NaN,NaN,NaN,NaN,NaN,NaN,427862.739624,4.584504e+06,41.408846,2.136909
30,﻿99400575427,Espai Gimnàstic per a Gent Gran *Espigó del Gas,NaN,NaN,2018-01-24T16:03:59+01:00,2021-03-29T16:44:37.372614+02:00,NaN,NaN,197903,Pg Marítim de la Barceloneta,...,NaN,NaN,NaN,NaN,NaN,NaN,432820.664881,4.581400e+06,41.381317,2.196567
31,﻿99400575438,Espai Gimnàstic per a Gent Gran,9.940030e+10,Jardins Interior d'Illa de Beatriu Pinós-Milany,2018-01-24T00:00:00+01:00,2021-03-29T16:44:41.866361+02:00,NaN,NaN,289105,C Rosselló,...,NaN,NaN,NaN,NaN,NaN,NaN,428989.583145,4.582295e+06,41.389056,2.150648
32,﻿99400575458,Espai Gimnàstic per a Gent Gran *Plaça Palestina,NaN,NaN,2018-01-24T17:46:54+01:00,2021-03-29T16:44:33.171798+02:00,NaN,NaN,326008,C Sinaí,...,NaN,NaN,NaN,NaN,NaN,NaN,428058.832342,4.586268e+06,41.424754,2.139045
33,﻿99400575467,Espai Gimnàstic per a Gent Gran *Pl Carmen La...,NaN,NaN,2018-01-25T09:39:45+01:00,2021-03-29T16:44:28.970086+02:00,NaN,NaN,701719,Pl Carmen Laforet,...,NaN,NaN,NaN,NaN,NaN,NaN,431188.352918,4.586478e+06,41.426916,2.176470
34,﻿99400575496,Espai Gimnàstic per a Gent Gran,9.940020e+10,Jardins de Teresa de Calcuta,2018-01-25T11:17:31+01:00,2021-03-29T16:44:21.449649+02:00,NaN,NaN,17579,Camí Antic de València,...,NaN,NaN,NaN,NaN,NaN,NaN,433287.323004,4.584148e+06,41.406111,2.201844
35,﻿99400575504,Espai Gimnàstic per a Gent Gran *Av Bogatell,NaN,NaN,2018-01-25T11:51:15+01:00,2021-03-29T16:44:19.753398+02:00,NaN,NaN,44200,Av Bogatell,...,NaN,NaN,NaN,NaN,NaN,NaN,432845.259588,4.582699e+06,41.393020,2.196717
36,﻿99400575444,Espai Gimnàstic per a Gent Gran,9.940006e+10,Jardins Interior d'Illa de Flora Tristan,2018-01-24T00:00:00+01:00,2021-03-29T16:44:41.983620+02:00,NaN,NaN,238400,C Padilla,...,NaN,NaN,NaN,NaN,NaN,NaN,431442.559967,4.583942e+06,41.404098,2.179799
37,﻿99400575453,Espai Gimnàstic per a Gent Gran,9.208602e+10,Parc de la Creueta del Coll,2018-01-24T00:00:00+01:00,2021-03-29T16:44:41.573725+02:00,NaN,NaN,230000,Pg Mare de Déu del Coll,...,NaN,NaN,NaN,NaN,NaN,NaN,428655.069685,4.585653e+06,41.419264,2.146252
38,﻿99400575460,Espai Gimnàstic per a Gent Gran *Plaça de les ...,NaN,NaN,2018-01-25T09:14:53+01:00,2021-03-29T16:44:32.108811+02:00,NaN,NaN,169103,C Jorge Manrique,...,NaN,NaN,NaN,NaN,NaN,NaN,428764.690805,4.587094e+06,41.432256,2.147394

### pools.

In [56]:
pool = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\pools.csv")

In [58]:
pool.columns

Index(['register_id', 'name', 'institution_id', 'institution_name', 'created',
       'modified', 'addresses_roadtype_id', 'addresses_roadtype_name',
       'addresses_road_id', 'addresses_road_name',
       'addresses_start_street_number', 'addresses_end_street_number',
       'addresses_neighborhood_id', 'addresses_neighborhood_name',
       'addresses_district_id', 'addresses_district_name',
       'addresses_zip_code', 'addresses_town', 'addresses_main_address',
       'addresses_type', 'values_id', 'values_attribute_id', 'values_category',
       'values_attribute_name', 'values_value', 'values_outstanding',
       'values_description', 'geo_epgs_25831_x', 'geo_epgs_25831_y',
       'geo_epgs_4326_x', 'geo_epgs_4326_y'],
      dtype='object')

### walk circuit

In [59]:
walk = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\walk_run_circuits.csv")

In [60]:
walk

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_attribute_id,values_category,values_attribute_name,values_value,values_outstanding,values_description,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿99400575099,Circuit Esportiu Castell de Montjuïc *circuit 1,NaN,NaN,2018-01-22T14:29:08+01:00,2022-09-17T09:11:21.525001+02:00,NaN,NaN,218504,Ctra Montjuïc,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,430249.880679,4.579578e+06,41.364692,2.166034
1,﻿99400575152,Circuit Esportiu Aragó - Guipúscoa,NaN,NaN,2018-01-22T16:37:27+01:00,2022-09-17T09:11:23.757501+02:00,NaN,NaN,18505,C Aragó,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,432069.459301,4.584447e+06,41.408697,2.187242
2,﻿92086011919,Circuit Esportiu,9.208601e+10,Parc de la Ciutadella,1987-10-22T00:00:00+01:00,2022-09-17T04:18:07.723536+02:00,NaN,NaN,201400,Pg Picasso,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,431929.028956,4.581896e+06,41.385711,2.185848
3,﻿99400099215,Circuit Esportiu Mirador de les Aigües,NaN,NaN,2004-11-09T14:18:07+01:00,2022-09-17T06:20:42.574993+02:00,NaN,NaN,3508,Ctra Aigües,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,424593.457745,4.582871e+06,41.393841,2.098001
4,﻿99400099221,Circuit Esportiu Passeig Marítim,NaN,NaN,2004-11-09T14:28:36+01:00,2022-09-17T06:20:42.351323+02:00,NaN,NaN,700664,C Arquitecte Sert,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,433152.082674,4.582353e+06,41.389928,2.200425
5,﻿1302123624,Circuit de Fitness del Parc del Litoral,NaN,NaN,2001-10-29T00:00:00+01:00,2022-09-17T02:30:33.827154+02:00,NaN,NaN,700768,Pg Marítim de la Mar Bella,...,20001,Telèfons,Tel.,010,True,NaN,434067.446604,4.583238e+06,41.397978,2.211276
6,﻿99400575142,Circuit Esportiu Diagonal - Sant Martí,NaN,NaN,2018-01-22T16:26:54+01:00,2022-09-17T09:11:23.750474+02:00,NaN,NaN,144601,Av Diagonal,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,432206.344860,4.583892e+06,41.403716,2.188941
7,﻿99400109378,Circuit Esportiu,9.208602e+10,Parc del Clot,2005-04-21T17:07:32+02:00,2022-09-17T06:24:13.459864+02:00,NaN,NaN,113506,C Escultors Claperós,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,432301.053530,4.584419e+06,41.408472,2.190015
8,﻿99400099219,Circuit Esportiu Rambla Prim,NaN,NaN,2004-11-09T14:26:33+01:00,2022-09-17T06:20:42.097064+02:00,NaN,NaN,266405,Rbla Prim,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,433188.444047,4.586309e+06,41.425569,2.200423
9,﻿93067092632,Circuit Esportiu Diagonal - Cervantes,NaN,NaN,1993-03-08T00:00:00+01:00,2022-09-17T05:01:08.709765+02:00,NaN,NaN,55807,Pl Francesc Macià,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,428398.478797,4.582734e+06,41.392957,2.143527
10,﻿99400575090,Circuit Esportiu,9.208601e+10,Parc de Joan Miró,2018-01-22T14:14:43+01:00,2022-09-17T09:11:19.038367+02:00,NaN,NaN,362001,C Vilamarí,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,428861.511629,4.581163e+06,41.378847,2.149250
11,﻿99400575122,Circuit Esportiu Castell de Montjuïc *circuit 2,NaN,NaN,2018-01-22T15:26:35+01:00,2022-09-17T09:11:21.040931+02:00,NaN,NaN,218504,Ctra Montjuïc,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,430249.880679,4.579578e+06,41.364692,2.166034
12,﻿99400575130,Circuit Esportiu Can Dragó,NaN,NaN,2018-01-22T15:52:12+01:00,2022-09-17T09:11:22.768035+02:00,NaN,NaN,282650,Av Rio de Janeiro,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,431608.920728,4.587004e+06,41.431695,2.181443

### cinemas.

Teatres                        130
Cinemes                         28
Auditoris                       26
WiFi BCN                         5
Discoteques                      2
Restaurants                      1
Altres esports                   1
Instal·lacions esportives        1
Casals i espais per a joves      1
Name: secondary_filters_name, dtype: int64