# Equipamiento Urbano
## Ayuntamiento de Barcelona

In [1]:
import pandas as pd

## Cultura.
### centros civicos

In [35]:
civic = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\\2021_centres_civics_entitats.csv")

In [36]:
civic.Notes_Dades.isna().sum()

102

In [27]:
civic.drop(columns=["Any", "Ambit", "Notes_Dades", "Notes_Equipament", "TipusEquipament", "TipusGeneral", "Titularitat"], inplace=True)

Cambiar indicador a columna y valores en cada centro civico.

In [39]:
civic.TipusEquipament.value_counts()

Centres cívics    102
Name: TipusEquipament, dtype: int64

In [37]:
civic

,Any,Equipament,Indicador,Valor,Notes_Dades,Notes_Equipament,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Titularitat,TipusGeneral,TipusEquipament,Ambit,Latitud,Longitud
0,2021,Centre Cívic Barceloneta,TotalUsosEntitats,130,NaN,NaN,1,Ciutat Vella,3,la Barceloneta,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.380269,2.192301
1,2021,Centre Cívic Barceloneta,Metres_quadrats,1431,NaN,NaN,1,Ciutat Vella,3,la Barceloneta,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.380269,2.192301
2,2021,Centre Cívic Baró de Viver,TotalUsosEntitats,39,NaN,NaN,9,Sant Andreu,58,Baró de Viver,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.448392,2.199921
3,2021,Centre Cívic Baró de Viver,Metres_quadrats,1535,NaN,NaN,9,Sant Andreu,58,Baró de Viver,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.448392,2.199921
4,2021,Centre Cívic Besòs,TotalUsosEntitats,0,NaN,NaN,10,Sant Martí,70,el Besòs i el Maresme,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.416306,2.211479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,2021,Centre Cívic Zona Nord,Metres_quadrats,2418,NaN,NaN,8,Nou Barris,55,Ciutat Meridiana,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.461114,2.177397
98,2021,Centre Cultural Albareda,TotalUsosEntitats,203,NaN,NaN,3,Sants-Montjuïc,11,el Poble Sec,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.374000,2.173269
99,2021,Centre Cultural Albareda,Metres_quadrats,1473,NaN,NaN,3,Sants-Montjuïc,11,el Poble Sec,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.374000,2.173269
100,2021,Centre Cultural la Farinera del Clot,TotalUsosEntitats,84,NaN,NaN,10,Sant Martí,65,el Clot,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.404914,2.188443
101,2021,Centre Cultural la Farinera del Clot,Metres_quadrats,2634,NaN,NaN,10,Sant Martí,65,el Clot,Municipal,Centres cívics,Centres cívics,Multidisciplinaris i altres,41.404914,2.188443

### Culture_leissure

es un general de toda la cultura de todos los otros df

In [29]:
culture = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\culture_leissure.csv")

In [ ]:
esta todo lo de el data frame de abajo museums y bibliotecs

In [31]:
culture.secondary_filters_name.value_counts()

Àrees de jocs infantils        601
Parcs i jardins                306
Bars i pubs musicals           200
Biblioteques                   186
WiFi BCN                       157
Teatres                        130
Xampanyeries                   126
Cocteleries                    126
Casals d'avis                  114
Sales d'estudi                  95
Discoteques                     78
Museus                          74
Restaurants                     58
Centres cívics                  53
Biblioteques municipals         50
Interiors d'illa                49
Casals i espais per a joves     47
Casals de barri                 40
Casals infantils                29
Cinemes                         28
Auditoris                       26
Museus municipals               21
Bancs del Temps                 18
Arxius municipals               16
Karaokes                        10
Tablaos flamencs                 8
Altres esports                   8
Instal·lacions esportives        8
Salons de ball                   6
Ateneus de fabricació            5
Sales de festes                  4
Universitats                     2
Atletisme en pista               2
Zoo                              1
Tibidabo                         1
Zones de joc                     1
Natació                          1
Bàsquet                          1
Tennis taula                     1
Name: secondary_filters_name, dtype: int64

In [30]:
culture

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿75990035678,Bar musical Flann O'Brien's,NaN,NaN,1996-09-17T00:00:00+02:00,2022-09-17T02:43:55.109244+02:00,NaN,NaN,70607.0,C Casanova,...,NaN,55734068,Bars i pubs musicals,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003000,428724.560600,4.582864e+06,41.394158,2.147412
1,﻿136112242,Centre Cívic Pere Pruna,NaN,NaN,2000-05-15T00:00:00+02:00,2022-12-09T11:43:21.830213+01:00,NaN,NaN,139805.0,Carrer de Ganduxer,...,NaN,55733072,Centres cívics,Planol BCN >> Cultura i lleure >> Espais de pa...,651,65103002002004,427389.377356,4.583883e+06,41.403209,2.131320
2,﻿136112242,Centre Cívic Pere Pruna,NaN,NaN,2000-05-15T00:00:00+02:00,2022-12-09T11:43:21.830213+01:00,NaN,NaN,139805.0,Carrer de Ganduxer,...,NaN,66731068,WiFi BCN,Planol BCN >> Internet >> Punts d'accés a Inte...,651,65103013000000,427389.377356,4.583883e+06,41.403209,2.131320
3,﻿92086034526,Centre Cívic Drassanes,NaN,NaN,1991-03-18T00:00:00+01:00,2022-12-09T15:08:24.769652+01:00,NaN,NaN,86902.0,Carrer Nou de la Rambla,...,NaN,55733072,Centres cívics,Planol BCN >> Cultura i lleure >> Espais de pa...,651,65103002002004,430834.918472,4.581014e+06,41.377678,2.172864
4,﻿92086034526,Centre Cívic Drassanes,NaN,NaN,1991-03-18T00:00:00+01:00,2022-12-09T15:08:24.769652+01:00,NaN,NaN,86902.0,Carrer Nou de la Rambla,...,NaN,66731068,WiFi BCN,Planol BCN >> Internet >> Punts d'accés a Inte...,651,65103013000000,430834.918472,4.581014e+06,41.377678,2.172864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2682,﻿92086011921,Parc de la Ciutadella,NaN,NaN,1988-07-13T00:00:00+02:00,2023-02-16T14:35:02.606418+01:00,NaN,NaN,201400.0,Passeig de Picasso,...,NaN,55737068,Parcs i jardins,Planol BCN >> Cultura i lleure >> Parcs i jard...,651,65103002006000,431890.666013,4.581966e+06,41.386337,2.185382
2683,﻿92086011921,Parc de la Ciutadella,NaN,NaN,1988-07-13T00:00:00+02:00,2023-02-16T14:35:02.606418+01:00,NaN,NaN,201400.0,Passeig de Picasso,...,NaN,66731068,WiFi BCN,Planol BCN >> Internet >> Punts d'accés a Inte...,651,65103013000000,431890.666013,4.581966e+06,41.386337,2.185382
2684,﻿92086009953,CRAI - Biblioteca,9.208601e+10,Facultat de Ciències de la Terra - UB,1990-02-12T00:00:00+01:00,2023-03-06T15:39:22.209534+01:00,NaN,NaN,7258.0,C Martí i Franquès,...,NaN,55731068,Biblioteques,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000000,426346.046950,4.581788e+06,41.384248,2.119094
2685,﻿92086009953,CRAI - Biblioteca,9.208601e+10,Facultat de Ciències de la Terra - UB,1990-02-12T00:00:00+01:00,2023-03-06T15:39:22.209534+01:00,NaN,NaN,7258.0,C Martí i Franquès,...,NaN,55731073,Sales d'estudi,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000005,426346.046950,4.581788e+06,41.384248,2.119094
2686,﻿99400165038,Teatre - Auditori,9.208600e+10,Centre Artesà Tradicionàrius,2006-07-17T08:19:56+02:00,2023-03-06T17:18:36.695246+01:00,NaN,NaN,344407.0,Trvs Sant Antoni,...,NaN,55732068,Teatres,"Planol BCN >> Cultura i lleure >> Cinemes, tea...",651,65103002001000,429344.021386,4.583790e+06,41.402545,2.154713

### restaurants

In [44]:
mus = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\\restaurants.csv")

In [46]:
mus.secondary_filters_name.value_counts()

Restaurants             2494
Cocteleries               35
Xampanyeries              35
Bars i pubs musicals      15
Tablaos flamencs           5
Discoteques                4
Karaokes                   2
Teatres                    1
Name: secondary_filters_name, dtype: int64

In [45]:
mus

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿280131454,Restaurant Els Pollos de Llull *Ramon Turró,NaN,NaN,2000-10-06T00:00:00+02:00,2022-09-17T02:19:30.132030+02:00,NaN,NaN,110009,C Ramon Turró,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,432360.467342,4.582488e+06,41.391080,2.190942
1,﻿99400280889,Restaurant La Royale,NaN,NaN,2011-10-25T11:41:09+02:00,2022-09-17T07:42:47.771616+02:00,NaN,NaN,57303,Pl Camp,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,427782.997527,4.583907e+06,41.403463,2.136026
2,﻿75990055450,Restaurant Ca l'Isidre,NaN,NaN,1996-09-18T00:00:00+02:00,2022-09-17T02:48:41.247894+02:00,NaN,NaN,127409,C Flors,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,430424.917497,4.580829e+06,41.375971,2.167983
3,﻿75990023271,Bar Restaurant Baztan,NaN,NaN,1996-09-17T00:00:00+02:00,2022-09-17T02:40:40.310380+02:00,NaN,NaN,32700,C Balmes,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,429472.232340,4.582835e+06,41.393962,2.156358
4,﻿75990025015,Restaurant Maccabi,NaN,NaN,1996-09-17T00:00:00+02:00,2022-09-17T02:41:11.149492+02:00,NaN,NaN,34308,C Rambla,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,430832.923405,4.581434e+06,41.381461,2.172793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2586,﻿99400611908,Bar Neutral,NaN,NaN,2018-10-29T12:07:05+01:00,2023-03-03T12:45:43.130970+01:00,NaN,NaN,139805,C Ganduxer,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,427984.370806,4.582805e+06,41.393553,2.138566
2587,﻿99400603462,Restaurant Khalijia Shisha,NaN,NaN,2018-07-11T15:40:34+02:00,2023-03-03T12:51:07.540197+01:00,NaN,NaN,247659,Carrer de Pau Claris,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,430657.270000,4.582412e+06,41.390253,2.170580
2588,﻿99400707533,Hamburgueseria Rock & Boom,NaN,NaN,2023-03-03T10:52:56.371181+01:00,2023-03-03T11:02:22.833006+01:00,NaN,NaN,51103,Carrer de Bonavista,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,429764.033000,4.583325e+06,41.398400,2.159791
2589,﻿99400707536,Restaurant Bo de Bernat,NaN,NaN,2023-03-03T11:10:56.787535+01:00,2023-03-03T12:12:13.244490+01:00,NaN,NaN,349706,C Comte d'Urgell,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,429805.294416,4.581339e+06,41.380510,2.160515
2590,﻿99400707540,Bar Restaurant Chamako,NaN,NaN,2023-03-03T11:28:02.562676+01:00,2023-03-03T11:47:09.369707+01:00,NaN,NaN,195500,Carrer de Margarit,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,430052.430000,4.580593e+06,41.373813,2.163556

### Museum libraries. NOT

In [32]:
mus = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\museum_libraries.csv")

In [ ]:
mus.drop(columnns=["register_id", "institution_id", "institution_name", "created", "modified", "addresses_roadtype_id", "addresses_roadtype_name",
                   "addresses_road_id", "values_description", "secondary_filters_id", "secondary_filters_fullpath"])

In [34]:
mus.secondary_filters_name.value_counts()

Biblioteques                 186
Sales d'estudi                95
Museus                        74
Biblioteques municipals       50
Museus municipals             21
Arxius municipals             16
WiFi BCN                      13
Universitats                   2
Parcs i jardins                1
Altres esports                 1
Natació                        1
Instal·lacions esportives      1
Name: secondary_filters_name, dtype: int64

In [33]:
mus

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿92168151705,Biblioteca Joan Miró,NaN,NaN,1992-01-07T00:00:00+01:00,2023-02-16T09:52:27.938933+01:00,NaN,NaN,362001.0,Carrer de Vilamarí,...,NaN,55731068,Biblioteques,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000000,428861.401630,4.581163e+06,41.378848,2.149248
1,﻿92168151705,Biblioteca Joan Miró,NaN,NaN,1992-01-07T00:00:00+01:00,2023-02-16T09:52:27.938933+01:00,NaN,NaN,362001.0,Carrer de Vilamarí,...,NaN,55731070,Biblioteques municipals,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000002,428861.401630,4.581163e+06,41.378848,2.149248
2,﻿92168151705,Biblioteca Joan Miró,NaN,NaN,1992-01-07T00:00:00+01:00,2023-02-16T09:52:27.938933+01:00,NaN,NaN,362001.0,Carrer de Vilamarí,...,NaN,55731073,Sales d'estudi,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000005,428861.401630,4.581163e+06,41.378848,2.149248
3,﻿92163150849,Museu Futbol Club Barcelona President Núñez,9.208600e+10,Futbol Club Barcelona,1992-06-11T00:00:00+02:00,2023-01-24T15:56:27.455451+01:00,NaN,NaN,100708.0,Carrer d'Arístides Maillol,...,NaN,55731069,Museus,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000001,426439.820164,4.581214e+06,41.379091,2.120286
4,﻿99400218118,Museu del Disseny de Barcelona,NaN,NaN,2008-12-01T14:02:22+01:00,2023-02-16T09:52:20.510916+01:00,NaN,NaN,146902.0,Plaça de les Glòries Catalanes,...,NaN,55731069,Museus,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000001,432130.663317,4.583769e+06,41.402601,2.188050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,﻿99400299968,Biblioteca Camp de l'Arpa - Caterina Albert,NaN,NaN,2012-09-06T12:53:28+02:00,2023-02-16T09:52:18.722474+01:00,NaN,NaN,161407.0,Carrer de la Indústria,...,NaN,55731073,Sales d'estudi,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000005,431663.708555,4.585239e+06,41.415797,2.182298
457,﻿99400448268,CRAI - Biblioteca de Fons Antic,NaN,NaN,2016-04-22T13:55:22+02:00,2022-07-11T12:49:09.354783+02:00,NaN,NaN,169409.0,G.V. Corts Catalanes,...,NaN,55731073,Sales d'estudi,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000005,430105.750355,4.582009e+06,41.386577,2.164030
458,﻿99400622824,Sala d'Estudi Montserrat Abelló - Les Corts,9.208600e+10,Biblioteca Montserrat Abelló,2019-03-15T00:00:00+01:00,2022-12-19T15:57:03.833967+01:00,NaN,NaN,88001.0,C Comtes de Bell-lloc,...,NaN,55731073,Sales d'estudi,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000005,427700.946794,4.581717e+06,41.383731,2.135306
459,﻿99400613287,Biblioteca Marta Mata,9.216817e+10,Escola Orlandai,2018-11-16T00:00:00+01:00,2022-09-17T10:56:14.421008+02:00,NaN,NaN,104607.0,C Domínguez i Miralles,...,NaN,55731068,Biblioteques,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000000,426376.633334,4.583247e+06,41.397392,2.119283
460,﻿99400678872,EcoMuseu Urbà Gitano de Barcelona,NaN,NaN,2021-11-04T10:44:54.429325+01:00,2022-01-13T13:40:27.251928+01:00,NaN,NaN,76501.0,Carrer de la Cera,...,NaN,55731069,Museus,Planol BCN >> Cultura i lleure >> Biblioteques...,651,65103002000001,430307.673310,4.581192e+06,41.379232,2.166539

### music and drinks. NOT

In [40]:
drinks = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\music_drinks.csv")

In [42]:
drinks.secondary_filters_name.value_counts()

Bars i pubs musicals         200
Cocteleries                  126
Xampanyeries                 126
Discoteques                   78
Restaurants                   57
Karaokes                      10
Tablaos flamencs               8
Salons de ball                 6
Sales de festes                4
Teatres                        2
Altres esports                 1
Instal·lacions esportives      1
Name: secondary_filters_name, dtype: int64

In [41]:
drinks

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿99400158645,Karaoke Touch Music,NaN,NaN,2006-05-10T13:15:59+02:00,2023-01-20T12:58:44.765310+01:00,NaN,NaN,700661,C Joan Miró,...,NaN,55734072,Karaokes,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003004,432830.727796,4.582360e+06,41.389967,2.196581
1,﻿99400593707,Cocteleria P41 Bar & Coctelarium,7.599027e+10,Hotel Arts Barcelona - HB-003984,2018-06-04T00:00:00+02:00,2021-05-28T14:38:30.930042+02:00,NaN,NaN,197302,C Marina,...,NaN,55734069,Cocteleries,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003001,432827.207894,4.582043e+06,41.387113,2.196574
2,﻿99400593707,Cocteleria P41 Bar & Coctelarium,7.599027e+10,Hotel Arts Barcelona - HB-003984,2018-06-04T00:00:00+02:00,2021-05-28T14:38:30.930042+02:00,NaN,NaN,197302,C Marina,...,NaN,55734076,Xampanyeries,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003008,432827.207894,4.582043e+06,41.387113,2.196574
3,﻿99400632799,Golden Shisha Lounge,NaN,NaN,2019-07-24T11:48:40+02:00,2022-09-17T11:06:08.734790+02:00,NaN,NaN,260158,C Plató,...,NaN,55734070,Discoteques,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003002,428261.859949,4.583557e+06,41.400357,2.141796
4,﻿92086038702,Bar Marsella,NaN,NaN,1992-03-13T00:00:00+01:00,2022-09-17T04:48:47.605726+02:00,NaN,NaN,308505,C Sant Pau,...,NaN,55734068,Bars i pubs musicals,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003000,430698.350786,4.581082e+06,41.378278,2.171224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614,﻿99400706558,Cocteleria Nola,NaN,NaN,2023-02-10T11:49:22.934005+01:00,2023-02-10T11:51:26.335586+01:00,NaN,NaN,318509,Carrer de Santa Teresa,...,NaN,55734069,Cocteleries,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003001,429752.334000,4.583290e+06,41.398079,2.159655
615,﻿99400706558,Cocteleria Nola,NaN,NaN,2023-02-10T11:49:22.934005+01:00,2023-02-10T11:51:26.335586+01:00,NaN,NaN,318509,Carrer de Santa Teresa,...,NaN,55734076,Xampanyeries,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003008,429752.334000,4.583290e+06,41.398079,2.159655
616,﻿99400707531,Bar Soda bus & Verne,NaN,NaN,2023-03-03T10:33:25.814544+01:00,2023-03-03T11:53:10.102699+01:00,NaN,NaN,23403,Carrer d'Aribau,...,NaN,55734069,Cocteleries,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003001,429327.922000,4.582627e+06,41.392070,2.154656
617,﻿99400707531,Bar Soda bus & Verne,NaN,NaN,2023-03-03T10:33:25.814544+01:00,2023-03-03T11:53:10.102699+01:00,NaN,NaN,23403,Carrer d'Aribau,...,NaN,55734076,Xampanyeries,Planol BCN >> Cultura i lleure >> Espais de mú...,651,65103002003008,429327.922000,4.582627e+06,41.392070,2.154656
618,﻿99400707531,Bar Soda bus & Verne,NaN,NaN,2023-03-03T10:33:25.814544+01:00,2023-03-03T11:53:10.102699+01:00,NaN,NaN,23403,Carrer d'Aribau,...,NaN,60731068,Restaurants,Planol BCN >> Restaurants >> Restaurants >> Re...,651,65103007000000,429327.922000,4.582627e+06,41.392070,2.154656

## educacion.
### escuelas

In [47]:
schools = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\equipamiento\education.csv")

In [ ]:
schools.drop(columns=["register_id"])

In [48]:
schools

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿130115232,Fundació Èxit,NaN,NaN,2000-05-09T00:00:00+02:00,2023-03-01T10:06:50.570989+01:00,NaN,NaN,250904.0,C Pelai,...,NaN,NaN,NaN,NaN,NaN,NaN,430450.150032,4.581891e+06,41.385543,2.168163
1,﻿92168166344,Centre Educatiu Valldaura,NaN,NaN,1988-03-01T00:00:00+01:00,2022-09-17T04:55:59.385567+02:00,NaN,NaN,314905.0,C Santa Engràcia,...,NaN,56731069.0,Ensenyament infantil (3-6 anys),Planol BCN >> Educació >> Ensenyament infantil...,651.0,6.510300e+13,431501.870529,4.588177e+06,41.442245,2.180029
2,﻿92168166344,Centre Educatiu Valldaura,NaN,NaN,1988-03-01T00:00:00+01:00,2022-09-17T04:55:59.385567+02:00,NaN,NaN,314905.0,C Santa Engràcia,...,NaN,56732068.0,Educació primària,Planol BCN >> Educació >> Ensenyament reglat >...,651.0,6.510300e+13,431501.870529,4.588177e+06,41.442245,2.180029
3,﻿92168166344,Centre Educatiu Valldaura,NaN,NaN,1988-03-01T00:00:00+01:00,2022-09-17T04:55:59.385567+02:00,NaN,NaN,314905.0,C Santa Engràcia,...,NaN,56732069.0,Educació secundària,Planol BCN >> Educació >> Ensenyament reglat >...,651.0,6.510300e+13,431501.870529,4.588177e+06,41.442245,2.180029
4,﻿75990423787,Institut de Formació i Promoció Laboral Clau d...,NaN,NaN,1997-03-22T00:00:00+01:00,2023-02-28T13:28:04.348629+01:00,NaN,NaN,232902.0,Pl Urquinaona,...,NaN,NaN,NaN,NaN,NaN,NaN,430866.103897,4.582338e+06,41.389606,2.173086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2674,﻿99400707626,Centre de Ioga Blanc Yoga *Les Corts,NaN,NaN,2023-03-06T12:18:24.529097+01:00,2023-03-06T12:19:18.406822+01:00,NaN,NaN,65200.0,Carrer del Cardenal Reig,...,NaN,NaN,NaN,NaN,NaN,NaN,426268.527000,4.581186e+06,41.378815,2.118241
2675,﻿99400604497,Centre de Ioga Blanc Yoga *Eixample,NaN,NaN,2018-07-25T13:12:58+02:00,2023-03-06T12:12:24.845353+01:00,NaN,NaN,54509.0,C Calàbria,...,NaN,NaN,NaN,NaN,NaN,NaN,429418.287215,4.581167e+06,41.378930,2.155907
2676,﻿99400604508,Centre de Ioga Més Millor,NaN,NaN,2018-07-25T13:48:50+02:00,2023-03-06T12:16:49.001160+01:00,NaN,NaN,121402.0,C Felip II,...,NaN,NaN,NaN,NaN,NaN,NaN,432349.414859,4.585423e+06,41.417516,2.190482
2677,﻿99400604498,Centre de Ioga Yoga Ecuanime,NaN,NaN,2018-07-25T13:15:59+02:00,2023-03-06T12:14:57.706275+01:00,NaN,NaN,227800.0,C Nicaragua,...,NaN,NaN,NaN,NaN,NaN,NaN,427812.188636,4.582076e+06,41.386971,2.136593
2678,﻿92168165429,Llar d'Infants Kasperle,NaN,NaN,1988-11-18T00:00:00+01:00,2023-03-06T14:20:25.817621+01:00,NaN,NaN,206403.0,C Gran de Gràcia,...,NaN,56731068.0,Ensenyament infantil (0-3 anys),Planol BCN >> Educació >> Ensenyament infantil...,651.0,6.510300e+13,429288.844959,4.583612e+06,41.400944,2.154074

### hospitals

In [50]:
hospitals = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\equipamiento\hospitals.csv")

In [51]:
hospitals

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿92086002898,Hospital El Pilar - Institut Cardiovascular Sa...,NaN,NaN,1985-04-25T00:00:00+02:00,2022-09-17T03:52:23.259292+02:00,NaN,NaN,32700,C Balmes,...,24 hores,61731068,Hospitals i clíniques,Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000000,428822.422501,4.583563e+06,41.400457,2.148500
1,﻿94040143759,Centre d'Atenció Primària Vallvidrera,NaN,NaN,1994-02-09T00:00:00+01:00,2022-05-31T13:04:21.817257+02:00,NaN,NaN,280803,Carrer d'Elisa Moragas i Badia,...,NaN,61731069,CAPs,Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000001,425131.616000,4.585084e+06,41.413818,2.104164
2,﻿99400012795,Centre d'Atenció Primària Turó,NaN,NaN,2002-07-17T11:52:41+02:00,2022-11-08T12:54:35.275149+01:00,NaN,NaN,54000,C Cadí,...,NaN,61731069,CAPs,Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000001,430702.695491,4.587167e+06,41.433082,2.170579
3,﻿94286182144,Centre d'Atenció Primària El Clot,NaN,NaN,1994-10-13T00:00:00+01:00,2023-02-22T13:18:12.329033+01:00,NaN,NaN,86200,C Concili de Trento,...,NaN,61731069,CAPs,Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000001,432558.041961,4.584783e+06,41.411767,2.193049
4,﻿99400279672,Clínica Sant Antoni,NaN,NaN,2011-10-06T11:34:12+02:00,2022-09-17T07:42:27.836805+02:00,NaN,NaN,299608,C Sant Eloi,...,NaN,61731068,Hospitals i clíniques,Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000000,428338.514252,4.578640e+06,41.356077,2.143294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,﻿99400284987,Centre d'Urgències d'Atenció Primària Horta,NaN,NaN,2012-01-18T11:13:24+01:00,2023-02-22T15:48:09.521530+01:00,NaN,NaN,301801,C Sant Gaudenci,...,NaN,61731070,Centres urgències (CUAPs),Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000002,429606.009091,4.587373e+06,41.434841,2.157430
138,﻿99400344819,Centre d'Atenció Primària Casernes,9.940031e+10,Centre de Salut Isabel Roig-Casernes de Sant A...,2014-06-12T00:00:00+02:00,2022-11-08T12:56:41.746381+01:00,NaN,NaN,701334,C Fernando Pessoa,...,NaN,61731069,CAPs,Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000001,432572.900119,4.588269e+06,41.443165,2.192838
139,﻿99400699333,Clínica Oftalvist,NaN,NaN,2022-10-10T12:47:48.921822+02:00,2022-10-10T12:47:55.666152+02:00,NaN,NaN,16907,Carrer d'Anglí,...,NaN,61731068,Hospitals i clíniques,Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000000,426868.041000,4.583650e+06,41.401070,2.125112
140,﻿99400706702,Centre Mèdic Vilasalut *Barcelona,NaN,NaN,2023-02-13T16:53:43.480283+01:00,2023-02-13T16:55:20.415030+01:00,NaN,NaN,292303,Sagrat Cor,...,NaN,61731068,Hospitals i clíniques,Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000000,426417.637869,4.583552e+06,41.400146,2.119736
141,﻿99400706694,Clínica Cipsalut,NaN,NaN,2023-02-13T16:31:42.481624+01:00,2023-02-13T16:31:44.065817+01:00,NaN,NaN,100800,Carrer de la Diputació,...,NaN,61731068,Hospitals i clíniques,Planol BCN >> Sanitat >> Hospitals i Centres d...,651,65103008000000,429385.723000,4.581490e+06,41.381837,2.155480

### play-ground

In [52]:
play = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\equipamiento\school_playground.csv")

In [53]:
play

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿99400472916,Patis escolars oberts al barri - Escola Mossèn...,NaN,NaN,2016-12-22T08:31:59+01:00,2023-01-17T10:19:46.339609+01:00,NaN,NaN,178400,C Lleida,...,NaN,NaN,NaN,NaN,NaN,NaN,429321.678285,4.580545e+06,41.373321,2.154824
1,﻿99400630189,Patis escolars oberts al barri - Institut Mené...,NaN,NaN,2019-06-20T13:49:59+02:00,2022-09-28T13:27:59.321841+02:00,NaN,NaN,28000,Via Augusta,...,NaN,NaN,NaN,NaN,NaN,NaN,428513.769509,4.583523e+06,41.400074,2.144813
2,﻿99400691081,Patis escolars oberts al barri - Escola Bresso...,NaN,NaN,2022-04-22T13:56:57.914659+02:00,2023-02-15T14:58:48.733685+01:00,NaN,NaN,65403,C Cardenal Tedeschini,...,NaN,NaN,NaN,NaN,NaN,NaN,431797.990031,4.586326e+06,41.425601,2.183782
3,﻿99400705006,Patis escolars oberts al barri- Institut Vapor...,NaN,NaN,2023-01-16T14:13:09.710406+01:00,2023-01-16T14:14:30.096779+01:00,NaN,NaN,322007,Carrer del Segre,...,NaN,NaN,NaN,NaN,NaN,NaN,432522.402163,4.587212e+06,41.433645,2.192352
4,﻿99400704985,Patis escolars oberts al barri - Escola Bresso...,NaN,NaN,2023-01-16T12:53:50.601353+01:00,2023-02-15T14:58:48.549768+01:00,NaN,NaN,215109,C Mònec,...,NaN,NaN,NaN,NaN,NaN,NaN,431291.136797,4.582183e+06,41.388241,2.178187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,﻿99400705008,Patis escolars oberts al barri- Escola El Sagrer,NaN,NaN,2023-01-16T14:16:32.193362+01:00,2023-01-16T14:17:43.006954+01:00,NaN,NaN,93103,C Costa Rica,...,NaN,NaN,NaN,NaN,NaN,NaN,432278.778444,4.585924e+06,41.422019,2.189580
81,﻿99400704992,Patis escolars oberts al barri - Escola Bresso...,NaN,NaN,2023-01-16T13:19:24.403097+01:00,2023-02-15T14:58:48.096097+01:00,NaN,NaN,276704,C Rectoria,...,NaN,NaN,NaN,NaN,NaN,NaN,429933.769928,4.587288e+06,41.434102,2.161363
82,﻿99400704994,Patis escolars oberts al barri - Escola Bresso...,NaN,NaN,2023-01-16T13:26:33.184892+01:00,2023-02-15T14:58:47.922349+01:00,NaN,NaN,700026,C Augusto César Sandino,...,NaN,NaN,NaN,NaN,NaN,NaN,433337.174796,4.587804e+06,41.439046,2.202038
83,﻿99400704997,Patis escolars oberts al barri - Escola Bresso...,NaN,NaN,2023-01-16T13:30:41.157537+01:00,2023-02-15T14:58:47.642733+01:00,NaN,NaN,266405,Rbla Prim,...,NaN,NaN,NaN,NaN,NaN,NaN,433266.977797,4.586189e+06,41.424488,2.201376
84,﻿99400705818,Patis escolars oberts al barri - Escola Montseny,NaN,NaN,2023-01-27T08:07:10.878881+01:00,2023-01-27T08:08:54.247722+01:00,NaN,NaN,340905,C Torrent del Remei,...,NaN,NaN,NaN,NaN,NaN,NaN,428816.369204,4.585246e+06,41.415613,2.148230

## SPORT
### excersice

In [54]:
exc = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\excersice.csv")

In [55]:
exc

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_description,secondary_filters_id,secondary_filters_name,secondary_filters_fullpath,secondary_filters_tree,secondary_filters_asia_id,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿99400297249,Àrea Esportiva,9.208603e+10,Parc de la Unitat,2012-07-12T00:00:00+02:00,2022-04-29T05:17:01.869892+02:00,NaN,NaN,186204,C Lloret de Mar,...,NaN,NaN,NaN,NaN,NaN,NaN,429640.510723,4.587535e+06,41.436303,2.157824
1,﻿99400297250,Àrea Esportiva *Pardo - Can Ros - Concepció Ar...,NaN,NaN,2012-07-12T10:07:27+02:00,2022-04-29T05:17:02.261529+02:00,NaN,NaN,160608,C Can Ros,...,NaN,NaN,NaN,NaN,NaN,NaN,431757.033399,4.586473e+06,41.426917,2.183275
2,﻿99400297205,Àrea Esportiva,9.216814e+10,Platja del Bogatell,2012-07-11T00:00:00+02:00,2022-04-29T05:16:58.852421+02:00,NaN,NaN,700756,Pg Marítim del Bogatell,...,NaN,NaN,NaN,NaN,NaN,NaN,433686.031383,4.582867e+06,41.394603,2.206754
3,﻿99400575466,Espai Gimnàstic per a Gent Gran *Pujalt,NaN,NaN,2018-01-25T09:35:53+01:00,2021-03-29T16:44:30.185453+02:00,NaN,NaN,271201,C Pujalt,...,NaN,NaN,NaN,NaN,NaN,NaN,431742.476730,4.590471e+06,41.462926,2.182649
4,﻿99400575501,Espai Gimnàstic per a Gent Gran *Jocs Esportiu...,NaN,NaN,2018-01-25T11:36:04+01:00,2021-03-29T16:44:20.955412+02:00,NaN,NaN,270901,C Pujades,...,NaN,NaN,NaN,NaN,NaN,NaN,434180.367237,4.584614e+06,41.410381,2.212477
5,﻿99400575506,Espai Gimnàstic per a Gent Gran,9.511411e+10,Jardins Ca l'Alena,2018-01-25T11:54:09+01:00,2021-03-29T16:44:20.371997+02:00,NaN,NaN,230601,C Mare de Déu de Port,...,NaN,NaN,NaN,NaN,NaN,NaN,428302.699521,4.579010e+06,41.359406,2.142822
6,﻿99400575508,Espai Gimnàstic per a Gent Gran *Plaça Navas,NaN,NaN,2018-01-25T11:59:51+01:00,2021-03-29T16:44:18.773153+02:00,NaN,NaN,226309,Pl Las Navas,...,NaN,NaN,NaN,NaN,NaN,NaN,429710.700485,4.580624e+06,41.374069,2.159467
7,﻿99400575430,Espai Gimnàstic per a Gent Gran,9.626914e+10,Parc de la Barceloneta,2018-01-24T16:08:15+01:00,2021-03-29T16:44:37.543462+02:00,NaN,NaN,197903,Pg Marítim de la Barceloneta,...,NaN,NaN,NaN,NaN,NaN,NaN,432593.428278,4.581484e+06,41.382060,2.193840
8,﻿99400575450,Espai Gimnàstic per a Gent Gran,9.911213e+10,Jardins d'Antoni Puigvert,2018-01-24T00:00:00+01:00,2023-01-31T14:46:26.758045+01:00,NaN,NaN,325005,Carrer de Sicília,...,NaN,NaN,NaN,NaN,NaN,NaN,430564.884000,4.584006e+06,41.404604,2.169292
9,﻿99400575454,Espai Gimnàstic per a Gent Gran *Parc Sanitar...,NaN,NaN,2018-01-24T17:28:07+01:00,2021-03-29T16:44:35.641213+02:00,NaN,NaN,116901,C Esteve Terradas,...,NaN,NaN,NaN,NaN,NaN,NaN,428150.072689,4.585179e+06,41.414955,2.140266
10,﻿99400575456,Espai Gimnàstic per a Gent Gran,9.510913e+10,Jardins del Baix Guinardó,2018-01-24T17:36:00+01:00,2021-03-29T16:44:34.768564+02:00,NaN,NaN,197302,C Marina,...,NaN,NaN,NaN,NaN,NaN,NaN,430441.603559,4.584582e+06,41.409781,2.167751
11,﻿99400575462,Espai Gimnàstic per a Gent Gran,9.940007e+10,Jardins de Josep Munté,2018-01-25T09:20:26+01:00,2021-03-29T16:44:30.951676+02:00,NaN,NaN,65200,C Cardenal Reig,...,NaN,NaN,NaN,NaN,NaN,NaN,426160.278885,4.581203e+06,41.378964,2.116944
12,﻿99400575421,Espai Gimnàstic per a Gent Gran *Arc de Teatre,NaN,NaN,2018-01-24T15:50:29+01:00,2021-03-29T16:44:38.161012+02:00,NaN,NaN,21306,C Arc del Teatre,...,NaN,NaN,NaN,NaN,NaN,NaN,430939.380467,4.580962e+06,41.377218,2.174119
13,﻿99400575457,Espai Gimnàstic per a Gent Gran,9.940032e+10,Parc de les Rieres d'Horta,2018-01-24T17:39:48+01:00,2021-03-29T16:44:34.137146+02:00,NaN,NaN,700651,Av Estatut de Catalunya,...,NaN,NaN,NaN,NaN,NaN,NaN,429259.595481,4.587240e+06,41.433612,2.153300
14,﻿99400575465,Espai Gimnàstic per a Gent Gran *Zona Esporti...,NaN,NaN,2018-01-25T09:32:53+01:00,2021-03-29T16:44:30.852890+02:00,NaN,NaN,275600,Av Rasos de Peguera,...,NaN,NaN,NaN,NaN,NaN,NaN,431105.634980,4.590101e+06,41.459543,2.175067
15,﻿99400575474,Espai Gimnàstic per a Gent Gran,9.940058e+10,Jardins Can Xiringoi,2018-01-25T00:00:00+01:00,2021-03-29T16:44:32.568929+02:00,NaN,NaN,8603,C Costa i Cuxart,...,NaN,NaN,NaN,NaN,NaN,NaN,431126.427501,4.586567e+06,41.427716,2.175718
16,﻿99400297246,Espai Gimnàstic per a Gent Gran,9.940023e+10,Jardins Interior d'Illa Càndida Pérez,2012-07-12T00:00:00+02:00,2022-04-29T05:16:59.863216+02:00,NaN,NaN,87009,C Comte Borrell,...,NaN,NaN,NaN,NaN,NaN,NaN,430025.474340,4.581026e+06,41.377713,2.163184
17,﻿99400297199,Espai Gimnàstic per a Gent Gran * Conca de Tre...,NaN,NaN,2012-07-11T10:07:40+02:00,2022-04-29T05:16:59.420679+02:00,NaN,NaN,85900,C Conca de Tremp,...,NaN,NaN,NaN,NaN,NaN,NaN,429366.462663,4.586196e+06,41.424218,2.154701
18,﻿99400172076,Espai Gimnàstic per a Gent Gran,9.822518e+10,Jardins de Vil·la Cecília,2006-11-17T13:49:40+01:00,2021-03-29T17:00:29.070262+02:00,NaN,NaN,107300,C Eduardo Conde,...,NaN,NaN,NaN,NaN,NaN,NaN,426531.902910,4.582858e+06,41.393906,2.121187
19,﻿99400575437,Espai Gimnàstic per a Gent Gran *Pl del Mar,NaN,NaN,2018-01-24T16:18:45+01:00,2021-03-29T16:44:36.153999+02:00,NaN,NaN,700911,Pl Mar,...,NaN,NaN,NaN,NaN,NaN,NaN,432130.607914,4.580516e+06,41.373300,2.188414
20,﻿99400575478,Espai Gimnàstic per a Gent Gran,9.208601e+10,Parc del Turó de la Peira,2018-01-25T09:58:23+01:00,2021-03-29T16:44:26.323576+02:00,NaN,NaN,119003,Pg Fabra i Puig,...,NaN,NaN,NaN,NaN,NaN,NaN,430108.064252,4.587215e+06,41.433467,2.163457
21,﻿99400575480,Espai Gimnàstic per a Gent Gran *Via Favència ...,NaN,NaN,2018-01-25T10:05:14+01:00,2021-03-29T16:44:24.967110+02:00,NaN,NaN,34400,Via Bàrcino,...,NaN,NaN,NaN,NaN,NaN,NaN,432505.582664,4.588809e+06,41.448025,2.191972
22,﻿99400575491,Espai Gimnàstic per a Gent Gran *Pl Assemblea...,NaN,NaN,2018-01-25T11:09:37+01:00,2021-03-29T16:44:23.085239+02:00,NaN,NaN,17604,C Antilles,...,NaN,NaN,NaN,NaN,NaN,NaN,432161.043674,4.586248e+06,41.424931,2.188135
23,﻿99400575510,Espai Gimnàstic per a Gent Gran *Plaça Alta d...,NaN,NaN,2018-01-25T12:03:45+01:00,2021-03-29T16:44:18.954979+02:00,NaN,NaN,11801,Pl Alta de Can Clos,...,NaN,NaN,NaN,NaN,NaN,NaN,428620.041380,4.579266e+06,41.361736,2.146586
24,﻿99400297206,Àrea Esportiva,9.208603e+10,Platja de la Nova Icària,2012-07-11T00:00:00+02:00,2022-04-29T05:16:58.853299+02:00,NaN,NaN,700757,Pg Marítim de Nova Icària,...,NaN,NaN,NaN,NaN,NaN,NaN,433469.394558,4.582515e+06,41.391413,2.204202
25,﻿99400297248,Àrea Esportiva,9.940025e+10,Jardins d'Enriqueta Sèculi,2012-07-12T00:00:00+02:00,2022-04-29T05:17:01.912996+02:00,NaN,NaN,325800,Ptge Simó,...,NaN,NaN,NaN,NaN,NaN,NaN,430886.896357,4.583983e+06,41.404418,2.173147
26,﻿99400297202,Espai Gimnàstic per a Gent Gran *Perea - Vall ...,NaN,NaN,2012-07-11T10:34:44+02:00,2022-04-29T05:16:59.412688+02:00,NaN,NaN,252455,C Perea,...,NaN,NaN,NaN,NaN,NaN,NaN,428240.588590,4.586212e+06,41.424263,2.141226
27,﻿99400575481,Espai Gimnàstic per a Gent Gran *Plaça Mainada,NaN,NaN,2018-01-25T10:12:38+01:00,2021-03-29T16:44:24.744774+02:00,NaN,NaN,187659,Pl Mainada,...,NaN,NaN,NaN,NaN,NaN,NaN,431787.104272,4.585656e+06,41.419566,2.183727
28,﻿99400575494,Espai Gimnàstic per a Gent Gran,9.933510e+10,Jardins Casa Bloc,2018-01-25T11:13:01+01:00,2021-03-29T16:44:22.748786+02:00,NaN,NaN,350705,C Valentí Iglésias,...,NaN,NaN,NaN,NaN,NaN,NaN,432312.551696,4.588017e+06,41.440870,2.189750
29,﻿99400575512,Espai Gimnàstic per a Gent Gran,9.534511e+10,Jardins Maluquer,2018-01-25T12:12:01+01:00,2021-03-29T16:44:17.858919+02:00,NaN,NaN,190904,Ptge Maluquer,...,NaN,NaN,NaN,NaN,NaN,NaN,427862.739624,4.584504e+06,41.408846,2.136909
30,﻿99400575427,Espai Gimnàstic per a Gent Gran *Espigó del Gas,NaN,NaN,2018-01-24T16:03:59+01:00,2021-03-29T16:44:37.372614+02:00,NaN,NaN,197903,Pg Marítim de la Barceloneta,...,NaN,NaN,NaN,NaN,NaN,NaN,432820.664881,4.581400e+06,41.381317,2.196567
31,﻿99400575438,Espai Gimnàstic per a Gent Gran,9.940030e+10,Jardins Interior d'Illa de Beatriu Pinós-Milany,2018-01-24T00:00:00+01:00,2021-03-29T16:44:41.866361+02:00,NaN,NaN,289105,C Rosselló,...,NaN,NaN,NaN,NaN,NaN,NaN,428989.583145,4.582295e+06,41.389056,2.150648
32,﻿99400575458,Espai Gimnàstic per a Gent Gran *Plaça Palestina,NaN,NaN,2018-01-24T17:46:54+01:00,2021-03-29T16:44:33.171798+02:00,NaN,NaN,326008,C Sinaí,...,NaN,NaN,NaN,NaN,NaN,NaN,428058.832342,4.586268e+06,41.424754,2.139045
33,﻿99400575467,Espai Gimnàstic per a Gent Gran *Pl Carmen La...,NaN,NaN,2018-01-25T09:39:45+01:00,2021-03-29T16:44:28.970086+02:00,NaN,NaN,701719,Pl Carmen Laforet,...,NaN,NaN,NaN,NaN,NaN,NaN,431188.352918,4.586478e+06,41.426916,2.176470
34,﻿99400575496,Espai Gimnàstic per a Gent Gran,9.940020e+10,Jardins de Teresa de Calcuta,2018-01-25T11:17:31+01:00,2021-03-29T16:44:21.449649+02:00,NaN,NaN,17579,Camí Antic de València,...,NaN,NaN,NaN,NaN,NaN,NaN,433287.323004,4.584148e+06,41.406111,2.201844
35,﻿99400575504,Espai Gimnàstic per a Gent Gran *Av Bogatell,NaN,NaN,2018-01-25T11:51:15+01:00,2021-03-29T16:44:19.753398+02:00,NaN,NaN,44200,Av Bogatell,...,NaN,NaN,NaN,NaN,NaN,NaN,432845.259588,4.582699e+06,41.393020,2.196717
36,﻿99400575444,Espai Gimnàstic per a Gent Gran,9.940006e+10,Jardins Interior d'Illa de Flora Tristan,2018-01-24T00:00:00+01:00,2021-03-29T16:44:41.983620+02:00,NaN,NaN,238400,C Padilla,...,NaN,NaN,NaN,NaN,NaN,NaN,431442.559967,4.583942e+06,41.404098,2.179799
37,﻿99400575453,Espai Gimnàstic per a Gent Gran,9.208602e+10,Parc de la Creueta del Coll,2018-01-24T00:00:00+01:00,2021-03-29T16:44:41.573725+02:00,NaN,NaN,230000,Pg Mare de Déu del Coll,...,NaN,NaN,NaN,NaN,NaN,NaN,428655.069685,4.585653e+06,41.419264,2.146252
38,﻿99400575460,Espai Gimnàstic per a Gent Gran *Plaça de les ...,NaN,NaN,2018-01-25T09:14:53+01:00,2021-03-29T16:44:32.108811+02:00,NaN,NaN,169103,C Jorge Manrique,...,NaN,NaN,NaN,NaN,NaN,NaN,428764.690805,4.587094e+06,41.432256,2.147394

### pools.

In [56]:
pool = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\pools.csv")

In [58]:
pool.columns

Index(['register_id', 'name', 'institution_id', 'institution_name', 'created',
       'modified', 'addresses_roadtype_id', 'addresses_roadtype_name',
       'addresses_road_id', 'addresses_road_name',
       'addresses_start_street_number', 'addresses_end_street_number',
       'addresses_neighborhood_id', 'addresses_neighborhood_name',
       'addresses_district_id', 'addresses_district_name',
       'addresses_zip_code', 'addresses_town', 'addresses_main_address',
       'addresses_type', 'values_id', 'values_attribute_id', 'values_category',
       'values_attribute_name', 'values_value', 'values_outstanding',
       'values_description', 'geo_epgs_25831_x', 'geo_epgs_25831_y',
       'geo_epgs_4326_x', 'geo_epgs_4326_y'],
      dtype='object')

### walk circuit

In [59]:
walk = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\walk_run_circuits.csv")

In [60]:
walk

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_attribute_id,values_category,values_attribute_name,values_value,values_outstanding,values_description,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿99400575099,Circuit Esportiu Castell de Montjuïc *circuit 1,NaN,NaN,2018-01-22T14:29:08+01:00,2022-09-17T09:11:21.525001+02:00,NaN,NaN,218504,Ctra Montjuïc,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,430249.880679,4.579578e+06,41.364692,2.166034
1,﻿99400575152,Circuit Esportiu Aragó - Guipúscoa,NaN,NaN,2018-01-22T16:37:27+01:00,2022-09-17T09:11:23.757501+02:00,NaN,NaN,18505,C Aragó,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,432069.459301,4.584447e+06,41.408697,2.187242
2,﻿92086011919,Circuit Esportiu,9.208601e+10,Parc de la Ciutadella,1987-10-22T00:00:00+01:00,2022-09-17T04:18:07.723536+02:00,NaN,NaN,201400,Pg Picasso,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,431929.028956,4.581896e+06,41.385711,2.185848
3,﻿99400099215,Circuit Esportiu Mirador de les Aigües,NaN,NaN,2004-11-09T14:18:07+01:00,2022-09-17T06:20:42.574993+02:00,NaN,NaN,3508,Ctra Aigües,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,424593.457745,4.582871e+06,41.393841,2.098001
4,﻿99400099221,Circuit Esportiu Passeig Marítim,NaN,NaN,2004-11-09T14:28:36+01:00,2022-09-17T06:20:42.351323+02:00,NaN,NaN,700664,C Arquitecte Sert,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,433152.082674,4.582353e+06,41.389928,2.200425
5,﻿1302123624,Circuit de Fitness del Parc del Litoral,NaN,NaN,2001-10-29T00:00:00+01:00,2022-09-17T02:30:33.827154+02:00,NaN,NaN,700768,Pg Marítim de la Mar Bella,...,20001,Telèfons,Tel.,010,True,NaN,434067.446604,4.583238e+06,41.397978,2.211276
6,﻿99400575142,Circuit Esportiu Diagonal - Sant Martí,NaN,NaN,2018-01-22T16:26:54+01:00,2022-09-17T09:11:23.750474+02:00,NaN,NaN,144601,Av Diagonal,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,432206.344860,4.583892e+06,41.403716,2.188941
7,﻿99400109378,Circuit Esportiu,9.208602e+10,Parc del Clot,2005-04-21T17:07:32+02:00,2022-09-17T06:24:13.459864+02:00,NaN,NaN,113506,C Escultors Claperós,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,432301.053530,4.584419e+06,41.408472,2.190015
8,﻿99400099219,Circuit Esportiu Rambla Prim,NaN,NaN,2004-11-09T14:26:33+01:00,2022-09-17T06:20:42.097064+02:00,NaN,NaN,266405,Rbla Prim,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,433188.444047,4.586309e+06,41.425569,2.200423
9,﻿93067092632,Circuit Esportiu Diagonal - Cervantes,NaN,NaN,1993-03-08T00:00:00+01:00,2022-09-17T05:01:08.709765+02:00,NaN,NaN,55807,Pl Francesc Macià,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,428398.478797,4.582734e+06,41.392957,2.143527
10,﻿99400575090,Circuit Esportiu,9.208601e+10,Parc de Joan Miró,2018-01-22T14:14:43+01:00,2022-09-17T09:11:19.038367+02:00,NaN,NaN,362001,C Vilamarí,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,428861.511629,4.581163e+06,41.378847,2.149250
11,﻿99400575122,Circuit Esportiu Castell de Montjuïc *circuit 2,NaN,NaN,2018-01-22T15:26:35+01:00,2022-09-17T09:11:21.040931+02:00,NaN,NaN,218504,Ctra Montjuïc,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,430249.880679,4.579578e+06,41.364692,2.166034
12,﻿99400575130,Circuit Esportiu Can Dragó,NaN,NaN,2018-01-22T15:52:12+01:00,2022-09-17T09:11:22.768035+02:00,NaN,NaN,282650,Av Rio de Janeiro,...,100003,Informació d'interès,Web,http://www.bcn.cat/trobatb/ca/circuits-esporti...,True,NaN,431608.920728,4.587004e+06,41.431695,2.181443