# Estadistic and difusion.

In [79]:
from bs4 import BeautifulSoup 
import pandas as pd
import requests
import re
import src.inmobi as im 
import importlib
importlib.reload(im)

## Vivienda.

#### Alquiler. Mercado contractual de alquiler en Barcelona por barrios. 2022.

Alquiler medio mensual ($/mes)

In [80]:
price_housing = 'https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Habitatge_i_mercat_immobiliari/Mercat_immobiliari/Habitatges_lloguer/a2022/tbarris1.htm'

In [81]:
df = im.scraping_prices (price_housing)
df.sample()

   Distrito        Barrio 1er trimestre 2do trimestre 3er trimestre
67       10   el Poblenou         967,9       1.085,6       1.104,2

## Indice socioeconomico.
#### Indice socioeconomico territorial (IST). 2015-2019

promedio del valor socioeconomico. no tiene num valor.

In [82]:
sociecon = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Condicions_de_vida/Index_socioeconomic/f01.htm"

In [83]:
df = im.scraping_sociecon (sociecon)
df.sample()

   Distrito       Barrio   2015   2016   2017   2018   2019
15       31   la Bordeta  107,1  107,7  107,7  108,2  107,1

## Seguridad.

### Denuncias policia Urbana.

#### sistema de seguridad publica.
Indicadores por distritos. 2020

In [84]:
seguridad = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Guardia_urbana/t67.htm"

In [85]:
df = im.seguridad (seguridad)
df.sample()

,Distrito,Denuncias por infracción de la ordenanza de convivencia ciudadana (% habitantes),Incidentes pordegradación del espacio público (‰ habitantes),Incidentes en laconvivenciavecinal (‰ habitantes),Incidentes por actividadesmolestas en el espaciopúblico (‰ habitantes),Incidentes por actividadesindebidas en el espaciopúblico (‰ habitantes)
0,Ciutat Vella,"17,16","3,24","73,64","78,57","16,90"

#### Actuaciones de ayuda y asistencia por distritos.

In [86]:
ayuda = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Guardia_urbana/t37.htm"

1. posiblemente eliminar las incidencias que no tienen mucho que ver con la seguridad como las ayudas por accidentes con el clima etc. 
2. crear un total de las incidencias ya limpias por distrito
3. separar por tipo de incidencias.

In [87]:
df = im.pol_urbana_ayuda (ayuda)
df.sample()

,Incidencias,Barcelona,1.Ciutat Vella,2.L'Eixample,3.Sants-Monjuïc,4.Les Corts,5.Sarrià-Sant Gervasi,6.Gràcia,7.Horta-Guiardó,8.Nou Barris,9.Sant Andreu,10.Sant Martí
72,Infracciones de extranjeros,29,10,7,1,2,0,2,0,0,0,6

#### Circulacion vehicular.

Denuncias policia de circulacion por distrits.

In [88]:
circulacion = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Guardia_urbana/t17.htm"

In [89]:
df = im.circulacion(circulacion)
df.sample()

,Incidencias,Barcelona,1.Ciutat Vella,2.L'Eixample,3.Sants-Monjuïc,4.Les Corts,5.Sarrià-Sant Gervasi,6.Gràcia,7.Horta-Guiardó,8.Nou Barris,9.Sant Andreu,10.Sant Martí
12,Ordenanza zona de bajas emisiones,33,1,5,4,0,3,5,2,6,0,6