# Estadistic and difusion.

In [6]:
from bs4 import BeautifulSoup 
import pandas as pd
import requests
import re
import src.inmobi as im 
import importlib
importlib.reload(im)

### Vivienda.

#### Mercado contractual de alquiler en Barcelona por barrios. 2022.

Alquiler medio mensual ($/mes)

In [23]:
price_housing = 'https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Habitatge_i_mercat_immobiliari/Mercat_immobiliari/Habitatges_lloguer/a2022/tbarris1.htm'

In [89]:

html = requests.get(price_housing)
soup = BeautifulSoup(html.content, "html.parser")
table = soup.find_all("table")[0]
tags = table.find_all("tr")
# select only texts and clean it.
rows = [i.text.strip().replace("\xa0", "").split("\n") for i in tags]
rowse = rows[10:-6]
    # transform to df.
df = pd.DataFrame(rowse)
    # clean first column names and drop not necesary columns, change the names of columns.

In [90]:
df["Barrio"] = df[0].apply(lambda x: x.split(".")[1])

In [91]:
df["Distrito"] = df[0].apply(lambda x: x.split(".")[0])

In [93]:
for i in df["Distrito"]:
    if len(str(i)) == 2:
        df["Distrito"][i] = i[0]
    if len(str(i)) == 4:
        df["Distrito"][i] = i[:2]

In [87]:
for i in df["Distrito"]:
        print(i[:2])

11
12
13
14
25
26
27
28
29
21
31
31
31
31
31
31
31
31
41
42
42
52
52
52
52
52
52
62
62
63
63
63
73
73
73
73
73
73
73
74
74
74
74
84
84
84
84
84
84
85
85
85
85
85
85
85
95
95
95
96
96
96
96
10
10
10
10
10
10
10
10
10
10

In [94]:
df["Distrito"]

0       11
1       12
2       13
3       14
4       25
      ...
68    1069
69    1070
70    1071
71    1072
72    1073
Name: Distrito, Length: 73, dtype: object

In [16]:
df["Distrito"] = df["Distrito"].apply(lambda x: x.split())

In [17]:
df

,0,1,2,3,4,5,6,7,8,Barrio,Distrito
0,11. el Raval,"917,0","872,0","928,1",,,"917,0","894,6","905,4",el Raval,[11]
1,12. el Barri Gňtic,"1.181,6","1.062,5","1.111,3",,,"1.181,6","1.127,0","1.122,6",el Barri Gňtic,[12]
2,13. la Barceloneta,"999,8","900,5","922,9",,,"999,8","949,6","940,3",la Barceloneta,[13]
3,"14. Sant Pere, Santa Caterina i la Ribera","1.022,8","1.051,4","1.084,9",,,"1.022,8","1.035,7","1.051,1","Sant Pere, Santa Caterina i la Ribera",[14]
4,25. el Fort Pienc,"957,9","1.106,9","1.118,7",,,"957,9","1.030,6","1.057,0",el Fort Pienc,[25]
...,...,...,...,...,...,...,...,...,...,...,...
68,1069. Diagonal Mar i el Front Marítim del Pobl...,"964,7","1.238,7","1.354,9",,,"964,7","1.082,7","1.159,2",Diagonal Mar i el Front Marítim del Poblenou,[1069]
69,1070. el Besňs i el Maresme,"796,9","779,2","761,4",,,"796,9","787,6","778,2",el Besňs i el Maresme,[1070]
70,1071. Provençals del Poblenou,"939,2","1.032,9","1.059,4",,,"939,2","984,0","1.009,2",Provençals del Poblenou,[1071]
71,1072. Sant Martí de Provençals,"796,4","843,0","1.158,9",,,"796,4","821,0","984,4",Sant Martí de Provençals,[1072]
72,1073. la Verneda i la Pau,"733,9","757,0","775,8",,,"733,9","745,4","754,5",la Verneda i la Pau,[1073]

In [ ]:
    df.drop(columns=[4, 5, 6, 7, 8], inplace=True)
    df.rename(columns={0:"barrio", 1:"1er trimestre", 2:"2do trimestre", 3:"3er trimestre"}, inplace=True)
    return df

In [8]:
df = im.scraping_prices (price_housing)
df

,barrio,1er trimestre,2do trimestre,3er trimestre
0,el Raval,"917,0","872,0","928,1"
1,el Barri Gňtic,"1.181,6","1.062,5","1.111,3"
2,la Barceloneta,"999,8","900,5","922,9"
3,"Sant Pere, Santa Caterina i la Ribera","1.022,8","1.051,4","1.084,9"
4,el Fort Pienc,"957,9","1.106,9","1.118,7"
...,...,...,...,...
68,Diagonal Mar i el Front Marítim del Poblenou,"964,7","1.238,7","1.354,9"
69,el Besňs i el Maresme,"796,9","779,2","761,4"
70,Provençals del Poblenou,"939,2","1.032,9","1.059,4"
71,Sant Martí de Provençals,"796,4","843,0","1.158,9"
72,la Verneda i la Pau,"733,9","757,0","775,8"

### Indice socioeconomico.
#### Indice socioeconomico territorial (IST). 2015-2019

In [8]:
sociecon = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Condicions_de_vida/Index_socioeconomic/f01.htm"

In [9]:
df = im.scraping_sociecon (sociecon)
df

,barrio,2015,2016,2017,2018,2019
0,el Raval,"72,1","73,1","74,0","76,0","77,4"
1,el Barri Gňtic,"96,7","96,9","95,0","90,9","83,9"
2,la Barceloneta,"93,3","95,1","95,1","95,4","95,6"
3,"Sant Pere, Santa Caterina i la Ribera","98,8","99,6","99,7","100,6","101,3"
4,el Fort Pienc,"113,7","114,0","112,9","113,2","112,2"
...,...,...,...,...,...,...
67,el Poblenou,"112,2","113,0","113,1","114,0","114,0"
68,Diagonal Mar i el Front Marítim del Poblenou,"118,8","119,1","118,3","117,1","116,4"
69,el Besňs i el Maresme,"78,0","78,5","78,5","77,3","75,2"
70,Provençals del Poblenou,"107,5","107,6","107,7","107,9","107,6"
71,Sant Martí de Provençals,"104,3","104,7","103,9","104,3","103,5"