# Mobilidad.

### Bicing.

In [132]:
import pandas as pd
import json
from pandas import json_normalize

import src.mobilidad as mo
import importlib
importlib.reload(mo)

In [59]:
bici = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\bicing\\2019BICING_ESTACIONS.csv")

In [60]:
x = mo.bici_(bici)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\mobilidad.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\mobilidad.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [61]:
x

                              address bikes category   latitude  longitude
0        Gran Via Corts Catalanes 760    16   bicing  41.397952   2.180042
1         Roger de Flor/ Gran Vía 126    18   bicing  41.395530   2.177060
2                           Nàpols 82    22   bicing  41.394055   2.181299
3                            Ribes 13    21   bicing  41.393480   2.181555
4                Pg Lluís Companys 11    39   bicing  41.391075   2.180223
...                               ...   ...      ...        ...        ...
1450786    (PK) C/ DE L´ABAT SAFONT 2     7   bicing  41.375244   2.169795
1454027    (PK) C/ DE L´ABAT SAFONT 2     8   bicing  41.375244   2.169795
1532556             PL. DE TETUAN 8-9     4   bicing  41.394232   2.175278
1538049                    Girona 142    20   bicing  41.398013   2.166978
1545080                Escornalbou 51   nan   bicing  41.418088   2.176313

[11022 rows x 5 columns]

### Bicipuertos.

In [133]:
with open("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\bicing\\bicipuertos.json") as f:
    puertos = json.load(f)

In [134]:
puertos = mo.bicipuertos (puertos)

In [135]:
puertos

,address,district_id,district,barri_id,barri,category,latitude,longitude
0,"MARINA, C., DE LA 309",02,Eixample,06,la Sagrada Familia,puerto_bici,41.377359,2.147228
1,"MARINA, C., DE LA 293",02,Eixample,06,la Sagrada Familia,puerto_bici,41.377359,2.147228
2,"MARINA, C., DE LA 311",02,Eixample,06,la Sagrada Familia,puerto_bici,41.377359,2.147228
3,"MARINA, C., DE LA 325",02,Eixample,06,la Sagrada Familia,puerto_bici,41.377359,2.147228
4,"LLANÇA, C., DE 23",02,Eixample,09,la Nova Esquerra de l'Eixample,puerto_bici,41.377359,2.147228
...,...,...,...,...,...,...,...,...
3922,"ENRIC GRANADOS, C., D' 95",02,Eixample,08,l'Antiga Esquerra de l'Eixample,puerto_bici,41.377359,2.147228
3923,"PROVENÇA, C., DE 80",02,Eixample,09,la Nova Esquerra de l'Eixample,puerto_bici,41.377359,2.147228
3924,"VILLARROEL, C., DE 136",02,Eixample,08,l'Antiga Esquerra de l'Eixample,puerto_bici,41.377359,2.147228
3925,"MALLORCA, C., DE 41",02,Eixample,09,la Nova Esquerra de l'Eixample,puerto_bici,41.377359,2.147228
3926,"TARRAGONA, C., DE 74",02,Eixample,09,la Nova Esquerra de l'Eixample,puerto_bici,41.377359,2.147228

### Buses.

In [90]:
bus = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\transporte_publico\ESTACIONS_BUS.csv")

In [92]:
bus.drop(columns=["CODI_CAPA", "CAPA_GENERICA", "ED50_COORD_X", "ED50_COORD_Y", "ETRS89_COORD_X", "ETRS89_COORD_Y", "ADRECA", "TELEFON"],inplace=True)

In [93]:
bus

,NOM_CAPA,LONGITUD,LATITUD,EQUIPAMENT,DISTRICTE,BARRI,NOM_DISTRICTE,NOM_BARRI
0,Autobusos diürns,2.103856,41.391488,BUS -113--,4,21,Les Corts,Pedralbes
1,Autobusos diürns,2.131320,41.428067,BUS -112--,7,39,Horta-Guinardó,Sant Genís dels Agudells
2,Autobusos diürns,2.144370,41.392286,BUS -101--,2,8,Eixample,l'Antiga Esquerra de l'Eixample
3,Autobusos diürns,2.145249,41.392108,BUS -100--,2,8,Eixample,l'Antiga Esquerra de l'Eixample
4,Autobusos diürns,2.105336,41.414554,BUS -111--,5,22,Sarrià-Sant Gervasi,"Vallvidrera, el Tibidabo i les Planes"
...,...,...,...,...,...,...,...,...
3219,Autobusos nocturns,2.177544,41.376464,NITBUS -N9--,1,2,Ciutat Vella,el Barri Gòtic
3220,Autobusos diürns,2.180320,41.398770,BUS -6-7-H12--,2,5,Eixample,el Fort Pienc
3221,Autobusos nocturns,2.187571,41.393615,NITBUS -N11--,10,66,Sant Martí,el Parc i la Llacuna del Poblenou
3222,Autobusos diürns,2.182826,41.391889,BUS -B25-B20--,2,5,Eixample,el Fort Pienc
3223,Autobusos diürns,2.177111,41.424273,BUS -19-47-V25-D50--,7,35,Horta-Guinardó,el Guinardó

### Transportes.

In [94]:
tran = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\transporte_publico\TRANSPORTS.csv")

In [96]:
tran.drop(columns=["CODI_CAPA", "CAPA_GENERICA", "ED50_COORD_X", "ED50_COORD_Y", "ETRS89_COORD_X", "ETRS89_COORD_Y", "ADRECA", "TELEFON"],inplace=True)

In [97]:
tran

,NOM_CAPA,LONGITUD,LATITUD,EQUIPAMENT,DISTRICTE,BARRI,NOM_DISTRICTE,NOM_BARRI
0,Tren a l'aeroport,2.189397,41.410259,Tren AEROPORT - CLOT-,10.0,65.0,Sant Martí,el Clot
1,Ferrocarrils Generalitat (FGC),2.135427,41.397791,FGC - BONANOVA-,5.0,26.0,Sarrià-Sant Gervasi,Sant Gervasi - Galvany
2,Ferrocarrils Generalitat (FGC),2.139248,41.405731,FGC - EL PUTXET-,5.0,27.0,Sarrià-Sant Gervasi,el Putxet i el Farró
3,Metro i línies urbanes FGC,2.187234,41.409376,Clot (Aragó / Meridiana)-,10.0,65.0,Sant Martí,el Clot
4,Metro i línies urbanes FGC,2.183681,41.430013,Fabra i Puig (Avinguda Meridiana)-,9.0,60.0,Sant Andreu,Sant Andreu
...,...,...,...,...,...,...,...,...
679,Metro i línies urbanes FGC,2.091533,41.366599,METRO (L5) - Can Boixeres-,NaN,NaN,NaN,NaN
680,Metro i línies urbanes FGC,2.173644,41.403863,METRO (L5) - Sagrada Família-,2.0,6.0,Eixample,la Sagrada Família
681,Ferrocarrils Generalitat (FGC),2.139256,41.406043,FGC - EL PUTXET-,5.0,27.0,Sarrià-Sant Gervasi,el Putxet i el Farró
682,Estació marítima,2.175174,41.368076,Terminal Marítima Sant Bertran *Ferris-,3.0,12.0,Sants-Montjuïc,la Marina del Prat Vermell
683,Estació marítima,2.174790,41.350989,Terminal Marítima D *Creuers-,3.0,12.0,Sants-Montjuïc,la Marina del Prat Vermell

In [98]:
tran = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\TAULA_MAP_ILLA.csv")

In [99]:
tran

,DISTRICTE,CODI_ILLA,SECC_CENS,BARRI,NOM_DISTRICTE,NOM_BARRI,AEB,HABITANTS,NUM_PARC,NUM_LOCALS,NUM_VIVENDES,NUM_PARKINGS,NUM_ALTRES,SUP_CONS,SUP_SOBRE_RASANT,SUP_SOTA_RASANT,SUP_LOCALS,SUP_SERVEIS,SUP_SOL,DATA_DADES
0,1,5071,001,01,Ciutat Vella,el Raval,001,1,4,96,1,3,89,202635,94173,108462,NaN,NaN,114001,03/03/2023 00:02:11
1,1,6041,036,03,Ciutat Vella,la Barceloneta,014,0,1,0,0,0,0,0,0,0,NaN,NaN,8360,03/03/2023 00:02:11
2,1,6044,036,03,Ciutat Vella,la Barceloneta,014,0,1,0,0,0,0,0,0,0,NaN,NaN,4843,03/03/2023 00:02:11
3,1,6054,036,03,Ciutat Vella,la Barceloneta,014,0,3,3,0,0,3,3711,0,3711,NaN,NaN,62393,03/03/2023 00:02:11
4,1,6055,036,03,Ciutat Vella,la Barceloneta,014,2,4,698,60,563,75,94304,54222,40082,NaN,NaN,13401,03/03/2023 00:02:11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5294,10,92498,138,73,Sant Martí,la Verneda i la Pau,232,268,3,189,126,40,4,11250,10250,1000,NaN,NaN,2003,03/03/2023 00:02:11
5295,10,92499,138,73,Sant Martí,la Verneda i la Pau,232,389,17,195,175,0,20,9838,9838,0,NaN,NaN,2013,03/03/2023 00:02:11
5296,10,92504,138,73,Sant Martí,la Verneda i la Pau,232,223,7,133,90,0,43,6470,6470,0,NaN,NaN,2013,03/03/2023 00:02:11
5297,10,92513,138,73,Sant Martí,la Verneda i la Pau,232,272,7,165,138,0,27,10161,10161,0,NaN,NaN,2015,03/03/2023 00:02:11
5298,10,92520,139,73,Sant Martí,la Verneda i la Pau,232,1718,21,855,766,0,89,55924,55217,707,NaN,NaN,6895,03/03/2023 00:02:11