# Environment
## Ayuntamiento de Barcelona

In [212]:
import plotly.express as px
import geopandas as gpd
import shapely.geometry
import numpy as np
import wget
import fiona
import folium

In [218]:
import pandas as pd
import plotly.graph_objects as go

In [378]:
import src.ecology as eco
import src.equipamiento as eq
import importlib
importlib.reload(eco)

### Calidad de aire.

In [172]:
# df de estaciones.
aire = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\\2022_qualitat_aire_estacions.csv")

In [173]:
distr = eco.limpia_estacions_aire(aire)

In [174]:
# df de los contaminantes y su id.
contami = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\contaminants.csv")

In [175]:
contami = eco.limpia_contaminants (contami)

sacar el mean por dia, evaluar el tipo de contaminante por el codigo= buscarlo en el el df de los contaminantes
conectar el data frame con el de arriba el completo para aberiguar la calidad por barrio con el codigo de la estacio. 
if estacio = entonces...

In [176]:
marzo_2023 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\Qualitat_Aire_Detall.csv")

In [177]:
marzo_2023 = eco.aire_monthly (marzo_2023, contami, distr)

In [178]:
# Febrero 2023
feb_2023 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2023_02_Febrer_qualitat_aire_BCN.csv")

In [179]:
feb_2023 = eco.aire_monthly (feb_2023, contami, distr)

In [180]:
# Enero 2023
ene_2023 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2023_01_Gener_qualitat_aire_BCN.csv")

In [181]:
ene_2023 = eco.aire_monthly (ene_2023, contami, distr)

In [182]:
# Dic 2022
dic_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_12_Desembre_qualitat_aire_BCN.csv")

In [183]:
dic_2022 = eco.aire_monthly (dic_2022, contami, distr)

In [185]:
# Nov 2022
nov_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_11_Novembre_qualitat_aire_BCN.csv")

In [186]:
nov_2022 = eco.aire_monthly (nov_2022, contami, distr)

In [187]:
# Octubre 2023
oct_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_10_Octubre_qualitat_aire_BCN.csv")

In [188]:
oct_2022 = eco.aire_monthly (oct_2022, contami, distr)

In [189]:
# septiembre 2022
sep_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_09_Setembre_qualitat_aire_BCN.csv")

In [190]:
sep_2022 = eco.aire_monthly (sep_2022, contami, distr)

In [191]:
# Agosto 2022
ago_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_08_Agost_qualitat_aire_BCN.csv")

In [192]:
ago_2022 = eco.aire_monthly (ago_2022, contami, distr)

In [193]:
# Jul 2022
jul_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_07_Juliol_qualitat_aire_BCN.csv")

In [194]:
jul_2022 = eco.aire_monthly (jul_2022, contami, distr)

In [195]:
# Junio 2022
jun_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_06_Juny_qualitat_aire_BCN.csv")

In [196]:
jun_2022 = eco.aire_monthly (jun_2022, contami, distr)

In [197]:
# Mayo 2022
may_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_05_Maig_qualitat_aire_BCN.csv")

In [198]:
may_2022 = eco.aire_monthly (may_2022, contami, distr)

In [199]:
# Abril 2022
abr_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_04_Abril_qualitat_aire_BCN.csv")

In [200]:
abr_2022 = eco.aire_monthly (abr_2022, contami, distr)

In [220]:
# Marzo 2022
mar_2022 = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\calidad de aire\per_mes\\2022_03_Marc_qualitat_aire_BCN.csv")

In [222]:
mar_2022 = eco.aire_monthly (mar_2022, contami, distr)

KeyError: "['PROVINCIA', 'CODI_PROVINCIA', 'CODI_MUNICIPI', 'MUNICIPI'] not found in axis"

### capacidad acustica

###### De 55 a 75 dB

###### Es un nivel de ruido considerable. Por ejemplo, un aspirador genera 65 dB. Una calle con mucho tráfico alcanza los 75 dB. El despertador o la televisión a un volumen elevado, pueden llegar a los 75 dB, igual que una lavadora, el teléfono móvil o una batidora.

###### De 75 dB a 100 dB

###### Es un nivel alto de ruido, la sensación es molesta. Por ejemplo, en un atasco hay 90 dB de ruido. También el que suele emitir una sirena de policía.

TOTAL_D        Ruido total en periodo dia
FFCC_E         Ruido de ejes ferroviarios y tranvía en período tarde
PATIS_D        Ruido en patios interiores en período día
OCI_N          Ruido de ocio y aglomeración de personas en período noche
VIANANTS_E     Ruido en calles peatonales en período tarde
VIANANTS_D     Ruido en calles peatonales en período día
INDUST_DEN     Ruido de industria en período Lden
INDUST_N       Ruido de industria en período noche
INDUST_E       Ruido de industria en período tarde
INDUST_D       Ruido de industria en período día
FFCC_DEN       Ruido de ejes ferroviarios y tranvía en período Lden
FFCC_N         Ruido de ejes ferroviarios y tranvía en período noche 
FFCC_D         Ruido de ejes ferroviarios y tranvía en período día
TOTAL_E        Ruido total en periodo tarde
GI_TR_DEN      Ruido de grandes infraestructuras viarias en período Lden 
GI_TR_N        Ruido de grandes infraestructuras viarias en período noche
GI_TR_E        Ruido de grandes infraestructuras viarias en período tarde
GI_TR_D        Ruido de grandes infraestructuras viarias en período día
TRANSIT_DEN    Ruido de tráfico viario en período Lden
TRANSIT_N      Ruido de tráfico viario en período noche
TRANSIT_E      Ruido de tráfico viario en período tarde
TRANSIT_D      Ruido de trafico viario en periodo dia
TOTAL_DEN      Ruido total en período Lden
TOTAL_N        ruido total en periodo noche
PATIS_E        Ruido en patios interiores en período tarde

In [323]:
soroll = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\capacidad acustica\\2017_barris_soroll_bcn_long.csv")

In [326]:
x = eco.soroll_barris(soroll)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["codi_districte", "codi_barri", "time"], inplace=True)

In [327]:
x

     nom_districte                barri     sound  valor
2190  Ciutat Vella             el Raval    <40 dB   0.27
2191  Ciutat Vella             el Raval  40-45 dB  28.36
2192  Ciutat Vella             el Raval  45-50 dB  11.97
2193  Ciutat Vella             el Raval  50-55 dB   7.95
2194  Ciutat Vella             el Raval  55-60 dB  15.40
...            ...                  ...       ...    ...
2915    Sant Martí  la Verneda i la Pau  60-65 dB  21.59
2916    Sant Martí  la Verneda i la Pau  65-70 dB  13.08
2917    Sant Martí  la Verneda i la Pau  70-75 dB   4.05
2918    Sant Martí  la Verneda i la Pau  75-80 dB   0.00
2919    Sant Martí  la Verneda i la Pau   >=80 dB   0.00

[730 rows x 4 columns]

### Green points

delete non necesary.

In [328]:
y = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\puntos_ecologicos.csv")

In [331]:
green = eq.clean_equipamientos (y)

In [334]:
green

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Punt Verd Mòbil *Mercat Bon Pastor,59,el Bon Pastor,9,Sant Andreu,Punts verds mòbils,41.436470,2.206245,C Sant Adrià 137
1,Punt Verd de Barri - Mercat de Sant Antoni,10,Sant Antoni,2,Eixample,Punts verds de barri,41.379065,2.161312,C Tamarit 169
2,Punt Verd Mòbil *Diagonal Mar,70,el Besòs i el Maresme,10,Sant Martí,Punts verds mòbils,41.410748,2.215235,C Llull 379
3,Punt Verd Mòbil *Passeig Sant Joan-Indústria,32,el Camp d'en Grassot i Gràcia Nova,6,Gràcia,Punts verds mòbils,41.402804,2.164687,Pg Sant Joan 169
4,Punt Verd Mòbil *Numància-Nau Santa Maria,19,les Corts,4,Les Corts,Punts verds mòbils,41.390934,2.131934,C Numància 180
...,...,...,...,...,...,...,...,...,...
606,Contenidor Roba Amiga * Via Júlia,51,Verdun,8,Nou Barris,Punts de roba amiga,41.441832,2.177335,Via Júlia 95
607,Contenidor Roba Amiga * Mercat de La Marina,13,la Marina de Port,3,Sants-Montjuïc,Punts de roba amiga,41.360349,2.139175,Passeig de la Zona Franca 178
608,Contenidor Roba Amiga * Punt Verd de Barri Sarrià,23,Sarrià,5,Sarrià-Sant Gervasi,Punts de roba amiga,41.397280,2.126532,Carrer del Cardenal Sentmenat 6
609,Contenidor de Sal *Torrent Font Mont - C. Font...,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,Contenidors de sal,41.413893,2.111225,Carrer de la Font del Mont 1
610,Contenidor de Sal * Escola Bressol La Puput,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,Contenidors de sal,41.415350,2.102357,Carrer d'Elisa Moragas i Badia 29

do sub queries to select just the necesary.

In [335]:
green["category"].value_counts()

Punts de recollida d'arbres de Nadal    226
Punts de roba amiga                     123
Contenidors de sal                      113
Punts verds mòbils                       97
Punts verds de barri                     27
Horts urbans                             15
Punts verds de zona                       7
Punts verds col·laboradors                1
Name: category, dtype: int64

### Jardin interiors.

In [373]:
interior = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\jardin_interiors.csv")

In [375]:
interior = eco.jardin_interior (interior)

In [376]:
interior.sample()

,name,barri_id,barri,district_id,district,latitude,longitude,address,category
23,Jardins de la Torre de Les Aigües *Temporalmen...,7,la Dreta de l'Eixample,2,Eixample,41.393091,2.169153,Carrer de Roger de Llúria 56,jardin_interior

### refugis.

In [389]:
refugi = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\refugi.csv")

refiguios tipo escuelas, parques, lugares tipo asilos bibliotecas, de espacios publicos.

In [392]:
refugi = eco.refugi (refugi)

In [393]:
refugi.sample()

,name,barri_id,barri,district_id,district,latitude,longitude,address,category
97,Parc del Guinardó,35,el Guinardó,7,Horta-Guinardó,41.419489,2.169614,Garriga i Roca 1,refugis

### Arbolado.

In [445]:
viari = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\arbrat\OD_Arbrat_Viari_BCN.csv")

In [446]:
viari = eco.arbolado(viari)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [447]:
viari

,taxon_name,common_name,barri_id,barri,district_id,district,category,address,latitud,longitud
0,Fraxinus angustifolia 'Raywood',-,48.0,la guineueta,8,nou barris,ARBRE VIARI,"Pg Fabra i Puig, 450",41.437287,2.165353
1,Fraxinus angustifolia 'Raywood',-,48.0,la guineueta,8,nou barris,ARBRE VIARI,"Pg Fabra i Puig, 450",41.437335,2.165436
2,Platanus x hispanica,Plátano,43.0,horta,7,horta - guinardó,ARBRE VIARI,"Doctor Letamendi, 90",41.437769,2.162530
3,Platanus x hispanica,Plátano,43.0,horta,7,horta - guinardó,ARBRE VIARI,"Doctor Letamendi, 90",41.437788,2.162501
4,Platanus x hispanica,Plátano,43.0,horta,7,horta - guinardó,ARBRE VIARI,"Doctor Letamendi, 90",41.437810,2.162471
...,...,...,...,...,...,...,...,...,...,...
153827,Melia azedarach,Melia; cinamomo,61.0,la sagrera,9,sant andreu,ARBRE VIARI,"Josep Estivill, 65",41.419993,2.190518
153828,Melia azedarach,Melia; cinamomo,61.0,la sagrera,9,sant andreu,ARBRE VIARI,"Ptge Bofarull, 2",41.420038,2.190579
153829,Melia azedarach,Melia; cinamomo,61.0,la sagrera,9,sant andreu,ARBRE VIARI,"Gran de la Sagrera, 12",41.419800,2.191147
153830,Melia azedarach,Melia; cinamomo,61.0,la sagrera,9,sant andreu,ARBRE VIARI,"Gran de la Sagrera, 12",41.419979,2.191137
153831,Celtis australis,Almez,61.0,la sagrera,9,sant andreu,ARBRE VIARI,"Gran de la Sagrera, 49",41.419716,2.191138

### arbrat parcs

located in the squares, flower beds, gazebos or small garden spaces

In [449]:
parcs = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\arbrat\OD_Arbrat_Parcs_BCN.csv")

In [450]:
parcs = eco.arbolado(parcs)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [451]:
parcs

,taxon_name,common_name,barri_id,barri,district_id,district,category,address,latitud,longitud
0,Populus nigra 'Italica',Chopo lombardo,48,la guineueta,8,nou barris,ARBRE PARC,"Pg Fabra i Puig, 450",41.437250,2.165295
1,Populus nigra 'Italica',Chopo lombardo,48,la guineueta,8,nou barris,ARBRE PARC,"Pg Fabra i Puig, 450",41.437318,2.165410
2,Populus nigra 'Italica',Chopo lombardo,48,la guineueta,8,nou barris,ARBRE PARC,"Pg Fabra i Puig, 450",41.437365,2.165494
3,Populus nigra 'Italica',Chopo lombardo,48,la guineueta,8,nou barris,ARBRE PARC,"Pg Fabra i Puig, 450",41.437380,2.165520
4,Populus nigra 'Italica',Chopo lombardo,48,la guineueta,8,nou barris,ARBRE PARC,"Pg Fabra i Puig, 450",41.437396,2.165552
...,...,...,...,...,...,...,...,...,...,...
35914,Ceratonia siliqua,Algarrobo,35,el guinardó,7,horta - guinardó,ARBRE PARC,"Jard Doctor Pla i Armengol, 0",41.416140,2.171525
35918,Morus australis 'Fruitless',-,69,diagonal mar i el front marítim del poblenou,10,sant martí,ARBRE PARC,"Parc Diagonal Mar, 0",41.407496,2.211734
35919,Cercis siliquastrum,Árbol del amor; Árbol de Judas,3,la barceloneta,1,ciutat vella,ARBRE PARC,"Parc Cascades, 0",41.386634,2.194469
35920,Cercis siliquastrum,Árbol del amor; Árbol de Judas,3,la barceloneta,1,ciutat vella,ARBRE PARC,"Parc Cascades, 0",41.386735,2.194602
35921,Cercis siliquastrum,Árbol del amor; Árbol de Judas,3,la barceloneta,1,ciutat vella,ARBRE PARC,"Parc Cascades, 0",41.386809,2.194705

### Arbrat Zona

In [452]:
zona = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\arbolado\\arbrat\OD_Arbrat_Zona_BCN.csv")

In [453]:
zona = eco.arbolado(zona)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\src\ecology.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [454]:
zona

,taxon_name,common_name,barri_id,barri,district_id,district,category,address,latitud,longitud
0,Chamaerops humilis,Palmito,48.0,la guineueta,8,nou barris,PALMERA ZONA,"Pg Fabra i Puig, 449",41.438986,2.165807
1,Yucca gigantea,Yuca pie de elefante,48.0,la guineueta,8,nou barris,PALMERA ZONA,"Pg Fabra i Puig, 441",41.438498,2.165526
2,Yucca gigantea,Yuca pie de elefante,48.0,la guineueta,8,nou barris,PALMERA ZONA,"Pg Fabra i Puig, 441",41.438452,2.165488
3,Chamaerops humilis,Palmito,48.0,la guineueta,8,nou barris,PALMERA ZONA,"Vilalba dels Arcs, 94",41.437955,2.165747
4,Tipuana tipu,Palo rosa; tipa blanca,47.0,can peguera,8,nou barris,ARBRE ZONA,"Pg Urrutia, 70",41.435473,2.167947
...,...,...,...,...,...,...,...,...,...,...
43387,Morus alba,Morera blanca; morera,49.0,canyelles,8,nou barris,ARBRE ZONA,"Antonio Machado, 41",41.444615,2.169950
43388,Laurus nobilis,Laurel,49.0,canyelles,8,nou barris,ARBRE ZONA,"Antonio Machado, 41",41.444505,2.169958
43389,Eriobotrya japonica,Níspero del Japón,49.0,canyelles,8,nou barris,ARBRE ZONA,"Antonio Machado, 41",41.444404,2.170030
43390,Morus alba,Morera blanca; morera,49.0,canyelles,8,nou barris,ARBRE ZONA,"Antonio Machado, 41",41.444641,2.169839
43391,Tipuana tipu,Palo rosa; tipa blanca,61.0,la sagrera,9,sant andreu,ARBRE ZONA,"Felip II, 20",41.417767,2.190962