# Equipamiento Urbano
## Ayuntamiento de Barcelona

In [159]:
import pandas as pd
import importlib

import sys 
sys.path.append("..\src")
#from analysis import *
import equipamiento as eq
importlib.reload(eq)

## Cultura.
### centros civicos

In [160]:
civic = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\\2021_centres_civics_entitats.csv")

In [161]:
civic = eq.civic_ (civic)

In [162]:
civic.sample()

,name,district_id,district,barri_id,barri,latitud,longitud,total_usos_entitats,metres_quadrats,division,category
36,Centre Cívic Sagrada Família,2,Eixample,6,la Sagrada Família,41.40538,2.17676,33,1900,equipamiento,centro_civic

In [163]:
civic.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\equipamiento\centre_civic.csv", index=False)

### restaurants

In [164]:
rest = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\\restaurants.csv")

In [165]:
rest = eq.clean_cult_ocio (rest)

In [166]:
rest.sample()

,name,barri_id,barri,district_id,district,category,latitud,longitud,address,division
265,Restaurant Fan Dim Sum,26,Sant Gervasi - Galvany,5,Sarrià-Sant Gervasi,Restaurants,41.395641,2.143782,Carrer de Laforja 128,cultura/ocio

In [167]:
rest.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\cult_ocio\\restaurants.csv", index=False)

### Museum libraries.

In [168]:
mus = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\museum_libraries.csv")

In [169]:
mus = eq.clean_equipamientos (mus) ### cultura y ocio

In [170]:
mus = eq.clean_ids (mus)

In [171]:
mus.sample()

,name,barri_id,barri,district_id,district,category,latitud,longitud,address,division
183,Biblioteca Canyelles,49,Canyelles,8,Nou Barris,Sales d'estudi,41.443804,2.16434,Ronda de la Guineueta Vella 34,equipamiento

In [172]:
mus.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\cult_ocio\\museums_libraries.csv", index=False)

### music and drinks.

In [173]:
drinks = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\music_drinks.csv")

In [174]:
drinks = eq.clean_equipamientos (drinks) #### cultura y ocio

In [175]:
drinks.sample()

,name,barri_id,barri,district_id,district,category,latitud,longitud,address,division
517,Cocteleria Bloody Mary,31,la Vila de Gràcia,6,Gràcia,Xampanyeries,41.398381,2.159227,C Ferrer de Blanes 3,equipamiento

In [176]:
drinks.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\cult_ocio\\music_drinks.csv", index=False)

### cines

In [177]:
cine = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\cinema.csv")

In [178]:
cine = eq.clean_equipamientos (cine) ### cultura y ocio

In [179]:
cine.sample()

,name,barri_id,barri,district_id,district,category,latitud,longitud,address,division
150,Teatre Sala Pangolí,32,el Camp d'en Grassot i Gràcia Nova,6,Gràcia,Teatres,41.401562,2.164714,C Bailèn 194,equipamiento

In [180]:
cine.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\cult_ocio\\cinemas.csv", index=False)

## educacion.
### escuelas

In [181]:
schools = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\equipamiento\education.csv")

In [182]:
schools = eq.clean_equipamientos (schools) ##### equipamiento

In [183]:
schools = eq.clean_ids (schools)

In [184]:
schools.sample()

,name,barri_id,barri,district_id,district,category,latitud,longitud,address,division
2587,Llar d'Infants Somriures,12,la Marina del Prat Vermell,3,Sants-Montjuïc,Ensenyament infantil (0-3 anys),41.329023,2.112505,Carrer Transversal 14 11,equipamiento

In [185]:
schools.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\equipamiento\\schools.csv", index=False)

### hospitals

In [186]:
hospitals = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\equipamiento\hospitals.csv")

In [187]:
hospitals = eq.clean_equipamientos (hospitals) ### equipamiento

In [188]:
hospitals.sample()

,name,barri_id,barri,district_id,district,category,latitud,longitud,address,division
52,Centre d'Atenció Primària Roger de Flor,7,la Dreta de l'Eixample,2,Eixample,CAPs,41.398895,2.172748,C Roger de Flor 194,equipamiento

In [189]:
hospitals.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\equipamiento\\hospitals.csv", index=False)

## SPORT
### excersice

In [190]:
exc = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\excersice.csv")

In [191]:
exc = eq.clean_excersice (exc)

In [192]:
exc.sample()

,name,barri_id,barri,district_id,district,category,latitud,longitud,address,division
2,Àrea Esportiva,68,el Poblenou,10,Sant Martí,excersice,41.394603,2.206754,Pg Marítim del Bogatell 80,excersice

In [193]:
exc.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\excercice\\excersice.csv", index=False)

### pools.

In [194]:
pool = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\pools.csv")

In [195]:
pool = eq.clean_pool (pool)

In [196]:
pool.sample()

,name,barri_id,barri,district_id,district,latitud,longitud,address,category,division
56,Piscines Esportives,45,Porta,8,Nou Barris,41.43616,2.183283,C Rosselló i Porcel 7,piscina,excersice

In [197]:
pool.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\excercice\\pools.csv", index=False)

### walk circuit

In [198]:
walk = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\walk_run_circuits.csv")

In [199]:
walk = eq.clean_circuit (walk)

In [200]:
walk.sample()

,name,barri_id,barri,district_id,district,latitud,longitud,address,category,division
3,Circuit Esportiu Mirador de les Aigües,21,Pedralbes,4,Les Corts,41.393841,2.098001,Ctra Aigües 1,walk_circuit,excersice

In [201]:
walk.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\excercice\\walk_circuit.csv", index=False)