# Mobilidad.

### Bicing.

In [67]:
import pandas as pd
import json
from pandas import json_normalize

import importlib
import sys 
sys.path.append("..\src")
import mobilidad as mo
importlib.reload(mo)

In [68]:
bici = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\bicing\\2019BICING_ESTACIONS.csv")

In [69]:
x = mo.bici_(bici)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\data\..\src\mobilidad.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\data\..\src\mobilidad.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [70]:
x["sub_category"] = "bicing"

C:\Users\ima_n\AppData\Local\Temp\ipykernel_2028\3890464631.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["sub_category"] = "bicing"

In [71]:
x.sample()

,address,bikes,category,division,latitud,longitud,sub_category
55202,Sardenya 362,10,bicing,mobilidad,41.405422,2.17064,bicing

In [72]:
x.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\bicing.csv", index=False)

### Bicipuertos.

In [73]:
with open("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\bicing\\bicipuertos.json") as f:
    puertos = json.load(f)

In [74]:
puertos = mo.bicipuertos (puertos)

In [75]:
puertos["sub_category"] = "bici_puerto"

In [76]:
puertos.sample()

,address,district_id,district,barri_id,barri,category,division,latitud,longitud,sub_category
1750,"RIBES, C., DE 12",02,Eixample,05,el Fort Pienc,puerto_bici,mobilidad,41.377359,2.147228,bici_puerto

In [77]:
puertos.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\bicipuertos.csv", index=False)

### Buses.

In [78]:
bus = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\transporte_publico\ESTACIONS_BUS.csv")

In [79]:
bus = mo.buses (bus)

In [80]:
bus["sub_category"] = "bus"

In [81]:
bus.sample()

,name,district_id,district,barri_id,barri,category,division,latitud,longitud,sub_category
1988,BUS -H12-52--,2,Eixample,8,l'Antiga Esquerra de l'Eixample,Autobusos diürns,mobilidad,41.385938,2.163336,bus

In [82]:
bus.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\bus_stops.csv", index=False)

### Transportes.

In [83]:
tran = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\transporte_publico\TRANSPORTS.csv")

In [84]:
tran = mo.clean_transportes(tran)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\data\..\src\mobilidad.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [85]:
tran["sub_category"] = "metro"

In [86]:
tran.sample()

,name,district_id,district,barri_id,barri,category,division,latitud,longitud,sub_category
254,METRO (L2) - Tetuan-,2,Eixample,7,la Dreta de l'Eixample,Metro i línies urbanes FGC,mobilidad,41.394915,2.175585,metro

In [87]:
tran.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\metro_train.csv", index=False)