# Mobilidad.

### Bicing.

In [44]:
import pandas as pd
import json
from pandas import json_normalize

import importlib
import sys 
sys.path.append("..\src")
import mobilidad as mo
importlib.reload(mo)

In [45]:
bici = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\bicing\\2019BICING_ESTACIONS.csv")

In [46]:
x = mo.bici_(bici)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\data\..\src\mobilidad.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)
d:\ironhack\proyectos\Barcelona_UrbanAnalysis\data\..\src\mobilidad.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [47]:
x.sample()

,address,bikes,category,division,latitud,longitud
302466,(PK) PL. GAL·LA PLACÍDIA 2,4,bicing,mobilidad,41.3989,2.153668

In [48]:
x.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\bicing.csv", index=False)

### Bicipuertos.

In [49]:
with open("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\bicing\\bicipuertos.json") as f:
    puertos = json.load(f)

In [50]:
puertos = mo.bicipuertos (puertos)

In [51]:
puertos.sample()

,address,district_id,district,barri_id,barri,category,division,latitud,longitud
3908,"TORRAS I BAGES, PG., DE 19",09,Sant Andreu,60,Sant Andreu,puerto_bici,mobilidad,41.377359,2.147228

In [52]:
puertos.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\bicipuertos.csv", index=False)

### Buses.

In [53]:
bus = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\transporte_publico\ESTACIONS_BUS.csv")

In [54]:
bus = mo.buses (bus)

In [55]:
bus.sample()

,name,district_id,district,barri_id,barri,category,division,latitud,longitud
2329,NITBUS -N0--,4,Les Corts,19,les Corts,Autobusos nocturns,mobilidad,41.386169,2.135895

In [56]:
bus.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\bus_stops.csv", index=False)

### Transportes.

In [57]:
tran = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\\transporte_publico\TRANSPORTS.csv")

In [58]:
tran = mo.clean_transportes(tran)

d:\ironhack\proyectos\Barcelona_UrbanAnalysis\data\..\src\mobilidad.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [59]:
tran.sample()

,name,district_id,district,barri_id,barri,category,division,latitud,longitud
459,Roquetes (Jaume Pinent)-,8,Nou Barris,50,les Roquetes,Metro i línies urbanes FGC,mobilidad,41.446877,2.174904

In [60]:
tran.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\metro_train.csv", index=False)

In [61]:
outer_merge = pd.merge(tran, bici, how="outer")

In [63]:
x = pd.merge(outer_merge, puertos, how="outer")

In [66]:
y = pd.concat(x, bus)

C:\Users\ima_n\AppData\Local\Temp\ipykernel_2028\3488437701.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only.
  y = pd.concat(x, bus)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [62]:
outer_merge

,name,district_id,district,barri_id,barri,category,division,latitud,longitud,bikes,address
0,Tren AEROPORT - CLOT-,10,Sant Martí,65,el Clot,Tren a l'aeroport,mobilidad,41.410259,2.189397,NaN,NaN
1,FGC - BONANOVA-,5,Sarrià-Sant Gervasi,26,Sant Gervasi - Galvany,Ferrocarrils Generalitat (FGC),mobilidad,41.397791,2.135427,NaN,NaN
2,FGC - EL PUTXET-,5,Sarrià-Sant Gervasi,27,el Putxet i el Farró,Ferrocarrils Generalitat (FGC),mobilidad,41.405731,2.139248,NaN,NaN
3,Clot (Aragó / Meridiana)-,10,Sant Martí,65,el Clot,Metro i línies urbanes FGC,mobilidad,41.409376,2.187234,NaN,NaN
4,Fabra i Puig (Avinguda Meridiana)-,9,Sant Andreu,60,Sant Andreu,Metro i línies urbanes FGC,mobilidad,41.430013,2.183681,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1545564,NaN,NaN,NaN,NaN,NaN,bicing,mobilidad,41.410538,2.158100,0,Cardener 82
1545565,NaN,NaN,NaN,NaN,NaN,bicing,mobilidad,41.410538,2.158100,0,Cardener 82
1545566,NaN,NaN,NaN,NaN,NaN,bicing,mobilidad,41.410538,2.158100,0,Cardener 82
1545567,NaN,NaN,NaN,NaN,NaN,bicing,mobilidad,41.410538,2.158100,0,Cardener 82
1545568,NaN,NaN,NaN,NaN,NaN,bicing,mobilidad,41.410538,2.158100,0,Cardener 82