# Estadistic and difusion.

In [1]:
from bs4 import BeautifulSoup 
import pandas as pd
import requests
import re
import importlib

import sys 
sys.path.append("..\src")
import social as soc
importlib.reload(soc)

import plotly

## Vivienda.

#### Alquiler. Mercado contractual de alquiler en Barcelona por barrios. 2022.

Alquiler medio mensual ($/mes)

In [98]:
price_housing = 'https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Habitatge_i_mercat_immobiliari/Mercat_immobiliari/Habitatges_lloguer/a2022/tbarris1.htm'

In [99]:
df = soc.scraping_prices (price_housing)
df['barri_id'] = range(1, 1+len(df))

In [145]:
df = df[df["3er trimestre"] != "nd"]
df = df[df["1er trimestre"] != "nd"]

In [188]:
df.sample()

,district_id,barri,1er trimestre,2do trimestre,3er trimestre,barri_id,total
72,10,la Verneda i la Pau,733,757,775,73,755.0

In [185]:
df["1er trimestre"] = df["1er trimestre"].apply(lambda x: x.split (",")[0].replace(".","")).astype(int)
df["2do trimestre"] = df["2do trimestre"].apply(lambda x: x.split (",")[0].replace(".","")).astype(int)
df["3er trimestre"] = df["3er trimestre"].apply(lambda x: x.split (",")[0].replace(".","")).astype(int)

In [186]:
mean = df[["1er trimestre", "2do trimestre", "3er trimestre"]].mean(axis=1)
df["total"] = mean

In [187]:
df

,district_id,barri,1er trimestre,2do trimestre,3er trimestre,barri_id,total
0,1,el Raval,917,872,928,1,905.666667
1,1,el Barri Gňtic,1181,1062,1111,2,1118.000000
2,1,la Barceloneta,999,900,922,3,940.333333
3,1,"Sant Pere, Santa Caterina i la Ribera",1022,1051,1084,4,1052.333333
4,2,el Fort Pienc,957,1106,1118,5,1060.333333
...,...,...,...,...,...,...,...
68,10,Diagonal Mar i el Front Marítim del Poblenou,964,1238,1354,69,1185.333333
69,10,el Besňs i el Maresme,796,779,761,70,778.666667
70,10,Provençals del Poblenou,939,1032,1059,71,1010.000000
71,10,Sant Martí de Provençals,796,843,1158,72,932.333333
72,10,la Verneda i la Pau,733,757,775,73,755.000000

In [171]:
df.sample()

,district_id,barri,1er trimestre,2do trimestre,3er trimestre,barri_id
68,10,Diagonal Mar i el Front Marítim del Poblenou,964,1238,1354,69

In [7]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\housing_price.csv", index=False)

## Indice socioeconomico.
#### Indice socioeconomico territorial (IST). 2015-2019

promedio del valor socioeconomico. no tiene num valor.

In [189]:
sociecon = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Condicions_de_vida/Index_socioeconomic/f01.htm"

In [190]:
socioec = soc.scraping_sociecon (sociecon)

In [191]:
socioec["barri"] = socioec["barri"].apply(lambda x: x.replace("ñ", "o"))

In [192]:
socioec['barri_id'] = range(1, 1+len(socioec))

In [193]:
socioec

,district_id,barri,2015,2016,2017,2018,2019,barri_id
0,1,el Raval,"72,1","73,1","74,0","76,0","77,4",1
1,1,el Barri Gňtic,"96,7","96,9","95,0","90,9","83,9",2
2,1,la Barceloneta,"93,3","95,1","95,1","95,4","95,6",3
3,1,"Sant Pere, Santa Caterina i la Ribera","98,8","99,6","99,7","100,6","101,3",4
4,2,el Fort Pienc,"113,7","114,0","112,9","113,2","112,2",5
...,...,...,...,...,...,...,...,...
67,10,el Poblenou,"112,2","113,0","113,1","114,0","114,0",68
68,10,Diagonal Mar i el Front Marítim del Poblenou,"118,8","119,1","118,3","117,1","116,4",69
69,10,el Besňs i el Maresme,"78,0","78,5","78,5","77,3","75,2",70
70,10,Provençals del Poblenou,"107,5","107,6","107,7","107,9","107,6",71
71,10,Sant Martí de Provençals,"104,3","104,7","103,9","104,3","103,5",72

In [34]:
socioec.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\nivel_socioeconomi.csv", index=False)

## Seguridad.

### Denuncias policia Urbana.

#### sistema de seguridad publica.
Indicadores por distritos. 2020

In [196]:
seguridad = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Guardia_urbana/t67.htm"

In [198]:
df = soc.seguridad (seguridad)
df.sample(5)

,district_id,district,denuncias por infracción de la ordenanza de convivencia ciudadana (% habitantes),incidentes pordegradación del espacio público (‰ habitantes),incidentes en laconvivenciavecinal (‰ habitantes),incidentes por actividadesmolestas en el espaciopúblico (‰ habitantes),incidentes por actividadesindebidas en el espaciopúblico (‰ habitantes)
4,5,Sarriŕ-Sant Gervasi,"0,48","1,30","31,39","18,72","2,19"
0,1,Ciutat Vella,"17,16","3,24","73,64","78,57","16,90"
2,3,Sants-Montjuďc,"0,73","2,05","38,47","33,29","3,62"
1,2,L'Eixample,"0,95","1,44","44,28","22,30","4,76"
8,9,Sant Andreu,"0,57","1,80","28,00","22,90","2,50"

In [ ]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\nivel_socioeconomi.csv", index=False)

#### Actuaciones de ayuda y asistencia por distritos.

In [411]:
ayuda = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Guardia_urbana/t37.htm"

1. posiblemente eliminar las incidencias que no tienen mucho que ver con la seguridad como las ayudas por accidentes con el clima etc. 
2. crear un total de las incidencias ya limpias por distrito
3. separar por tipo de incidencias.

In [412]:
ayuda = soc.pol_urbana_ayuda (ayuda)

In [471]:
for i, row in ayuda.iterrows():
    if row[0] == "Fugas-productos químicos":
        ayuda.drop(i, inplace=True)
    if row[0] == "Asistencia a personas en espacios públicos":
        ayuda.drop(i, inplace=True)
    if row[0] == "Infracciones por estacionamientos":
        ayuda.drop(i, inplace=True)    
    if row[0] == "Desconocidos":
        ayuda.drop(i, inplace=True)
    if row[0] == "Desconocido":
        ayuda.drop(i, inplace=True)
    if row[0] == "Molestias por generadores":
        ayuda.drop(i, inplace=True)    
    if row[0] == "Hogueras/barbacoas":
        ayuda.drop(i, inplace=True)
    if row[0] == "Lluvia torrencial":
        ayuda.drop(i, inplace=True)
    if row[0] == "Otras actuaciones en medio ambiente":
        ayuda.drop(i, inplace=True)
    if row[0] == "Vientos fuertes": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Accidente procedente pasarela CME": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Vigilancia policial": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Otras intervenciones de Policía administrativa": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Seńales automatizadas": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Controles de tráfico": 
        ayuda.drop(i, inplace=True)    
    if row[0] == "Obras/ trabajos en espacios públicos": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Asistencia a enfermos mentales": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Asistencia en las playas": 
        ayuda.drop(i, inplace=True)    
    if row[0] == "Nieve y hielo": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Contra los derechos de los trabajadores": 
        ayuda.drop(i, inplace=True)  
    if row[0] == "Caza/pesca/flora/fauna": 
        ayuda.drop(i, inplace=True)

In [473]:
df = ayuda.melt()
df = df[pd.to_numeric(df["value"], errors="coerce").notnull()]
df["value"] = df["value"].apply(lambda x: x.split (",")[0].replace("'","")).astype(float)

C:\Users\ima_n\AppData\Local\Temp\ipykernel_14252\1067461962.py:1: FutureWarning: This dataframe has a column name that matches the 'value_name' column name of the resulting Dataframe. In the future this will raise an error, please set the 'value_name' parameter of DataFrame.melt to a unique name.
  df = ayuda.melt()

In [474]:
df

     variable   value
871     value  57.955
872     value  36.939
873     value  17.865
874     value  16.616
875     value  15.389
...       ...     ...
1603    value       0
1604    value       0
1605    value       0
1606    value       1
1607    value       1

[737 rows x 2 columns]

In [449]:
exclude_strs = ['vía', 'tráfico']
pattern = '|'.join(exclude_strs)
mask = ayuda['Incidencias'].str.contains(pattern)
df = ayuda.loc[mask]

In [450]:
traf = df.melt()
traf = traf[pd.to_numeric(traf["value"], errors="coerce").notnull()]
df = traf.drop(traf[traf['value'] == '7.553'].index)
traf["value"] = traf["value"].astype(int)

traf = df[["variable", "value"]].groupby(by="variable").agg("sum")
traf

ValueError: invalid literal for int() with base 10: '7.553'

In [428]:
traf = df.melt()
traf = traf[pd.to_numeric(traf["value"], errors="coerce").notnull()]
traf["value"] = traf["value"].astype(str)
traf["value"] = traf["value"].apply(lambda x: x.split (",")[0].replace("'","")).astype(int)
traf["value"] = traf["value"].astype(int)
try:   
    traf = traf[["variable", "value"]].groupby(by="variable").agg("sum")
except:
    pass
traf

ValueError: invalid literal for int() with base 10: '7.553'

In [ ]:
try:
    traf["value"] = traf["value"].apply(lambda x: x.split (",")[0].replace("'","")).astype(int)
    traf["value"] = traf["value"].astype(int)
    traf = traf[["variable", "value"]].groupby(by="variable").agg("sum")
except:
    pass
traf

In [405]:
traf["value"] = traf["value"].astype(int)
traf = traf[["variable", "value"]].groupby(by="variable").agg("sum")

OverflowError: Python int too large to convert to C long

In [267]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\ayuda_asistencia.csv", index=False)

### Mossos de squadra.

Hechos conocidos por distrito.

In [464]:
mossos = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Mossos_esquadra/t112.htm"

In [465]:
df = soc.mossos_inc(mossos)
df.sample()

,Incidencias,Barcelona,1.Ciutat Vella,2.L'Eixample,3.Sants-Monjuïc,4.Les Corts,5.Sarrià-Sant Gervasi,6.Gràcia,7.Horta-Guiardó,8.Nou Barris,9.Sant Andreu,10.Sant Martí
38,Detención ilegal,20,6,4,4,0,1,2,0,1,1,1

In [466]:
df = df.melt()
df = df[pd.to_numeric(df["value"], errors="coerce").notnull()]
df["value"] = df["value"].apply(lambda x: x.split (",")[0].replace("'","")).astype(float)

df

          variable   value
66       Barcelona  57.263
67       Barcelona  17.655
68       Barcelona  11.289
69       Barcelona  11.153
70       Barcelona  10.957
..             ...     ...
787  10.Sant Martí   1.000
788  10.Sant Martí   0.000
789  10.Sant Martí   0.000
790  10.Sant Martí   0.000
791  10.Sant Martí   0.000

[726 rows x 2 columns]

In [455]:
df = df.melt()
df = df[pd.to_numeric(df["value"], errors="coerce").notnull()]
df["value"] = df["value"].apply(lambda x: x.split (",")[0].replace("'","")).astype(float)
try:
    df["value"] = df["value"].astype(int)
    x = df[["variable", "value"]].groupby(by="variable").agg("sum")
except:
    pass

In [456]:
x

                       value
variable
1.Ciutat Vella          4233
10.Sant Martí           3629
2.L'Eixample            3901
3.Sants-Monjuïc         3796
4.Les Corts             3801
5.Sarrià-Sant Gervasi   4315
6.Gràcia                2914
7.Horta-Guiardó         4593
8.Nou Barris            4723
9.Sant Andreu           4208
Barcelona               5179

In [51]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\mossos_asistencia_ayuda.csv", index=False)

### Poblacion.

edad por grandes grupos de edad 2021 por barrios.

In [215]:
poblacion = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Poblacio_i_demografia/Poblacio/Xifres_oficials_poblacio/a2021/edat/edatg05.htm"

In [216]:
df = soc.poblation(poblacion)

In [218]:
df.sample()

,Dto.,Barrio,TOTAL,0-14 años,15-24 años,25-64 años,65 años y más
25,52,Sant Gervasi - Galvany,46.816,6.431,5.504,24.334,10.547

In [52]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\densidad_poblacion.csv", index=False)