# Estadistic and difusion.

In [6]:
from bs4 import BeautifulSoup 
import pandas as pd
import requests
import re
import importlib

import sys 
sys.path.append("..\src")
import social as soc
importlib.reload(soc)

import plotly

## Vivienda.

#### Alquiler. Mercado contractual de alquiler en Barcelona por barrios. 2022.

Alquiler medio mensual ($/mes)

In [4]:
price_housing = 'https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Habitatge_i_mercat_immobiliari/Mercat_immobiliari/Habitatges_lloguer/a2022/tbarris1.htm'

In [32]:
df = soc.scraping_prices (price_housing)
df['barri_id'] = range(1, 1+len(df))
df

,district_id,barri,1er trimestre,2do trimestre,3er trimestre,barri_id
0,1,el Raval,"917,0","872,0","928,1",1
1,1,el Barri Gňtic,"1.181,6","1.062,5","1.111,3",2
2,1,la Barceloneta,"999,8","900,5","922,9",3
3,1,"Sant Pere, Santa Caterina i la Ribera","1.022,8","1.051,4","1.084,9",4
4,2,el Fort Pienc,"957,9","1.106,9","1.118,7",5
...,...,...,...,...,...,...
68,10,Diagonal Mar i el Front Marítim del Poblenou,"964,7","1.238,7","1.354,9",69
69,10,el Besňs i el Maresme,"796,9","779,2","761,4",70
70,10,Provençals del Poblenou,"939,2","1.032,9","1.059,4",71
71,10,Sant Martí de Provençals,"796,4","843,0","1.158,9",72
72,10,la Verneda i la Pau,"733,9","757,0","775,8",73

In [7]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\housing_price.csv", index=False)

## Indice socioeconomico.
#### Indice socioeconomico territorial (IST). 2015-2019

promedio del valor socioeconomico. no tiene num valor.

In [53]:
sociecon = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Condicions_de_vida/Index_socioeconomic/f01.htm"

In [54]:
socioec = soc.scraping_sociecon (sociecon)

In [55]:
socioec["barri"] = socioec["barri"].apply(lambda x: x.replace("ñ", "o"))

In [56]:
socioec['barri_id'] = range(1, 1+len(socioec))

In [57]:
socioec

,district_id,barri,2015,2016,2017,2018,2019,barri_id
0,1,el Raval,"72,1","73,1","74,0","76,0","77,4",1
1,1,el Barri Gňtic,"96,7","96,9","95,0","90,9","83,9",2
2,1,la Barceloneta,"93,3","95,1","95,1","95,4","95,6",3
3,1,"Sant Pere, Santa Caterina i la Ribera","98,8","99,6","99,7","100,6","101,3",4
4,2,el Fort Pienc,"113,7","114,0","112,9","113,2","112,2",5
...,...,...,...,...,...,...,...,...
67,10,el Poblenou,"112,2","113,0","113,1","114,0","114,0",68
68,10,Diagonal Mar i el Front Marítim del Poblenou,"118,8","119,1","118,3","117,1","116,4",69
69,10,el Besňs i el Maresme,"78,0","78,5","78,5","77,3","75,2",70
70,10,Provençals del Poblenou,"107,5","107,6","107,7","107,9","107,6",71
71,10,Sant Martí de Provençals,"104,3","104,7","103,9","104,3","103,5",72

In [34]:
socioec.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\nivel_socioeconomi.csv", index=False)

## Seguridad.

### Denuncias policia Urbana.

#### sistema de seguridad publica.
Indicadores por distritos. 2020

In [58]:
seguridad = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Guardia_urbana/t67.htm"

In [59]:
df = soc.seguridad (seguridad)
df.sample()

,district_id,district,denuncias por infracción de la ordenanza de convivencia ciudadana (% habitantes),incidentes pordegradación del espacio público (‰ habitantes),incidentes en laconvivenciavecinal (‰ habitantes),incidentes por actividadesmolestas en el espaciopúblico (‰ habitantes),incidentes por actividadesindebidas en el espaciopúblico (‰ habitantes)
4,5,Sarriŕ-Sant Gervasi,"0,48","1,30","31,39","18,72","2,19"

In [ ]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\nivel_socioeconomi.csv", index=False)

#### Actuaciones de ayuda y asistencia por distritos.

In [71]:
ayuda = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Guardia_urbana/t37.htm"

1. posiblemente eliminar las incidencias que no tienen mucho que ver con la seguridad como las ayudas por accidentes con el clima etc. 
2. crear un total de las incidencias ya limpias por distrito
3. separar por tipo de incidencias.

In [72]:
ayuda = soc.pol_urbana_ayuda (ayuda)

In [73]:
ayuda.Infracciones

AttributeError: 'DataFrame' object has no attribute 'Infracciones'

In [81]:
if ayuda.Incidencias == "Fugas-productos químicos":
    ayuda.drop(inplace=True, )

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [89]:
for i, row in ayuda.iterrows():
    if row[0] == "Fugas-productos químicos":
        ayuda.drop(i, inplace=True)
    if row[0] == "Asistencia a personas en espacios públicos":
        ayuda.drop(i, inplace=True)
    if row[0] == "Infracciones por estacionamientos":
        ayuda.drop(i, inplace=True)    
    if row[0] == "Desconocidos":
        ayuda.drop(i, inplace=True)
    if row[0] == "Desconocido":
        ayuda.drop(i, inplace=True)
    if row[0] == "Molestias por generadores":
        ayuda.drop(i, inplace=True)    
    if row[0] == "Hogueras/barbacoas":
        ayuda.drop(i, inplace=True)
    if row[0] == "Lluvia torrencial":
        ayuda.drop(i, inplace=True)
    if row[0] == "Otras actuaciones en medio ambiente":
        ayuda.drop(i, inplace=True)
    if row[0] == "Vientos fuertes": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Accidente procedente pasarela CME": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Vigilancia policial": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Otras intervenciones de Policía administrativa": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Seńales automatizadas": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Controles de tráfico": 
        ayuda.drop(i, inplace=True)    
    if row[0] == "Obras/ trabajos en espacios públicos": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Asistencia a enfermos mentales": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Asistencia en las playas": 
        ayuda.drop(i, inplace=True)    
    if row[0] == "Nieve y hielo": 
        ayuda.drop(i, inplace=True)
    if row[0] == "Contra los derechos de los trabajadores": 
        ayuda.drop(i, inplace=True)  
    if row[0] == "Caza/pesca/flora/fauna": 
        ayuda.drop(i, inplace=True)

In [87]:
print(list(ayuda.Incidencias))

['Convivencia vecinal', 'Actividades molestas en espacios públicos', 'Otras actuaciones de seguridad ciudadana', 'Infracciones en vados y reservas', 'Infracciones en movimiento', 'Actas contra la propiedad privada', 'Colaboración con otros servicios', 'Accidentes de tráfico con heridos', 'Soportes tráfico', 'Incidencias de locales', 'Incidencias con afectación de vía', 'Accidentes de tráfico sin heridos', 'Asistencia a personas en edificio', 'Incendios', 'Incidencias con peligro por el tráfico', 'Animales de compańía', 'Estupefacientes/psicotrópicos', 'Agresiones', 'Manifestaciones/concentraciones', 'Inspecciones/controles en locales', 'Alarmas de incendio/robo', 'Restricciones temporales de tráfico', 'Peleas de animales', 'Traslados de vehículos sin infracción', 'Violencia doméstica', 'Infracciones en locales', 'Averías de servicios públicos', 'Averías de servicios municipales', 'Venta ambulante', 'Conflictos en locales', 'Vandalismo', 'Colaboración con autoridad judicial /policial', 'Animales/insectos peligrosos', 'Ámbito de protección del menor', 'Asistencia a conductor en vía pública', 'Ocupaciones de espacios públicos', 'Siniestros en edificios', 'Vertido de residuos', 'Espectáculos en espacios públicos', 'Otras incidencias con animales', 'Conducciones y acompańamientos', 'Infracciones en movimiento (vehículos)', 'Seńales no automatizadas', 'Contra la libertad sexual', 'Actos contra la propiedad pública', 'Delitos contra el orden público', 'Atentados', 'Materias peligrosas', 'Inmovilizaciones/desinmovilizaciones', 'Transporte público', 'Ocupaciones ilícitas', 'Reforma', 'Actividad con presos', 'Actos contra la propiedad', 'Comunicados de emergencia', 'Avería técnica SPEIS', 'Ámbito educativo', 'Sin identificar', 'Edificios oficiales', 'Infracciones de extranjeros', 'Incidencias de alimentos', 'Explosiones', 'Custodias presos y detenidos', 'Suministro básico', 'Tribus urbanas', 'Asistencia técnica', 'Delitos alimenticios', 'Desconocido']

In [90]:
ayuda

,Incidencias,Barcelona,1.Ciutat Vella,2.L'Eixample,3.Sants-Monjuïc,4.Les Corts,5.Sarrià-Sant Gervasi,6.Gràcia,7.Horta-Guiardó,8.Nou Barris,9.Sant Andreu,10.Sant Martí
0,Convivencia vecinal,57.955,7.645,11.474,6.783,2.030,4.842,4.512,4.784,5.281,4.020,6.456
2,Actividades molestas en espacios públicos,36.939,6.353,4.445,4.477,1.394,2.318,2.512,2.827,3.955,2.456,5.721
4,Otras actuaciones de seguridad ciudadana,17.865,3.437,3.373,1.877,504,1.044,1.100,1.181,1.411,1.313,2.315
5,Infracciones en vados y reservas,16.616,1.122,3.119,1.750,774,1.780,1.306,1.714,1.858,1.179,1.985
6,Infracciones en movimiento,15.389,2.382,3.622,1.406,512,1.181,660,996,1.189,962,1.661
...,...,...,...,...,...,...,...,...,...,...,...,...
77,Custodias presos y detenidos,11,2,2,7,0,0,0,0,0,0,0
78,Suministro básico,11,0,3,2,0,0,1,0,2,3,0
81,Tribus urbanas,5,0,1,3,0,0,1,0,0,0,0
82,Asistencia técnica,3,0,0,1,0,0,0,1,0,0,1
83,Delitos alimenticios,3,0,2,0,0,0,0,0,0,0,1

In [49]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\ayuda_asistencia.csv", index=False)

#### Circulacion vehicular.

Denuncias policia de circulacion por distrits.

In [98]:
circulacion = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Guardia_urbana/t17.htm"

1. investigar que tipo de incidentes son y si valen la pena agregarlos.
2. sacar el total por cada distrito.
3. sacar el porcentaje debido a la poblacion, mientras mas gente viva ahi obviamente mas accidentes.

In [99]:
df = soc.circulacion(circulacion)
df

,Incidencias,Barcelona,1.Ciutat Vella,2.L'Eixample,3.Sants-Monjuïc,4.Les Corts,5.Sarrià-Sant Gervasi,6.Gràcia,7.Horta-Guiardó,8.Nou Barris,9.Sant Andreu,10.Sant Martí
0,Ordenanza de circulación de peatones y vehículos,75.291,14.604,9.354,5.720,4.652,9.244,6.896,4.094,8.438,5.058,7.131
1,Reglamento general de circulación,66.053,10.156,14.550,5.848,3.254,6.038,4.026,3.479,3.980,4.532,9.935
2,Reglamento general de vehículos,13.250,1.872,2.117,1.634,663,1.494,767,622,1.031,924,2.074
3,Reglamento general de conductores,5.951,773,1.133,719,281,388,323,349,649,414,900
4,Ley responsabilidad civil y seguros circulació...,5.183,507,782,561,241,373,210,362,867,467,792
5,Ley seguridad vial,1.960,208,277,545,54,148,96,87,110,128,300
6,Ley de ordenación de transporte terrestre,858,66,12,487,45,34,12,46,20,57,79
7,Reglamento metropolitano del taxi,415,106,85,73,21,33,13,19,7,21,35
8,Reglamento VTC urbano (vehículos con conductor),105,22,7,45,2,4,3,0,0,2,18
9,Decreto ley enero 4/2019 medidas urgentes en t...,97,26,14,42,1,3,1,0,0,1,9
10,Ley reguladora del acceso motorizado al medio ...,63,0,0,0,0,8,1,36,16,1,0
11,Reglamento ordenación de transporte terrestre,35,5,3,19,0,1,0,0,0,1,5
12,Ordenanza zona de bajas emisiones,33,1,5,4,0,3,5,2,6,0,6
13,Decreto ley enero 5/2017 de medidas urgentes p...,14,5,0,9,0,0,0,0,0,0,0
14,Ley catalana 12/87 transporte de viajeros vehí...,4,1,1,2,0,0,0,0,0,0,0
15,Ley taxi 19_2013,2,0,0,1,0,0,1,0,0,0,0
16,Reglamento regulador de las escuelas particula...,2,0,0,1,0,0,0,0,0,1,0

In [100]:
for i, row in df.iterrows():
    if row[0] == "Reglamento general de vehículos":
        ayuda.drop(i, inplace=True)
    if row[0] == "Reglamento general de conductores":
        ayuda.drop(i, inplace=True)
    if row[0] == "Ley de ordenación de transporte terrestre":
        ayuda.drop(i, inplace=True)    
    if row[0] == "Reglamento metropolitano del taxi":
        ayuda.drop(i, inplace=True)
    if row[0] == "Reglamento VTC urbano (vehículos con conductor)":
        ayuda.drop(i, inplace=True)
    if row[0] == "Molestias por generadores":
        ayuda.drop(i, inplace=True)    
    if row[0] == "Hogueras/barbacoas":
        ayuda.drop(i, inplace=True)

KeyError: '[2] not found in axis'

In [96]:
print(list(df.Incidencias))

['Ordenanza de circulación de peatones y vehículos', 'Reglamento general de circulación', 'Reglamento general de vehículos', 'Reglamento general de conductores', 'Ley responsabilidad civil y seguros circulación vehículo a motor', 'Ley seguridad vial', 'Ley de ordenación de transporte terrestre', 'Reglamento metropolitano del taxi', 'Reglamento VTC urbano (vehículos con conductor)', 'Decreto ley enero 4/2019 medidas urgentes en transporte de viajeros alquiler vehículos con conductor', 'Ley reguladora del acceso motorizado al medio natural', 'Reglamento ordenación de transporte terrestre', 'Ordenanza zona de bajas emisiones', 'Decreto ley enero 5/2017 de medidas urgentes para la ordenación de los servicios de transporte de viajeros', 'Ley catalana 12/87 transporte de viajeros vehículos motor', 'Ley taxi 19_2013', 'Reglamento regulador de las escuelas particulares de conductores']

In [50]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\falta_vialidad.csv", index=False)

### Mossos de squadra.

Hechos conocidos por distrito.

In [14]:
mossos = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Societat_i_condicions_de_vida/Seguretat_i_prevencio/Mossos_esquadra/t112.htm"

In [15]:
df = soc.mossos_inc(mossos)
df

,Incidencias,Barcelona,1.Ciutat Vella,2.L'Eixample,3.Sants-Monjuïc,4.Les Corts,5.Sarrià-Sant Gervasi,6.Gràcia,7.Horta-Guiardó,8.Nou Barris,9.Sant Andreu,10.Sant Martí
0,Hurto,57.263,12.282,13.009,6.209,2.602,2.863,2.288,2.680,2.987,4.123,7.453
1,Estafas,17.655,1.252,3.354,1.959,951,1.753,1.314,1.595,1.530,1.446,2.460
2,Dańos,11.289,1.423,1.875,1.294,511,829,690,981,920,854,1.876
3,Robo con fuerza interior vehículo,11.153,1.502,2.510,1.167,822,902,448,774,495,588,1.836
4,Robo con violencia y/o intimidación,10.957,2.858,1.806,1.342,388,669,400,520,669,626,1.601
...,...,...,...,...,...,...,...,...,...,...,...,...
61,Sustracción de cosa propia de utilidad social,2,0,0,0,0,0,0,1,0,0,1
62,Asesinato consumado,1,0,0,1,0,0,0,0,0,0,0
63,Asesinato tentativa,1,1,0,0,0,0,0,0,0,0,0
64,Contra los recursos naturales y el medio ambiente,1,0,0,0,0,0,0,0,1,0,0
65,Omisión del deber de socorros,1,0,1,0,0,0,0,0,0,0,0

In [ ]:
df.

In [51]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\mossos_asistencia_ayuda.csv", index=False)

### Poblacion.

edad por grandes grupos de edad 2021 por barrios.

In [16]:
poblacion = "https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Poblacio_i_demografia/Poblacio/Xifres_oficials_poblacio/a2021/edat/edatg05.htm"

In [17]:
df = soc.poblation(poblacion)
df

,Dto.,Barrio,TOTAL,0-14 años,15-24 años,25-64 años,65 años y más
0,1,el Raval,47.228,6.032,4.978,30.885,5.333
1,1,el Barri Gòtic,21.827,1.439,2.364,15.859,2.165
2,1,la Barceloneta,14.643,1.065,1.245,9.822,2.511
3,1,"Sant Pere, Santa Caterina i la Ribera",22.131,1.974,2.171,14.945,3.041
4,2,el Fort Pienc,31.262,3.329,2.789,18.292,6.852
...,...,...,...,...,...,...,...
67,10,el Poblenou,33.976,4.968,3.059,20.428,5.521
68,10,Diagonal Mar i el Front Marítim del Poblenou,13.323,2.350,1.173,7.694,2.106
69,10,el Besòs i el Maresme,25.657,3.557,2.780,15.085,4.235
70,10,Provençals del Poblenou,20.949,2.891,1.827,12.393,3.838
71,10,Sant Martí de Provençals,26.032,2.991,2.368,14.083,6.590

In [52]:
df.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\\to_tableau\\densidad_poblacion.csv", index=False)