In [1]:
import pandas as pd
import sqlalchemy as alch
from getpass import getpass
import pymysql
from sqlalchemy import create_engine, text

### Connect to SQL

In [2]:
sqlpassword = getpass()
dbName = "Barcelona"
connectionData = f"mysql+pymysql://root:{sqlpassword}@localhost/{dbName}"

engine = alch.create_engine(connectionData)

### Mobilidad.

In [3]:
bicing = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\bicing.csv")
bicing.to_sql("bicing", if_exists="append", con=engine, index=False)

11022

In [4]:
bici_puertos = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\bicipuertos.csv")
bici_puertos.to_sql("bici_puertos", if_exists="append", con=engine, index=False)

3610

In [5]:
bus_stops = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\bus_stops.csv")
bus_stops.to_sql("bus_stops", if_exists="append", con=engine, index=False)

3224

In [6]:
metro_train = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mobilidad\\metro_train.csv")
metro_train.to_sql("metro_train", if_exists="append", con=engine, index=False)

488

In [8]:
mobilidad = pd.read_sql_query(sql=text("""
SELECT category,  division, latitud, longitud, sub_category 
	FROM bicing
		UNION 
SELECT category, division, latitud, longitud, sub_category 
	FROM bici_puertos
    WHERE category = "puerto_bici"
		UNION
SELECT category, division, latitud, longitud, sub_category 
	FROM bus_stops
		UNION
SELECT category, division, latitud, longitud, sub_category 
	FROM metro_train;
"""), con=engine.connect())

In [9]:
mobilidad

,category,division,latitud,longitud,sub_category
0,bicing,mobilidad,41.397952,2.180042,bicing
1,bicing,mobilidad,41.395530,2.177060,bicing
2,bicing,mobilidad,41.394055,2.181299,bicing
3,bicing,mobilidad,41.393480,2.181555,bicing
4,bicing,mobilidad,41.391075,2.180223,bicing
...,...,...,...,...,...
4171,Metro i línies urbanes FGC,mobilidad,41.392365,2.181191,metro
4172,Metro i línies urbanes FGC,mobilidad,41.403863,2.173644,metro
4173,Ferrocarrils Generalitat (FGC),mobilidad,41.406043,2.139256,metro
4174,Estació marítima,mobilidad,41.368076,2.175174,metro
4175,Estació marítima,mobilidad,41.350989,2.174790,metro

In [10]:
mobilidad.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mapping\mobilidad.csv", index=False)

### Equipamiento.

In [11]:
civic = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\equipamiento\\centre_civic.csv")
civic.to_sql("civic_centre", if_exists="append", con=engine, index=False)

51

In [12]:
hos = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\equipamiento\\hospitals.csv")
hos.to_sql("hospitals", if_exists="append", con=engine, index=False)

142

In [13]:
school = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\equipamiento\\schools.csv")
school.to_sql("schools", if_exists="append", con=engine, index=False)

1972

In [14]:
equipamiento = pd.read_sql_query(sql=text("""
SELECT name, category, division, latitud, longitud, sub_category
	FROM hospitals
		UNION
SELECT name, category, division, latitud, longitud, sub_category
	FROM civic_centre
		UNION
SELECT name, category, division, latitud, longitud, sub_category
		FROM schools;
"""), con=engine.connect())

In [15]:
equipamiento

,name,category,division,latitud,longitud,sub_category
0,Hospital El Pilar - Institut Cardiovascular Sa...,Hospitals i clíniques,equipamiento,41.400457,2.148500,hospitals
1,Centre d'Atenció Primària Vallvidrera,CAPs,equipamiento,41.413818,2.104164,hospitals
2,Centre d'Atenció Primària Turó,CAPs,equipamiento,41.433082,2.170579,hospitals
3,Centre d'Atenció Primària El Clot,CAPs,equipamiento,41.411767,2.193049,hospitals
4,Clínica Sant Antoni,Hospitals i clíniques,equipamiento,41.356077,2.143294,hospitals
...,...,...,...,...,...,...
2160,Escola de Doctorat - UB,Universitats,equipamiento,41.384856,2.162637,schools
2161,Institut de Biologia Evolutiva,Universitats,equipamiento,41.385565,2.193994,schools
2162,Nuclio Digital School,Informàtica,equipamiento,41.407147,2.175102,schools
2163,Llar d'Infants El Camí Feliç ZAL Port,Ensenyament infantil (0-3 anys),equipamiento,41.322168,2.134977,schools
2164,Llar d'Infants Kasperle,Ensenyament infantil (0-3 anys),equipamiento,41.400944,2.154074,schools

In [16]:
equipamiento.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mapping\equipamiento.csv", index=False)

### culto y ocio.

In [17]:
cine = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\cult_ocio\\cinemas.csv")
cine.to_sql("cinemas", if_exists="append", con=engine, index=False)

195

In [18]:
mus = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\cult_ocio\\museums_libraries.csv")
mus.to_sql("museums_libraries", if_exists="append", con=engine, index=False)

455

In [19]:
drinks = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\cult_ocio\\music_drinks.csv")
drinks.to_sql("music_drinks", if_exists="append", con=engine, index=False)

618

In [20]:
rest = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\cult_ocio\\restaurants.csv")
rest.to_sql("restaurants", if_exists="append", con=engine, index=False)

2557

In [21]:
oci = pd.read_sql_query(sql=text("""
SELECT name, category, division, latitud, longitud, sub_category
	FROM cinemas
		UNION
SELECT name, category, division, latitud, longitud, sub_category
	FROM museums_libraries
		UNION
SELECT name, category, division, latitud, longitud, sub_category
		FROM music_drinks
        UNION
SELECT name, category, division, latitud, longitud, sub_category
    FROM restaurants;
"""), con=engine.connect())

In [22]:
oci

,name,category,division,latitud,longitud,sub_category
0,Auditòrium,Auditoris,equipamiento,41.382838,2.176818,cines
1,Teatre,Teatres,equipamiento,41.435729,2.186494,cines
2,Sala de Cinema,Cinemes,equipamiento,41.376851,2.173408,cines
3,Teatre,Teatres,equipamiento,41.410450,2.182461,cines
4,Teatre Romea,Teatres,equipamiento,41.380585,2.171083,cines
...,...,...,...,...,...,...
3817,Bar Neutral,Restaurants,cultura/ocio,41.393553,2.138566,restaurants
3818,Restaurant Khalijia Shisha,Restaurants,cultura/ocio,41.390253,2.170580,restaurants
3819,Hamburgueseria Rock & Boom,Restaurants,cultura/ocio,41.398400,2.159791,restaurants
3820,Restaurant Bo de Bernat,Restaurants,cultura/ocio,41.380510,2.160515,restaurants
3821,Bar Restaurant Chamako,Restaurants,cultura/ocio,41.373813,2.163556,restaurants

In [23]:
oci.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mapping\ocio.csv", index=False)

### Excercise.

In [24]:
exc = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\excercice\excersice.csv")
exc.to_sql("excercise", if_exists="append", con=engine, index=False)

39

In [25]:
pool = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\excercice\pools.csv")
pool.to_sql("pools", if_exists="append", con=engine, index=False)

131

In [26]:
circuit = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\excercice\walk_circuit.csv")
circuit.to_sql("walk_circuit", if_exists="append", con=engine, index=False)

13

In [27]:
exc = pd.read_sql_query(sql=text("""
SELECT name, category, division, latitud, longitud, sub_category
	FROM excercise
		UNION
SELECT name, category, division, latitud, longitud, sub_category
	FROM pools
		UNION
SELECT name, category, division, latitud, longitud, sub_category
		FROM walk_circuit;
"""), con=engine.connect())

In [28]:
exc

,name,category,division,latitud,longitud,sub_category
0,Àrea Esportiva,excersice,excersice,41.436303,2.157824,ejercicio
1,Àrea Esportiva *Pardo - Can Ros - Concepció Ar...,excersice,excersice,41.426917,2.183275,ejercicio
2,Àrea Esportiva,excersice,excersice,41.394603,2.206754,ejercicio
3,Espai Gimnàstic per a Gent Gran *Pujalt,excersice,excersice,41.462926,2.182649,ejercicio
4,Espai Gimnàstic per a Gent Gran *Jocs Esportiu...,excersice,excersice,41.410381,2.212477,ejercicio
...,...,...,...,...,...,...
178,Circuit Esportiu Rambla Prim,walk_circuit,excersice,41.425569,2.200423,walk
179,Circuit Esportiu Diagonal - Cervantes,walk_circuit,excersice,41.392957,2.143527,walk
180,Circuit Esportiu,walk_circuit,excersice,41.378847,2.149250,walk
181,Circuit Esportiu Castell de Montjuïc *circuit 2,walk_circuit,excersice,41.364692,2.166034,walk
182,Circuit Esportiu Can Dragó,walk_circuit,excersice,41.431695,2.181443,walk

In [29]:
exc.to_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv_from_python\mapping\excercise.csv", index=False)